### ISSUE TITLE
Lancaster Stemmer custom rules configuration

### ISSUE THREAD

**Issue by mjunsilo** [dkpro/dkpro-core#1001]
The SMILE lancaster stemmer now supports custom rules to be specified. This feature will add a custom rules configuration parameter to the DKPro LancasterStemmer UIMA wrapper.

**Comment by mjunsilo** [comment]
Initial version can be previewed here:

https://github.com/mjunsilo/dkpro-core/commit/d9f8cf875b45b1eb306e3d1fa1b22b99cd7c7f81

Waiting for version of 1.2.2 SMILE API to be public available before making the pull request. This should happen soon.

**Comment by reckart** [comment]
@mjunsilo looks like SMILE is already at version 1.3.1 (https://github.com/haifengl/smile). Are you still planning on doing a PR on this one?

**Comment by mjunsilo** [comment]
We merged the latest changes to the lancaster stemmer with 1.2.2 a while a go, so this would only be to upgrade to the latest version of the library. I can have a look at it this week, and do a PR if all tests hold. I will just in case check that other modules don't have added this dependency as well so that the upgrade doesn't potentially break anything.

**Comment by mjunsilo** [comment]
I guess it would be overkill to do a new issue on this one, and I can just commit the version update directly to master if you prefer. All tests pass.

**Comment by reckart** [comment]
Please go ahead :)

**Comment by mjunsilo** [comment]
Closing the issue. Just committed an final update of smile-nlp to version 1.3.1.
