### ISSUE TITLE
Stanford corenlp 3.7 not in maven yet

### ISSUE THREAD

**Issue by KnowledgeGarden** [dkpro/dkpro-core#1003]
Build on the master branch fails. Should I be building against an particular branch?

**Comment by reckart** [comment]
I have temporarily added a repo where I deployed the current CoreNLP beta. That should fix the build for you. #1002 https://github.com/dkpro/dkpro-core/commit/c086a7e656617bdac2d0f10185b005ef5674da25

**Comment by KnowledgeGarden** [comment]
Did a pull on master branch and started build again. Same failure.

**Comment by reckart** [comment]
@KnowledgeGarden did you set up some catch-all proxy in your settings.xml? Did you run your build with "-U" so Maven re-attempts the download of the JAR? Did you try manually deleting the failed download from your local repository before retryingt he build?

**Comment by KnowledgeGarden** [comment]
Removed old. Added -U, uncommented out the proxies in Maven's settings.xml. Changed the error message, but no cigar:
Failed to execute goal on project de.tudarmstadt.ukp.dkpro.core.corenlp-gpl: Could not resolve dependencies for project de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.corenlp-gpl:jar:1.9.0-SNAPSHOT: Failed to collect dependencies at edu.stanford.nlp:stanford-corenlp:jar:3.7.0-beta-1: Failed to read artifact descriptor for edu.stanford.nlp:stanford-corenlp:jar:3.7.0-beta-1: Could not transfer artifact edu.stanford.nlp:stanford-corenlp:pom:3.7.0-beta-1 from/to ukp-oss-model-releases (http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local): proxy.host.net: unknown error

Tried to download the package to drop in the repo: download is for 3.7.0.jar

**Comment by reckart** [comment]
Sounds like you still have some proxy configuration that might be causing problems? I have no idea, I haven't seen this error message so far. The build works nicely on our Jenkins.

**Comment by KnowledgeGarden** [comment]
Thanks for the help. The only firewall here is my macbook. I cannot imagine what proxy would change things; settings.xml had all proxy information commented out. Uncommenting did nothing. Wonder if it could be maven itself.  It's the latest 3.3.9, but, for example, doesn't have the "clean" plugin.

**Comment by reckart** [comment]
I am also using Mavsn 3.3.9 on OS X - no problems here. `proxy.host.net: unknown error` sounds like something is odd with your network config. Anyway, something is also odd with the URL. It should be `http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ext-releases-local/` not `...public-model-releases-local`.

**Comment by reckart** [comment]
Btw. I  made another commit some time ago that fixes the repo url in the POM (https://github.com/dkpro/dkpro-core/commit/033242d0bc7a9575de7cc59f5d910519ba9e8156) - maybe you still have a local version before that commit?

**Comment by KnowledgeGarden** [comment]
The pom in my stanfordnlp directory reads <url>https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ext-releases-local</url>; the green line in your change reads <url>https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ext-releases-local</url>
The are the same.

The URL in question is found here: https://github.com/dkpro/dkpro-core/blob/master/pom.xml

**Comment by reckart** [comment]
@KnowledgeGarden ok, we actually found one of our Jenkins jobs that depended on DKPro Core did also fail. We have been able to fix this and also improve the repo declaration in DKPro Core itself now (which was not failing on our Jenkins). Could you please try again if the build works for you with commit d2aa2b975960331642f395c370275e5a4e199866 or higher?

**Comment by KnowledgeGarden** [comment]
Lots of changes! 
did git pull on core, emptied out bad edu.stanford.nlp in .m2
did mvn install -U -DskipTests --> same failure.
Commented out the settings.xml proxy declaration, cleaned out .m2 for stanford again.
What I get:
Failed to execute goal on project de.tudarmstadt.ukp.dkpro.core.corenlp-gpl: Could not resolve dependencies for project de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.corenlp-gpl:jar:1.9.0-SNAPSHOT: Could not find artifact edu.stanford.nlp:stanford-corenlp:jar:3.7.0-beta-1 in ukp-oss-model-releases (http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local)

**Comment by reckart** [comment]
The build failure we had on our Jenkins was in a second project that depended on DKPro Core - here we needed to re-declare the repository. The DKPro Core build itself was already good.

The JAR is not in the public-model-releases-local repo but in `http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-releases`. I don't get why your system is unable to resolve the dependency... I'm afraid, I cannot reproduce the problem here.

**Comment by KnowledgeGarden** [comment]
By downloading the jars, DKPro Core builds. No clue why it was unable to download from the pom with this possible exception: it appeared to start a download. It took me two tries to download the large model jar; first try failed. Still, Core built. Now off to other builds in the project. Thanks!
