### ISSUE TITLE
FrequencyDistribution: clear() method does not reset maxFreq

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#1024]
The `maximum Frequency` value is not reseted when `clear()` is called which might lead to a wrong `most frequent sample`.

https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-api-frequency-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/api/frequency/util/FrequencyDistribution.java#L274

**Comment by Horsmann** [comment]
@reckart Can I merged this into the 1.8.x branch for the 1.8.1 or leave this on master only at the moment?

**Comment by reckart** [comment]
@Horsmann as you wish. Do you plan to do a 1.8.1 release?

**Comment by Horsmann** [comment]
@reckart Not directly. I had the impression you are planning to do a `1.8.1` release because it has a milestone tag. I would certainly endorse you if you want to release a 1.8.1 but I am in no immediate urge to get a new DKPro release :)
