### ISSUE TITLE
New format of LXF Support

### ISSUE THREAD

**Issue by kouylekov-usit** [dkpro/dkpro-core#1027]
The LXF have underwent an update of the format. It is more or less the following:

The annotations class is moved from annotations to its own parameter:

```
{
    "type" : "node",
    "origin" : "dkpro",
    "id" : "dkpro-n8@1",
    "index" : 7,
    "rank" : 0,
    "annotations" : {
      dkpro: {
           "pos" : "DT",
           "class": "morphology"
      }
 }
```
becomes:

```
{
    "type" : "node",
    "origin" : "dkpro",
    "id" : "dkpro-n8@1",
    "index" : 7,
    "rank" : 0,
    "annotation_class" : "morphology",
    "annotations" : {
      "pos" : "DT"
    }
```

**Comment by reckart** [comment]
Anything else to do here or is this issue resolved?

**Comment by kouylekov-usit** [comment]
Yes. We are in a progress of updating again in a major overhaul. So for now you can leave it open.

Cheers Milen

**Comment by reckart** [comment]
@kouylekov-usit Since there have been no further changes here for a while, I am closing it. If you do any further changes before 1.9.0 is release, please re-open. Otherwise, please open separate issues for improvements in 1.10.0.
