### ISSUE TITLE
newlineIsSentenceBreak parameter of StanfordSegmenter doesn't work

### ISSUE THREAD

**Issue by tbsflk** [dkpro/dkpro-core#1029]
The parameter `newlineIsSentenceBreak` of StanfordSegmenter has no effect. 

I debugged the code and saw that it is passed correctly to the corresponding CoreNLP class [here](https://github.com/dkpro/dkpro-core/blob/8452c7472a56e1578827af8b923e359a4988f3e7/dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordSegmenter.java#L217). However, the issue is that the WordToSentenceProcessor can't really recognize linebreaks as it only gets a list of Tokens from DKPro, built [here](https://github.com/dkpro/dkpro-core/blob/8452c7472a56e1578827af8b923e359a4988f3e7/dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordSegmenter.java#L202), which do not include linebreaks. 

If I add additional token objects for linebreaks to that list, like this

```java
Pattern newline = Pattern.compile(".*(\r\n|\n|\r).*");
int lastTokenEnd = 0;

for (Token token : casTokens) {
   Matcher newlineMatcher = newline.matcher(aJCas.getDocumentText().subSequence(lastTokenEnd, token.getBegin()));
   if (newlineMatcher.matches()) {
      CoreLabel l = new CoreLabel();
      l.set(CharacterOffsetBeginAnnotation.class, lastTokenEnd + newlineMatcher.start(1));
      l.set(CharacterOffsetEndAnnotation.class, lastTokenEnd + newlineMatcher.end(1));
      l.setWord("\n");
      tokensInDocument.add(l);
   }
   lastTokenEnd = token.getEnd();
   ... (add real token)
}
```

it seems to work.

**Comment by reckart** [comment]
Nice catch :) Sounds like a workable solution.
