### ISSUE TITLE
StanfordNamedEntityRecognizer doesn't create annotations that end at the end of a sentence

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#1037]
Looking at the lines [188-211](https://github.com/dkpro/dkpro-core/blob/57dc82892d1bb419158eff37119dfaaca0763d8b/dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizer.java#L188) in StanfordNamedEntityRecognizer I just realized that this tagger doesn't create  annotations that end at the end of a sentence.

So in practice this component expects the last token to be a unimportant token (e.g. punctuation mark indicating end of sentence). I am not sure if this was on purpose?

I think it is wise to check other places were similar code has been used.

- [x] Fix this bug in StanfordNamedEntityRecognizer
- [x] Find other classes which use a similar code

**Comment by maxxkia** [comment]
I have added a test that addresses this.

**Comment by reckart** [comment]
Sounds like a bug.

**Comment by reckart** [comment]
Can you fix it?

**Comment by maxxkia** [comment]
Yup, I have the fix. I'll add it now.

**Comment by maxxkia** [comment]
Fixed it here.
Should also check other classes which use a similar code.

**Comment by reckart** [comment]
Maybe you can search for `"O"` to find similar locations.

**Comment by maxxkia** [comment]
Didn't find any similar code. Will close this issue.

**Comment by reckart** [comment]
:) Thanks
