### ISSUE TITLE
Upgrade to UDPipe 1.1.0

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#1039]
https://github.com/ufal/udpipe/releases/tag/v1.1.0

- [x] probably don't need the hack for installing the library locally anymore (https://github.com/ufal/udpipe/issues/10)
- [x] upload the ud-pipe.jar to UKP repo or Maven Central (@reckart)

Additional tasks deferred to #1141.

**Comment by reckart** [comment]
@kouylekov-usit is this something you would like to do?

**Comment by kouylekov-usit** [comment]
Yes we are. Should I prepare the new build script ? I have created a version with the segmenter wrapper to handle the offsets (will make a pull request for this one). But will be interesting to see what they mean by:

  * Improve|input_format|API to allow inter-block state (for correct tracking of inter-sentence spaces and document-level offsets).


Cheers Milen

**Comment by reckart** [comment]
@kouylekov-usit - yes, the build.xml needs updating - not sure if the models changed, but the binary definitely. No idea what the format change means.

**Comment by kouylekov-usit** [comment]
I am on it

On Apr 3, 2017 11:31 AM, Richard Eckart de Castilho <notifications@github.com> wrote:

@kouylekov-usit<https://github.com/kouylekov-usit> - yes, the build.xml needs updating - not sure if the models changed, but the binary definitely. No idea what the format change means.

**Comment by oepen** [comment]
i have been in touch with milan stranka (the UDPipe developer) on a different project; in that thread, he wrote

> UDPipe 1.1 is able to store token offsets in the CoNLL-U [...]

so possibly the ‘magic’ to recover character offsets from comparing tokens to the underlying document may no longer be required when moving to the new version?

**Comment by kouylekov-usit** [comment]
I will verify. We have a working/tested version of the wrapper if it does not.

Cheers Milen


On Apr 3, 2017 11:39 AM, Stephan Oepen <notifications@github.com> wrote:

i have been in touch with milan stranka (the UDPipe developer) on a different project; in that thread, he wrote

UDPipe 1.1 is able to store token offsets in the CoNLL-U [...]

so possibly the ‘magic’ to recover character offsets from comparing tokens to the underlying document may no longer be required when moving to the new version?

**Comment by reckart** [comment]
@kouylekov-usit I have uploaded a new udpipe 1.1.0 JAR file to the UKP repo and also deployed the new binary JAR there. The POM has been updated accordingly.

**Comment by reckart** [comment]
@kouylekov-usit You should check again in the new 1.1.0 Java API that is now available to the module if you find the methods for accessing the offset information.

**Comment by reckart** [comment]
@kouylekov-usit any news regarding the offsets or any further plans atm?
