### ISSUE TITLE
TreeTagger models

### ISSUE THREAD

**Issue by nilsreiter** [dkpro/dkpro-core#1042]
I added an entry in the build.xml for a middle high german parameter file (gmh, https://github.com/nilsreiter/dkpro-core/commit/668b686af04382b9c1e815eb18243aa899feb968). And while I was at it, I also updated the checksums for (modern) English and German (https://github.com/nilsreiter/dkpro-core/commit/3acd5f53eaf160f196b052330bed2df0ade5f6a0). I can submit a pull request, but I am unsure about the target branch.

Cheers
Nils

**Comment by reckart** [comment]
PRs should go against the master branch.

**Comment by reckart** [comment]
Oh... and thanks! :) It is tedious to keep track of TT models being updated/added/removed, so it is great to get updates and contributions in this area.

**Comment by nilsreiter** [comment]
yes, I can imagine that.
