### ISSUE TITLE
Models for TreeTagger pos tagger for french are not available

### ISSUE THREAD

**Issue by asher-stern** [dkpro/dkpro-core#1046]
Hi.
Perhaps I miss something... I tried to search the documentation and the issues but couldn't find my problem.

I am trying to use TreeTaggerPosTagger for French document (the document language is set to "fr" in the CAS).

I get the error:
```
Failed to serve the given document. ExecutionException: org.apache.uima.analysis_engine.AnalysisEngineProcessException
caused by AnalysisEngineProcessException
caused by IOException: Unable to load resource [classpath:/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/tagger-fr-le.properties]: 
FileNotFoundException: No file found at [classpath:/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/tagger-fr-le.properties]

Please make sure that [de.tudarmstadt.ukp.dkpro.core.treetagger-model-tagger-fr-le] version [20100111.1] is on the classpath.
If the version shown here is not available, try a recent version.

If you are using Maven, add the following dependency to your pom.xml file:

<dependency>
  <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
  <artifactId>de.tudarmstadt.ukp.dkpro.core.treetagger-model-tagger-fr-le</artifactId>
  <version>20100111.1</version>
</dependency>

Please consider that the model you are trying to use may not be publicly
distributable. Please refer to the DKPro Core User Guide for instructions
on how to package non-redistributable models.
```

I tried to add the dependency specified in the error message, but that artifact could not be downloaded.
I tried to add additional UKP repositories to my POM, but this didn't help. the `mvn install` command just fails to download it.

Also, I did not find instructions about non-redistributable models in the user-guide.

Can you please help me with this problem?
Thanks.

**Comment by zesch** [comment]
Hey Asher,

we cannot distribute the TreeTagger models. So you have to build them yourself.
It is a bit hidden in the documentation:
https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/developer-guide.html#_example_how_to_package_treetagger_binaries_and_models

-Torsten

**Comment by asher-stern** [comment]
Hi Torsten.
Thanks very much.
