### ISSUE TITLE
Add CERMINE PDF reader

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#1070]
Implement a UIMA reader based on the CERMINE PDF extraction library:
https://github.com/CeON/CERMINE/

- [x] implement pdf reader component
- [x] normalize whitespace characters, replace \n\t etc. with single whitespace
- [x] add test
- [x] update documentation

**Comment by maxxkia** [comment]
@reckart CERMINE is distributed under AGPL-3.0 license. I checked on a license selector service (https://ufal.github.io/public-license-selector/) and learned that the only additional clause AGPL contains in addition to GPL clauses is that the source code should be applied with the web application. So it's compatible with GPL, so it goes under -gpl module.

But I think I should put an AGPL license header for the classes in Cermine PDF reader module, right?

**Comment by reckart** [comment]
Yep. Should go into the GPL module and the headers should be AGPL headers. We'll have to configure the license-checking maven plugin to check for this header then.

**Comment by maxxkia** [comment]
So should I name the module `dkpro-core-io-pdf-gpl` or `dkpro-core-io-cermine-gpl`? I'd prefer the former.

**Comment by reckart** [comment]
`dkpro-core-io-cermine-gpl`.

**Comment by reckart** [comment]
I think that either whitespace normalization should be an option or it should be not implemented at all and instead handled by a separate WhitespaceNormalizer component. - In any case, is it planned to implement this soonish? Otherwise, I'd tend towards closing this issue and having new issues scheduled for 1.10.0 with further improvements.

**Comment by maxxkia** [comment]
Just added this parameter ;)
Last thing remaining is update the documentation which I will do soon.

**Comment by maxxkia** [comment]
Apparently no more work needs to be done for documentation.
