### ISSUE TITLE
Typos: Semantics.xml

### ISSUE THREAD

**Issue by asher-stern** [dkpro/dkpro-core#1073]
In the description of SemanticPredicate:

The SemanticPredicate annotation can be attached to predicates __in a sentences__.
Semantic predicates express events or situations and take semantic arguments
expressing the participants in these events __ore__ situations.

Typos
1. __in a sentences__ ==> __in a sentence__
2. __ore__ ==> __or__

**Comment by maxxkia** [comment]
Thanks for pointing this out.
