### ISSUE TITLE
Malt parser annotator sets a token as the governor of itself

### ISSUE THREAD

**Issue by asher-stern** [dkpro/dkpro-core#1081]
Using:
LanguageToolSegmenter
StanfordPosTagger
MaltParser

Feeding the sentence:

> When the key is released, a damper stops the strings' vibration, ending the sound.

A Dependency is added on the token "stops", where its governor is the token "stops" itself.

**Comment by reckart** [comment]
In https://github.com/dkpro/dkpro-core/issues/628 it was discussed that all dependency parsers should behave the same for the ROOT dependency and that the ROOT should loop to itself. Does that explain the effect you see?

**Comment by asher-stern** [comment]
Hi.
I was not aware of that.
Yes, it explains it.

**Comment by reckart** [comment]
Ok, I guess we can resolve this as an answered question then.
