### ISSUE TITLE
Add support for the GRAF format

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#110]
```
Add support for the GRAF format (http://www.cs.vassar.edu/~ide/papers/LAW.pdf) using
the ANC UIMA Utils (http://www.anc.org/tools/uima-utils.html).
```

Original issue reported on code.google.com by `richard.eckart` on 2013-02-13 22:17:59

**Comment by reckart** [comment]
The current state of my attempts to create a UIMA  Collection Reader and CAS Consumer components for GrAF in DKPro Core:

There are two tests:

* the GrafWriterTest annotates a sample text and writes it in GrAF format. The problem here is, that the full package names of the types get lost. They get truncated to the last element of the package name, e.g. `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type` becomes `type`. For this test, this is not relevant, but it is when trying to use the generated GrAF file in the next test. 
* the GrafReaderWriterTest tries to do a round-trip GrAF -> UIMA -> GrAF using a frozen copy of the file that is generated by GrafWriterTest. However, I cannot get this working in any way due to the truncated
 package names in the annotation spaces.

The code for the GrafReader also is currently very rough. I'm just trying to get the round-trip working before refining it. It is not meant to work for anything beyond the unit test.

The GrafWriter currently has no support for generating the `header.xml` file that is required by the GrafReader.

So these are my obstacles are currently:

* GrafRenderer does not generate a suitable header.xml file (actually it would be nice if this file wasn't even required...)
* GrafRenderer truncates the package names in the annotation spaces 
* CASFactory does not allow loading data into an existing CAS instead of creating a new CAS. It should assume that the existing CAS has already been suitably initialized

**Comment by reckart** [comment]
Briefly checked out against GrAF UIMA Utils 3.1.1-SNAPSHOT - the type names still appear to be truncated e.g. from `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token` to `type.Token` which prevents the reimport part in the roundtrip.

**Comment by reckart** [comment]
@ksuderman , just noticed you are on GitHub as well (let's see if this message reaches you).

**Comment by ksuderman** [comment]
@reckart yes it did reach me.  I will try to find some hours to put towards tracking down the problem with type names being truncated.

**Comment by reckart** [comment]
Considering that the upstream GRAF Java code is no longer supported and doesn't work anymore with UIMAv3, this issue won't be completed anymore.
