### ISSUE TITLE
Code Style file for Eclipse 4.7+ not found

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#1112]
The following link

> [Eclipse Code Style file](http://dkpro.github.io/files/DKProCoreStyle_20170725.xml) (2017-07-25, use for Eclipse 4.7.x and above)

On [contributing](http://dkpro.github.io/contributing/) page does not work.

**Comment by reckart** [comment]
Whoops - I forgot to commit the actual file. It is uploaded now.
