### ISSUE TITLE
Integrate CISStem German stemmer

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-core#1120]
https://github.com/LeonieWeissweiler/CISTEM

**Comment by reckart** [comment]
* Not yet added to parent POMs.
* CisStem file should have MIT license header any copyright by Leonie Weißweiler, not DKPro header
* Missing NOTICE.txt file explaining source of CisStem

**Comment by reckart** [comment]
* Should be using new-style naming conventions for packages, artifactId and groupId
