### ISSUE TITLE
Add possible to ignore named entities annotations on BinaryCasReader

### ISSUE THREAD

**Issue by lucianojs** [dkpro/dkpro-core#1149]
I need to evaluate the F-measure of my NER model generated by BinaryCAS format annotations, but it is not possible to remove NER tag annotations for comparisons. Like the readNamedEntity parameter of Conll2002Reader.

I tried converting BinaryCAS to ConNLL2002 but realized after conversion that this format does not support multiple annotations in the same token.

**Comment by reckart** [comment]
The loading processes of binary CASes does not allow for controlling what is loaded.

But you can easily remove the annotations yourself. Just create a new component:

```
import static org.apache.uima.fit.util.JCasUtil.select;

import org.apache.uima.analysis_engine.AnalysisEngineProcessException;
import org.apache.uima.fit.component.JCasAnnotator_ImplBase;
import org.apache.uima.jcas.JCas;

import de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity;

public class NamedEntityRemover
    extends JCasAnnotator_ImplBase
{
    @Override
    public void process(JCas aJCas) throws AnalysisEngineProcessException
    {
        select(aJCas, NamedEntity.class).forEach(aJCas::removeFsFromIndexes);
    }
}
```

The above code should work with UIMA 2.10.1, uimaFIT 2.3.0 and Java 8.

**Comment by reckart** [comment]
If you use the latest version of DKPro Core from this github repo, then you could also find our basic evaluation code useful. E.g. check out 

https://github.com/dkpro/dkpro-core/blob/7ecebc718c4f8238401ee6b54229fa842618a0b3/dkpro-core-opennlp-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTrainerTest.java#L56-L116

**Comment by lucianojs** [comment]
It worked perfectly, thank you.
