### ISSUE TITLE
Add reader for Leipzig Corpora Collection

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-core#1166]
This is an interesting source for corpora in a wide range of languages.

**Comment by reckart** [comment]
I think we are done here.

**Comment by betoboullosa** [comment]
Test LccReaderTest failed because it used the old parameter name.

**Comment by reckart** [comment]
Which shows that one should first let Jenkins check the code ;)

**Comment by reckart** [comment]
Thanks for fixing!

**Comment by betoboullosa** [comment]
>Which shows that one should first let Jenkins check the code ;)

Put him to work!
