### ISSUE TITLE
privacy links on git pages broken

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-core#1179]
Affects all DKPro subprojects such as https://dkpro.github.io/dkpro-core/privacy.html, https://dkpro.github.io/dkpro-tc/privacy.html, etc.

**Comment by reckart** [comment]
I guess some change in the Jekyll version used on GitHub caused the `.html` to be dropped. The pages are now under `https://dkpro.github.io/dkpro-core/privacy`... probably more things need to be fixed across all the pages...

**Comment by reckart** [comment]
Updated the following sites:

* dkpro-bigdata-website		DONE
* dkpro-c4corpus-website		DONE
* dkpro-core-website		DONE
* dkpro-csniper-website		DONE
* dkpro-github-io			DONE
* dkpro-jotl-website		DONE
* dkpro-jowkl-website		DONE
* dkpro-jweb1t-website		N/A (forwarding only)
* dkpro-jwktl-website		DONE
* dkpro-jwpl-website		DONE
* dkpro-keyphrases-website		N/A
* dkpro-lab-website		DONE
* dkpro-lsr-website		N/A (forwarding only)
* dkpro-script-website		DONE
* dkpro-similarity-website		DONE
* dkpro-statistics-website		DONE
* dkpro-tc-website			DONE	
* dkpro-toolbox-website		N/A (forwarding only)
* dkpro-uby-website		DONE
* dkpro-wsd-website		DONE
