### ISSUE TITLE
Subclassing DocumentMetaData breaks XmiReader

### ISSUE THREAD

**Issue by nilsreiter** [dkpro/dkpro-core#1195]
I have a type system with a sub type of `DocumentMetaData`, to store more specific properties about the documents. When I try to load these documents with `XmiReader`, I get an `IllegalStateException: CAS already contains DocumentMetaData`. 

Maybe it's not supported to have subtypes of DocumentMetaData, but it would be cool if they are recognized properly.

**Comment by reckart** [comment]
Which version of DKPro Core are you using?

**Comment by nilsreiter** [comment]
1.9.0

**Comment by reckart** [comment]
Right, the current code does not support subclasses of DocumentMetaData.

But you can tell XmiReader to leave your own annotation type alone by setting `PARAM_ADD_DOCUMENT_METADATA` to `false`.

Actually, the way for us to go in the future is probably to no longer have DocumentMetaData inherit from the UIMA DocumentAnnotation and instead make it a separate DKPro Core-specific document-level annotation. Inheriting from DocumentAnnotation causes all kinds of trouble.

**Comment by nilsreiter** [comment]
Ok thanks. I'll try that, but it's also good to know about the future plans.
