### ISSUE TITLE
Preposition

### ISSUE THREAD

**Issue by asher-stern** [dkpro/dkpro-core#1224]
Hi.
I guess I've missed something here, but, I've seen that new types were added to the type system for pos-tags, starting with "POS_", which replace the previous tags.
In the new pos tags (POS_ADJ, POS_ADP, etc.), I don't find a pos-tag for preposition.

Can you please help?
Thanks.

**Comment by zesch** [comment]
Hey Asher,

as far as I know, prepositions are now contained in the larger class ADP.
See also here:
http://universaldependencies.org/u/pos/all.html

And the mappings, e.g.
https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-api-lexmorph-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/en-ptb-pos.ma#

**Comment by asher-stern** [comment]
Hi Torsten.
Thanks very much.

Asher
