### ISSUE TITLE
Restore alignment data for Backmapper after a CAS restore

### ISSUE THREAD

**Issue by mjunsilo** [dkpro/dkpro-core#1244]
In cases when the CAS is persisted after the ApplyChangesAnnotator has completed, but before back mapping has occurred, then it it is not possible to resume processing from a restored CAS at this point, since all alignment data exists only at runtime in the AlignmentStorage singleton.

There are situations where it might be desirable to resume processing before back mapping, e.g. to avoid redoing some complex NLP tasks when only simpler tasks need to be reprocessed before back mapping.

**Developer discussions related to this for reference**

On Wednesday, May 30, 2018 at 11:02:36 AM UTC+2, Mario wrote:

I just found out that I cannot persist the cache before backmapping if I want to resume processing from a restored CAS before this point, since all alignment data exists only at runtime in the AlignmentStorage singleton.

I am curious whether there is a simple viable approach to get this optionally persisted with the CAS, so that I could resume processing before backmapping. I would have a go at implementing it if the solution doesn't turn out to be too complicated, i.e. it should not affect the existing logic and only introduce an optional feature to store and restore the information when the option is enabled. However, it cannot be done without introducing some additional field(s) in the type system where this information can be stored.

On Wednesday, May 30, 2018 at 1:32:53 PM UTC+2, Richard wrote:

One hacky way would be to try and make the AlignedString and its internal data-structures serializable. The ApplyChangesAnnotator and BackMapper could then be changed such that they store/read the AlignedString  from its external form. This could be stored in a file or (even more hacky) in the CAS.

The other option is to render the linked list of DataSegments which is inside the AlignedString into feature structures and to store these in the CAS in the ApplyChangesAnnotator and parse the info back from there into an AlignedString in the BackMapper.

There might be a way in between storing only a subset of the DataSegment information in the CAS - but until you figured out which subset it is, you might already have easier stored everything.
 
It has been quite a while since I last worked on that code - I think it is doable with reasonable effort if you have the motivation/need to do it.

On Wednesday, May 30, 2018 at 1:54:58 PM UTC+2, Mario wrote:

I had some similar thoughts myself. I was initially just thinking creating something that just serialized the key to AlignedString map to a field in a new feature structure type specific to ApplyChangesAnnotator and BackMapper. This would be stores with the CAS when the option is enabled during apply changes, and then restored in the BackMapper when that feature structure is present in the CAS for the view to be mapped back. The feature structure would be removed again after use.

I wouldn't go into rendering it into a more fine grained feature structure type in an initial version, and I am not sure what the benefits should be in doing so, and it would just mean more work.

I'll create an issue if you feel alright with this outline for an approach, and then we could refine the details when the initial PR is ready. I'll also include this thread in the issue description.

On Wednesday, May 30, 2018 at 2:42:53 PM UTC+2, Richard wrote:

I'm not sure what you mean by "serializing the key to the AlignedString map to a field".
This key wouldn't be useful if you want to resume processing CASes (e.g. after a crash)
because the map wouldn't be there anymore, right?

On Wednesday, May 30, 2018 at 3:08:04 PM UTC+2, Mario wrote:

I didn't look to deep into the details of this yet, and I just saw that the AlignmentStorage values for a CAS key is another map from keys that contain the ApplyChangesAnnotator source and target view name to AlignedString, so I thought I also need  to restore this map before mapping back. However, I think there might be additional details to consider, because there is possibly a whole chain that needs to be restored, so I must admit I need to spent more time understanding all the details first.

On Friday, June 8, 2018 at 9:57:29 AM UTC+2, Mario wrote:

I finally found some time to look deeper into this.

My first observation is that it appears that we only need to store a new mapping info annotation for each source to target mapping in the source view, so that it contains the source and target view names only. We can isolate the code in ApplyChangeAnnotator that constructs the AlignedString into a separate function that the BackMapper can use to reconstruct the data structure from SofaChangeAnnotations instead of serializing and deserializing it.

My second observation is that we can do this always, so that the AlignmentStorage just works as a cache for saving the reconstruction later. Reconstruction happens then only when the mapping data is not found in the cache when running through the back mapping chain. I don't think we should remove the mapping info annotation after back mapping, since this will allow the CAS to be restored at a later point and do some additional processing or reprocessing and then do the back mapping once again. In this case it requires the user to delete the previously mapped annotations unless duplicates are desired.

My third observation is that it appears that the AlignmentStorage weak hash map doesn't appear cleanly threadsafe in the context of put operations. We never observed any irregularities though, but the datastructure is as such not synchronized during insertion, and neither does the AlignmentStorage synchronize during put and get, which I suggest we do to be safe. Removal happens only during GC, so by definition I assume this part to be thread safe. I might be mistaken, but please have a look yourself and let me know what you think.

On Friday, June 8, 2018 at 11:21:38 AM UTC+2, Mario wrote:

Just an update after yet another closer inspection. We don't even need the mapping info annotation since the information is already given in the mapping chain parameter specified for backmapper, so all information is already available. I believe we just need to reconstruct the aligment state from the SofaChangeAnnotations in the original source view.

**Comment by reckart** [comment]
I had a look at the [PR](https://github.com/dkpro/dkpro-core/pull/1245). I'm pleasantly surprised that the SofaChangesAnnotations that we already had in fact seem to be sufficient to solve the entire problem. From your perspective, is it a universal solution or does it only work for special cases?

**Comment by mjunsilo** [comment]
I think it should work in most normal restore cases from my interpretation of ApplyChangesAnnotator and the Backmapper, unless one decided to delete or alter the SofaChangeAnnotations in between the calls, which could be consider a bit of an odd scenario. However, the old behaviour should still apply like previous in this case, so it's only in restore scenarios the new behaviour kicks in as a fallback, and I think it's a good a idea to narrow the initial restore use cases that needs to be supported.
