### ISSUE TITLE
how to remove ivy model downloads from runtime phase into compile phase

### ISSUE THREAD

**Issue by helt** [dkpro/dkpro-core#1265]
I use dkpro-core (1.9.2) in a project for NER detection via StanfordSegmenter or OpenNlpSegmenter, depending on the language. Currently, I am fine with the pre-computed models and do not need to train them myself. 

From the available documentation, i decided to add
```
        <dependency>
            <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
            <artifactId>de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-de-maxent</artifactId>
            <version>20120616.1</version>
        </dependency>
```
to my `pom.xml`.

However, on first start of the application, the models are downloaded into an `~/.ivy2` directory from `zoidberg.ukp...`.

Is there a way to circumvent this behavior? More precisely, how to infer the actual model that is mirrored on zoidberg, i.e. the original url for the model to download manually? 

best regards,
helt

**Comment by reckart** [comment]
It should not be necessary to manually download the packaged models. In any case, they need to be on the classpath - you couldn't simply specify a path to them in your component.
Please follow the users's guide on how to add models as dependencies to your Maven project:

https://dkpro.github.io/dkpro-core/releases/1.9.2/docs/user-guide.html#_adding_resources_as_dependencies_maven

The base URL for the model repo is `https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/list/public-model-releases-local/` - there you could browse for the artifacts and obtain raw URLs. But as I said: that should not be necessary.

**Comment by helt** [comment]
yes, that's how I did it - but the issue remains: download of the models seems to happen at application *runtime*, not during the *build phase*.

i.e. if I create a fat server jar and deploy it on, e.g. 50 machines, all models would needed to download 50 times... ON application startup.

**Comment by reckart** [comment]
Then you probably did not add all the dependencies for all the models that you need at runtime. If a model is already on the classpath, then it is not downloaded.

**Comment by reckart** [comment]
How are you creating your FAT jar?

**Comment by helt** [comment]
spring boot 2.0.1.RELEASE does that. I.e. I don't really know...

Maybe this snippet helps:
```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <fork>true</fork>
                </configuration>
            </plugin>
```

**Comment by helt** [comment]
Just to be sure that i have understood it correctly: If the build process is set up correctly, then my application wont download models and `~/.ivy2` cache folder should not contain any jars, right?

**Comment by reckart** [comment]
If DKPro Core can locate the model on the classpath, then it doesn't try to resolve it via Ivy.

The relevant code is here:

https://github.com/dkpro/dkpro-core/blob/8d2fb850516b8d5c904a1acc4c3ebb9c5f315bc1/dkpro-core-api-resources-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/api/resources/ResourceObjectProviderBase.java#L575-L597

I haven't tried this with Spring Boot so far - I think it should work though. Maybe you can start your FAT jar with remote debugging enabled, then connect your IDE to the JAR and set a breakpoint in the code mentioned above to see what is happening?

**Comment by reckart** [comment]
@helt What do you see in the logs before/when Ivy kicks in?

**Comment by helt** [comment]
@reckart Aye. Now it works flawlessly. Seems like intellij handles things differently. If starting the fat jar from command line, it works as intended. No downloads whatsoever.

Thank you

**Comment by reckart** [comment]
Odd, but great that it works now for you 👍
