### ISSUE TITLE
IxaPosTagger does not provide TypeCapability Annotation

### ISSUE THREAD

**Issue by WUUUGI** [dkpro/dkpro-core#1292]
Annotation should be:

```java
@TypeCapability(
        inputs = { 
            "de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token",
            "de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Sentence" }, 
        outputs = { 
            "de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS" })
```
This is necessary because Java does not support Annotation inheritance. 
E.g.:

```java
clazz.getAnnotation(TypeCapability.class);
```
returns `null`

**Comment by reckart** [comment]
@WUUUGI What you do is: you implement your annotation checking code such that it fetches superclasses and interfaces and checks them as well. Many frameworks (e.g. uimaFIT or Spring) do it this way. DKPro Core requires no change.
