### ISSUE TITLE
Add additional OpenNLP PoS tagging models

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#1301]
Models for languages

OpenNLP
- [ ] Afrikaans
- [ ] Urdu
- [ ] Scottish Gaelic
- [ ] Nepali
- [ ] Icelandic
- [ ] Slovak
- [ ] French

**Comment by Horsmann** [comment]
@reckart 

```
[ERROR] src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpPosTaggerTest.java:[150] (sizes) LineLength: Zeile ist 194 Zeichen lang (Obergrenze ist 100).
[ERROR] src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpPosTaggerTest.java:[154] (sizes) LineLength: Zeile ist 194 Zeichen lang (Obergrenze ist 100).
```

Can we bump up the path length? this POS_* Prefix makes the rows just quite long for the coarse-grained tags....

**Comment by reckart** [comment]
@Horsmann The commit message should be 

```
#1301 - Add additional PoS tagging models

- model declaration missing
```

not `dkpro#1301...`. Optimally every commit should have detail information as a bullet point list in addition to the title (separated by an empty line). E.g. e04af431fcf18b8056c170ce4939f7068e681674 has no detail info.

**Comment by reckart** [comment]
> Can we bump up the path length? this POS_* Prefix makes the rows just quite long for the coarse-grained tags....

Add line breaks. There is no reason why all the values need to be in a single line.

**Comment by Horsmann** [comment]
@reckart Ok, OpenNLP builds with the `use-full-resource` profile and the models are moved to the release rep; could you merge the pull request?

**Comment by reckart** [comment]
This can still be done...
