### ISSUE TITLE
desc/type/POS.xml not found in SOLR but fine outside SOLR

### ISSUE THREAD

**Issue by ggiavelli** [dkpro/dkpro-core#1348]
I think this might be related to classloader or classpath? I checked the segmentation-asl jar and the file is there. It runs fine outside of SOLR from eclipse. 

Caused by: org.apache.uima.util.InvalidXMLException: An import could not be resolved.  No file with name "desc/type/POS.xml" was found in the class path or data path. (Descriptor: jar:file:/C:/dev/solr-7.5.0/server/lib/de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl-1.10.0.jar!/desc/type/LexicalUnits.xml)

I have the jar I produce added to the schema instance lib path, configured to load in the lib, and just for grins created a system classpath and added it to that as well.

It happens when I first try to create a JCas object
   mJCas = JCasFactory.createJCas();

**Comment by reckart** [comment]
Are you using a fat JAR?

**Comment by ggiavelli** [comment]
Yes I am. I have compile with dependencies set to maven putting all the sub jars into one

**Comment by reckart** [comment]
See: https://uima.apache.org/d/uimafit-current/tools.uimafit.book.html#ugr.tools.uimafit.packaging

**Comment by ggiavelli** [comment]
thanks will try and get back on it

**Comment by ggiavelli** [comment]
Just an update. I set up the maven shade plugin and then got a security exception
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330) ~[?:1.8.0_191]

so then, I tried adding an exclude for security files and the unpacking plugin. But it might not be using it. Here is my POM

'''
  <build>
    <sourceDirectory>src/main/java</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
           <excludes>
				 <exclude>**/main/</exclude>
		 </excludes>  
        </configuration>
      </plugin>
      
       <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-shade-plugin</artifactId>
      <version>2.2</version>
      <executions>
        <execution>
          <phase>package</phase>
          <goals><goal>shade</goal></goals>
          <configuration>
            <transformers>
              
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                <mainClass>MyMainClass</mainClass>
              </transformer>
              
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>META-INF/org.apache.uima.fit/fsindexes.txt</resource>
              </transformer>
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>META-INF/org.apache.uima.fit/types.txt</resource>
              </transformer>
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>META-INF/org.apache.uima.fit/typepriorities.txt</resource>
              </transformer>
            </transformers>
            
            <outputFile>${project.build.directory}/${artifactId}-${version}-standalone.jar</outputFile>
        
          </configuration>
          
       
          
        </execution>
      </executions>
    </plugin>

     <plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <version>2.8</version>
  <executions>
    <execution>
      <id>unpack-dependencies</id>
      <phase>package</phase>
      <goals>
        <goal>unpack-dependencies</goal>
      </goals>
      <configuration>
        <excludes>META-INF/*.SF,META-INF/*.DSA,META-INF/*.RSA</excludes>
      </configuration>
    </execution>
  </executions>
</plugin>

  </plugins>    
   
  
    
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <excludes>
                <exclude>*.properties</exclude>
            </excludes>
            <filtering>false</filtering>
        </resource>
    </resources>
</build>
  '''

**Comment by reckart** [comment]
I haven't been working with signed JARs, but I doubt this works out of the box with fat JARs. Probably you'll have to tell the shade plugin to drop the signature files. I don't think telling the dependency plugin will do much.

**Comment by reckart** [comment]
Btw, if your fat JAR has no primary main class, then you should drop the `MyMainClass` section from the shade configuration.

**Comment by ggiavelli** [comment]
Thanks, I was thinking the same thing. will keep trying. will let you know if I get it.

**Comment by ggiavelli** [comment]
I did the individual jars approach and still go the same issue. So its not the combined jar, it must be some kind of classpath error. I checked and what it is looking for is there exactly where it is looking. 

No file with name "desc/type/POS.xml" was found in the class path or data path. (Descriptor: jar:file:/C:/dev/solr-7.5.0/server/lib/de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl-1.10.0.jar!/desc/type/LexicalUnits.xml)

Do I need to go down this Generate PEAR file path? Seems like a ton of work: https://uima.apache.org/doc-uima-pears.html

**Comment by reckart** [comment]
The file `desc/type/POS.xml` would be in the JAR `de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.10.0.jar` - do you have that on your classpath? Maybe it is a matter of Maven dependency scopes (i.e. compile vs test)?

**Comment by ggiavelli** [comment]
I think thats in most of the components. Its in the dependency jar as well. Its getting the error totally outside eclipse, when I stage it in SOLR. Runs fine in eclipse. thats the scooby doo mystery.

**Comment by reckart** [comment]
>  Its in the dependency jar as well

@ggiavelli The `desc/type/POS.xml` file should **only** be in `de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.10.0.jar`- what do you mean *Its in the dependency jar as well*?

**Comment by ggiavelli** [comment]
I have more testing to do but this seems to help. It's a confi for the shard maven plugin to exclude security dependencies. still have to try under solr.... but its progress not security faulting out from command>java
---
     <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-shade-plugin</artifactId>
      <version>2.2</version>
      <executions>
        <execution>
          <phase>package</phase>
          <goals><goal>shade</goal></goals>
          <configuration>
            <transformers>
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                <mainClass>MyMainClass</mainClass>
              </transformer>
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>META-INF/org.apache.uima.fit/fsindexes.txt</resource>
              </transformer>
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>META-INF/org.apache.uima.fit/types.txt</resource>
              </transformer>
              <transformer
                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>META-INF/org.apache.uima.fit/typepriorities.txt</resource>
              </transformer>
            </transformers>
             <outputFile>${project.build.directory}/${artifactId}-${version}-shade-standalone.jar</outputFile>
       
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
              </excludes>
            </filter>
          </filters>
        
          </configuration>
          
        </execution>
      </executions>
    </plugin>

**Comment by reckart** [comment]
Since there was no further communication, I assume this could be resolved.
