### ISSUE TITLE
feature-request: BratReader should not require mappings for all Brat labels

### ISSUE THREAD

**Issue by alaindesilets** [dkpro/dkpro-core#1417]
It would be very useful if BratReader was able to read .ann files that contain labels for which there is no known UIMA type mapping. These unknown labels would just get mapped to a generic type called, say, GenericLabel. Instances of GenericLabel would have a method getLabel() which would return the Brat label.

I am prepared to do this if the dev team is OK with it.

**Comment by reckart** [comment]
The `from` field in the mappings which is used to match against the brat type is treated as a regular expression. So if you build a mapping like this, I *think* it should work:

```
'textTypeMapppings': [
  {
    'from': 'known_brat_label',
    'to': 'my.company.KnownUimaType'
  },
  {
    'from': '.*', // <= match any brat label not matched before
    'to': 'my.company.GenericUimaType', 
    'subCatFeature': 'label' // <= store brat label into this feature
  }
]

**Comment by alaindesilets** [comment]
Thx Rickart.

In the above, what mappings are you referring to? Can you provide a code sample that shows how to actually activate this kind of mapping?

Thx.

**Comment by reckart** [comment]
See https://github.com/dkpro/dkpro-core/blob/1.12.x/dkpro-core-io-brat-asl/src/test/java/org/dkpro/core/io/brat/BratReaderWriterTest.java#L181

**Comment by reckart** [comment]
@alaindesilets Did it work for you?

**Comment by reckart** [comment]
I assume it worked and no further action is required.

**Comment by alaindesilets** [comment]
Yes, it worked. Thx.
