### ISSUE TITLE
I would like to know if there is anyway to include custom taggers such as flair or allennlp?

### ISSUE THREAD

**Issue by pidugusundeep** [dkpro/dkpro-core#1474]
I would like to use the NER tagger from allennlp or flair. Please let me know how to implement the same in DKpro.

**Comment by reckart** [comment]
You'd have to implement an UIMA wrapper that maps the data from the CAS to the data required for the tool in question, invokes the tool, and maps the data back to the CAS afterwards.

Examples of how to build a Java-based UIMA component communicating with Flair can be found in e.g. https://github.com/JULIELab/jcore-base .
