### ISSUE TITLE
CRFClassifier#getClassifier input stream should be buffered

### ISSUE THREAD

**Issue by StefWin** [dkpro/dkpro-core#1478]
Hi,
I've found a minor bug inside the CoreNlpNamedEntityRecognizerModelProvider when loading an CRFClassifier the InputStream is not buffered, but it should be as the jdoc states:

>  ... This method does not buffer the InputStream, so you should have buffered it before calling this method.

**Comment by reckart** [comment]
Did you try buffering it and did you observer any improvement by doing so?
