### ISSUE TITLE
Stopping DKPro From Pulling Models From Internet

### ISSUE THREAD

**Issue by ggiavelli** [dkpro/dkpro-core#1479]
Is there a way to disable CORE from pulling models from the net everytime 
Is there a maven way to get the latest models, or a parameter to stop them from changing. 

The main issue is we want stability of our release and to confirm our testing is on one codebase.

**Comment by reckart** [comment]
As long as you ensure that you have those models that you need on your classpath, you can disable the auto-download functionality by setting the system property `dkpro.model.repository.offline` to `true`.

**Comment by reckart** [comment]
Btw. you could also change the repository to an in-house repository. There are a couple of system properties for this:

```
    public static final String PROP_REPO_OFFLINE = "dkpro.model.repository.offline";
    public static final String PROP_REPO_ID = "dkpro.model.repository.id"; // Repo ID
    public static final String PROP_REPO_URL = "dkpro.model.repository.url"; // Repo URL
    public static final String PROP_REPO_CACHE = "dkpro.model.repository.cache"; // Folder where the artifacts are locally cached
```

The auto-downloaded at the moment uses Ivy (not Maven). I don't know atm if/how Ivy can be configured to deal with repos that would require authentication. Possibly the repo ID might be helpful here. So far, I only tested with repos not requiring authentication.

**Comment by ggiavelli** [comment]
thanks. very helpful. closing it.
