### ISSUE TITLE
rftagger-bin jar is no longer in maven repository

### ISSUE THREAD

**Issue by reynoldsnlp** [dkpro/dkpro-core#1517]
My project depends on the rftagger, and I just discovered that it is no longer available in maven repositories:

`
[ERROR] Failed to execute goal on project VIEW: Could not resolve dependencies for project VIEW:VIEW:war:1.0-pre1: Failed to collect dependencies at de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.rftagger-bin:jar:20130430.0: Failed to read artifact descriptor for de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.rftagger-bin:jar:20130430.0: Could not transfer artifact de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.rftagger-bin:pom:20130430.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [JWNL (http://www.anc.org/maven/thirdparty/, default, releases+snapshots), OpenNLP Repository (http://opennlp.sourceforge.net/maven2/, default, releases+snapshots), ukp-oss-model-releases (http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local, default, releases+snapshots)] -> [Help 1]
`

My [pom.xml](https://gitlab.com/view/core/-/blob/master/app/pom.xml) includes the following:

```xml
  <properties>
    <dkpro.core.version>1.8.0</dkpro.core.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
      <artifactId>de.tudarmstadt.ukp.dkpro.core.rftagger-asl</artifactId>
      <version>${dkpro.core.version}</version>
    </dependency>
    <dependency>
      <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
      <artifactId>de.tudarmstadt.ukp.dkpro.core.rftagger-bin</artifactId>
      <version>20130430.0</version>
    </dependency>
    <dependency>
      <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
      <artifactId>de.tudarmstadt.ukp.dkpro.core.rftagger-model-morph-de-tiger</artifactId>
      <version>20150928.1</version>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
        <artifactId>de.tudarmstadt.ukp.dkpro.core.rftagger-asl</artifactId>
        <version>${dkpro.core.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

Is there still a way to make this work?

**Comment by reckart** [comment]
Make sure that you use `https` in the repository URLs - I would assume that should help.
