### ISSUE TITLE
How to read a XMI doc with a typesystem

### ISSUE THREAD

**Issue by monWork** [dkpro/dkpro-core#1519]
I am trying to read a xmi doc and convert it into conll doc and i am getting error since the xmi has a custom typesystem. 
```
createReaderDescription(XmiReader.class,
                        XmiReader.PARAM_SOURCE_LOCATION, "00034-49911110997.xmi",
                        XmiReader.PARAM_TYPE_SYSTEM_FILE, "entity_typesystem.xml",
                        XmiReader.PARAM_LANGUAGE, "en"),
                createEngineDescription(Conll2006Writer.class,
                        Conll2006Writer.PARAM_TARGET_LOCATION, "."));
```
PARAM_TYPE_SYSTEM_FILE is not an attribute of Xmireader class so how do i specify my custom typesystem while reading the xmi doc

**Comment by reckart** [comment]
I can see that `PARAM_TYPE_SYSTEM_FILE` is declared in the XmiReader class in DKPro Core 2.2.0 - which version are you using?

**Comment by monWork** [comment]
I believe the documentation is pretty old but i tried to update the version to 1.10 still no success.

**Comment by monWork** [comment]
I think i have figured it out. THanks
