### ISSUE TITLE
Danish UD17 Tag Mapping Typo

### ISSUE THREAD

**Issue by Querela** [dkpro/dkpro-core#1520]
See:
https://github.com/dkpro/dkpro-core/blob/a1f3d0c557810f7eb81ed636f5ff4f2edc5d1be8/dkpro-core-api-lexmorph-asl/src/main/resources/org/dkpro/core/api/lexmorph/tagset/da-ddt-pos.map#L25-L26
I believe `N` should be `NP`.

**Comment by reckart** [comment]
I believe you are right. Would you like to submit a pull request?

**Comment by Querela** [comment]
Hm, yes, I can do so tomorrow.
I will check the docs to be 100% sure.
