### ISSUE TITLE
Change artifactId to "dkpro-core-XXX"

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#186]
For quite some time, DKPro has used OSGi-style artifact IDs. However, we never got around
to really turn our JARs into OSGI bundles. Since the artifactIds are quite long, I
think it's time to change them to a more Maven-like format:

```
dkpro-core-api-XXX-asl
dkpro-core-io-XXX-asl
dkpro-core-XXX-asl
etc.
```

- [x] rename all modules and packages that do not contain types (to maintain type name compatibility)
- [ ] ~~introduce empty proxy artifacts under the new names that depend on the artifacts using the old names, specifically for artifacts containing types~~

----

Original issue reported on code.google.com by `richard.eckart` on 2013-08-02 16:46:13

**Comment by reckart** [comment]
I am considering changing the module names to the short variants for the benefit of easier navigation on github and leaving the package names and artifact IDs as is for the moment. Does anybody have any thoughts on this?

**Comment by daxenberger** [comment]
ok from my side.

**Comment by zesch** [comment]
Ok here too
Johannes Daxenberger <notifications@github.com> schrieb am Mo., 28. Dez.
2015 um 15:06:

**Comment by reckart** [comment]
I would like to start this before 2.0.0:

* [ ] rename all modules and packages that do not contain types (to maintain type name compatibility)
* [ ] introduce empty proxy artifacts under the new names that depend on the artifacts using the old names, specifically for artifacts containing types

**Comment by Horsmann** [comment]
Wouldn't it be the cleaner way to simply rename everything and re-upload things into the artifactory under the new package name rather than introducing an additional proxy layer? 
I would say if you change from say 1.8.0 to 1.9.0 you can expect from the user that he/she updates the imports of the types that are being used?

**Comment by reckart** [comment]
The package names in an artifact should reflect the groupId/artifactId to avoid potential conflicts between multiple artifacts under different IDs containing the same classes. So I only want to move the classes to artifacts under new names when also the package names change. However, for UIMA-types, the classname is a part of the UIMA type name and changing that will break lots of things, in particular related to loading existing XMI/bincas files. Those files are what I am worried about, not the imports in Java classes.

**Comment by reckart** [comment]
Ok, so I see no objections and nobody screaming, so I'll continue with this slow migration to the new names.

**Comment by reckart** [comment]
All packages and groupId/artifactIds have been changed.

The packages for the UIMA JCas classes remain the same though!
