### ISSUE TITLE
getClasspathAsFolder

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#267]
```
de.tudarmstadt.ukp.dkpro.core.api.frequency.provider.FrequencyCountProvider.getClasspathAsFolder
extracts a model from classpath into a temporary folder which can then be used.

If the model already is on the drive it copies it to a folder anyways. This is unexpected.

It should check whether the model path already is a folder and should not ty to copy
it in this case.
```

Original issue reported on code.google.com by `nico.erbs` on 2013-10-22 14:15:28

**Comment by zesch** [comment]
Is this still relevant?
I cannot even find the method that is mentioned here.

**Comment by reckart** [comment]
Might be in ResourceUtil?

**Comment by reckart** [comment]
The method appears to be `de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceUtils.getClasspathAsFolder(String, boolean)`.

**Comment by reckart** [comment]
I had a look at the code and cannot really relate the described problem to the code. The problem description sounds like the data is repeatedly extracted from the classpath to disk, but if "cache" is set to true, this should not happen. So no idea really what the problem is/was.

@nicolaierbs: do you still remember any details?

**Comment by nicolaierbs** [comment]
That's a long time ago. I believe I wanted to use data from a file inside a jar.

**Comment by reckart** [comment]
Ok, since we have no idea anymore what exactly we wanted and a rough code inspection shows that it should be behaving as desired, I'm closing this.
