### ISSUE TITLE
Integrate Genia tagger

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#313]
```
Integrate the Genia tagger (BSD-like license).

http://www.nactem.ac.uk/tsujii/GENIA/tagger/ 

Windows binary here: http://syeedibnfaiz.blogspot.com.br/2011/07/porting-genia-pos-tagger-301-to-windows.html

So we only need to build a Linux and OS X binary :)
```

Original issue reported on code.google.com by `richard.eckart` on 2014-01-13 02:29:04

**Comment by Horsmann** [comment]
I had a look here. I noticed the following things and wonder how to deal with them appropriately

a) the tagger hard-coded loads a NER, CHUNK and POS model at start up that is expected to lie in the same folder as the binary - makes it even sense to split things up ? (into an executable and 3 model artifacts) ? From the binaries perspective you need a single fat-file with everything in it.

b) the tagger does NER, Chunk and POS always together (you can silence tokenization only as it seems) - what would be an appropriate model name? they tagger needs them all together at startup anyway why bother to call one the NER model and one the POS model?

**Comment by reckart** [comment]
There is a Java implementation of the it: https://github.com/juanmirocks/jeniatagger

I was more thinking about using that one.
