### ISSUE TITLE
PRN and AUX are reserved names on Windows

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#414]
```
DKPro Core ASL cannot be checked out on Windows 7. And here is the reason: http://stackoverflow.com/questions/22769059/unable-to-checkout-using-tortoise-svn-file-already-exists-error-for-two-file/22771580#22771580

So constituent type PRN.java should be renamed.
```

Original issue reported on code.google.com by `pedrobssantos` on 2014-07-01 21:56:01

**Comment by logological** [comment]
Would it be possible to duplicate the `PRN` class (giving the duplicate a different name such as, say, `PRNx`), update all references to `PRN` to `PRNx`, mark the original as `@deprecated`, and then delete the original `PRN` two releases from now?  This will give maintainers of other programs advance warning of the new class name and time to update their code.

A potential problem with changing the name of the class is that there are an awful lot of string references to `"PRN"` in the code. If any of these strings are dynamically mapped to class names, we'll need to handle `"PRNx"` -> `PRN` as a special case.

**Comment by reckart** [comment]
It would be nice to solve this problem as part of migrating to some universal phrase tag set (consituents) #268.

**Comment by reckart** [comment]
@pkluegl :)

**Comment by pkluegl** [comment]
This is not only PRN I think, but also AUX?

[https://en.wikipedia.org/wiki/Filename](https://en.wikipedia.org/wiki/Filename)

> In addition, in Windows and DOS utilities, some words are also reserved and cannot be used as filenames.[17] For example, DOS device files:[19]
> 
> CON, PRN, AUX, CLOCK$, NUL
> COM1, COM2, COM3, COM4
> LPT1, LPT2, LPT3, LPT4 (LPT4 only in some versions of DR-DOS)
> LST (only in 86-DOS and DOS 1.xx)
> KEYBD$, SCREEN$ (only in multitasking MS-DOS 4.0)
> $IDLE$ (only in Concurrent DOS 386, Multiuser DOS and DR DOS 5.0 and higher)
> CONFIG$ (only in MS-DOS 7.0-8.0)

**Comment by reckart** [comment]
Grmpf.... Windows....

AUX is a UD name... http://universaldependencies.org/u/pos/AUX_.html

If we change that, we loose the 1-to-1 mapping with the UD that we wanted to have as part of https://github.com/dkpro/dkpro-core/issues/76 ...

One option would be to prefix all the POS types with e.g. `UD_`...

Any suggestions/comments? @logological @pkluegl @zesch @Horsmann @judithek @carschno @dkpro/core-dev

**Comment by Horsmann** [comment]
I think it makes sense to show which standard we are using for our POS. `UD` seems to become a more or less well known abbreviation - which should make it clear that we use the `universal dependencies` 

Maybe a `suffix` instead of a `prefix` ?

**Comment by pkluegl** [comment]
I would prefer a prefix over a suffix (but my opinion should not be weighted too high as I am not an active DKPro Core user).
We use the type of annotation as prefix, not the standard, e.g., the type would be something like POSTagAux

**Comment by reckart** [comment]
@pkluegl aren't such verbose names inconvenient when writing Ruta rules?

**Comment by pkluegl** [comment]
Yes, they are :-)
This was not a proposal, just sharing alternatives.
On the other hand, same short names for different packages (as in DKPro) is also not  optimal for Ruta.

**Comment by reckart** [comment]
Well, the constituents tags need to be cleaned up anyway. I don't know if there is an overlap between UD dependencies and UD pos tags.

So just to throw a few additional naming schemes here:

* `AUX` (this is the one we want to get rid of because of conflicts)
* `UD_AUX`
* `AUX_UD`
* `POS_AUX`
* `P_AUX`
* `pAUX`
* `$AUX` ( I wouldn't be surprised if that would cause problems ;) )
* ...?

**Comment by pkluegl** [comment]
$AUX: ahhh... not good. After all problems there might be, at least Ruta won't work with this.
pAUX: I'd rather stay with the convention that types start with a upper-case letter
P_AUX: P is not a good abbreviation for pos in my opinion, not really a big advantage over POS_AUX

POS_AUX, UD_AUX, AUX_UD would be ok I think, preference in this order (descreasing).

Is the capitalization important for you?

(Just wanted to mention that Ruta can handle the same short names, but you need aliasing or something when importing the typesystem packages.)

**Comment by reckart** [comment]
Regarding capitalization: as mentioned before, we wanted to be in sync with the UD POS tags, and they are all capitalized: http://universaldependencies.org/u/pos/index.html

**Comment by pkluegl** [comment]
Ah ok, I thought they would also be identifiable if the case was changed for some chars :-D nevermind

**Comment by reckart** [comment]
Well, in principle yes - I would like to keep the extract logic going from *Windows-safe-names* to UD names as minimal as possible. Removing/adding an affix is an unambiguous substring operation. Changing the case is not necessarily unambiguous and is simple yet another operation that I'd prefer to avoid.

**Comment by judithek** [comment]
@reckart there are overlaps between the universal POS tags and the universal dependencies,
e.g.
POS: AUX, see http://universaldependencies.org/u/pos/AUX_.html (here the mouseover text says: u-pos AUX)
dependency: aux see http://universaldependencies.org/u/dep/aux_.html (the mouseover text says: u-dep aux)

another example: conj

**Comment by logological** [comment]
I think there is no all-around best solution, though if an affix is to be introduced, it's probably better to be a prefix.

**Comment by ferschke** [comment]
Moin moin,
are there plans to address this issue before 1.9.0 is released?
Just curious, because this was mentioned to me by a co-worker and I told him I'd ask.
For some reason, our dev machines are all Windows (but usually have a Linux VM on them, so we could somehow make it work).

**Comment by reckart** [comment]
@ferschke Care to contribute.

**Comment by ferschke** [comment]
I could look into this, but from the discussion it seems there are still quite a couple of decisions to be made how to do this.

**Comment by ferschke** [comment]
I could look into this, but from the discussion it seems there are still quite a couple of decisions to be made how to do this.

**Comment by reckart** [comment]
So I tend towards using POS_AUX as a schema for the type names then.

**Comment by reckart** [comment]
We have a Jenkins job now that tries compiling DKPro Core on Windows. Of course it fails, but with the new job, we have a better way to noticing these failures and fixing them.

**Comment by pkluegl** [comment]
I'll take a look at the types.

**Comment by pkluegl** [comment]
Ok, I'll have several questions.

Her's the first one: Should the tweet POS tags also get a POS prefix?

**Comment by reckart** [comment]
I guess so.

**Comment by reckart** [comment]
I suppose we'd end with prefixes for any type of POS, Dependency and Constituent subclasses like:

* POS_AUX
* DEP_AUX (which is currently called AUX0)
* CONST_PRN (or CON_PRN to if we care to stick to three-letter prefixes as not to overdo it)

**Comment by rezahay** [comment]
Dear Richard,
Is this issue regarding build-failure on windows (10)? I just tried to build 1.9 but I get the following error:

[ERROR] Failed to execute goal org.apache.uima:jcasgen-maven-plugin:2.10.0:generate (default) on project de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl: JCasGen: Input/Output exception occurred.
[ERROR] Exception: D:\Workspaces\GitRepository\dkpro-core\dkpro-core-api-lexmorph-asl\target\generated-sources\jcasgen\de\tudarmstadt\ukp\dkpro\core\api\lexmorph\type\pos\AUX.java (The system cannot find the file specified)

Regards,
Reza

**Comment by pkluegl** [comment]
@rezahay , yes this problem is covered by this issue.

**Comment by pkluegl** [comment]
I renamed the POS types now and fixed most of the tests. There are still many other test failures on my machine which could cover some missing renamings. My pull request waits for the ICLA answer.

What about the types for the syntax annotations? The correspnding artifact is building without problems since the customized (with PRN) is excluded.

**Comment by reckart** [comment]
Well... do you want to be able to do a full build on windows or not? Do you think it would be sufficient to build only the non-type modules?

**Comment by pkluegl** [comment]
... of course a full build. The thing is: I can build api.syntax-asl

There are some other modules like fs.hdfs-asl which could cause some troubles fro windows but I would not cover them here.

**Comment by reckart** [comment]
You can build api.syntax-asl because somebody back in the day already hit the problem that AUX was a reserved name on Windows and changed it to AUX0. This was a long time ago.

Then the Universal POS tags and Universal Dependencies came into existence and we had a few discussions around switching from "DKPro Core specific" coarse-grained tags to commonly accepted coarse grained tags:

* POS tags: https://github.com/dkpro/dkpro-core/issues/1088
* Constituents: https://github.com/dkpro/dkpro-core/issues/516
* Dependencies: https://github.com/dkpro/dkpro-core/issues/517

This brought back the problem that tag names clashed with Windows device names.

Then we had some discussion around how to resolve such clashes. I was in favor of doing it in a way that affects all tags equally, e.g. adding a prefix or suffix. The benefit would be that we could arrive at the proper coarse-grained tag simply by stripping the affix - and it would work in the same for all tags - no special treatment for individual tags.

Am I understanding correctly that you would be in favor of an approach that would introduce exceptions only for specific tags?

**Comment by pkluegl** [comment]
Nope, it depends on the perspective:

- Do I want to introduce new exceptions? No way
- Could I live with existing exceptions when I can build everything with windows? Probably yes
- Should the names of all these type follow the same convention (DEP and CON prefixes)? Yes
- Are  these changes hard requirements for me for 1.9.0? Not really
- Break the type system compatibility once or twice? Rather only in one release
- Will I volunteer to do the DEP and CON changes after realizing how much work POS was? Hmmm

Afterall, its about when 1.9.0 should be released and how much time is available to do the changes.

**Comment by pkluegl** [comment]
What is the status of  #1088, #516 and #517, and what is there impact on this issue?

#1088 is half way done, right? What about the other two? When we rename all syntax types, will they be removed as a next step?

**Comment by reckart** [comment]
#1088 would be kind of re-started by the present issue because most of the steps already taken in #1088 are affected. 

#517 and #516 haven't had too much attention yet. I suppose the two don't have an immediate impact on the present issue because the `api.sytnax` module appears to be building on Windows. Their relation to the present issue is that addressing #517 and #516 are also kind of introducing a "breaking" type system change. 

Btw. the present issue is introducing a "more breaking" change because we actually have to delete the POS types with the names that conflict with Windows device names. Thus, by default DKPro Core 1.9.0 would no longer be able to load XMIs annotated with 1.8.0 POS type names.

**Comment by reckart** [comment]
While looking at #1090, I noticed that the `coarseValue` of the `POS` annotation is now often (if not always) set to `POS_something`. However, the `coarseValue` should not include the `POS_` prefix. That's something that needs to be changed everywhere where the `coarseValue` is set.

**Comment by reckart** [comment]
Usually we currently use this code: 

```
                posAnno.setCoarseValue(posAnno.getClass().equals(POS.class) ? null
                        : posAnno.getType().getShortName().intern());
```

That needs to be changed to strip the `POS_` prefix.
