### ISSUE TITLE
MateTools SRL - Upload dependencies to maven central

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#536]
```
For the DKPro MateTools SRL component, upload liblinear 1.51 and the SRL 4.31 jar to
Maven Central (currently hosted on zoidberg).

Remove references for these and for the zoidberg repository from the pom.xml of MateTools
```

Original issue reported on code.google.com by `nils456` on 2014-11-25 08:58:09

**Comment by reckart** [comment]
@pedrobisp At the time, did you have a look whether the SRL 4.31 actually matches the sources in the mate-tools svn (i.e. if we can compile from SVN and get something that works)?

@betoboullosa can you have a look at building the JARs for mate-tools SRL from the sources in the mate-tools SVN and also see where to get sources for liblinear 1.51 to build the JARs for a third-party deploy to Maven Central?

**Comment by pedrobisp** [comment]
@reckart FYI, @nreimers was the one who wrapped the srl from mate-tools.
I have no idea if they match. Nevertheless, I have just checked out this source code into my workspace: https://mate-tools.googlecode.com/svn/tags/mate-tools-3.61/srl/
The project was built successfully without any issues. Then, I just removed the srl and libnear dependencies from matetools module, and manually added the project with the srl source code to the classpath of matetools module, ran the unit tests for srl and everything passed.
However, I do not see anything in their documentation stating that the jar for srl 4.31 corresponds to mate-tools 3.61...
It would be nice if someone could check this out.
There are some tools for reverse engineering on jars... Maybe that could be used...

**Comment by reckart** [comment]
@pedrobisp Afaik the JAR for SRL and the jar for anna do not overlap with each other. They use completely different package names. So as long as the labels (pos, dependency, etc.) that anna 3.5 produces are comparable to those of anna 3.3 (and I think they are because I believe the models have been trained on the same corpora), then it shouldn't matter if SRL is used in combination with 3.3 or 3.5 or with taggers, segmenters, etc. from any other DKPro Core module that provides comparable output. Would you agree?

**Comment by pedrobisp** [comment]
@reckart I am not talking about SRL using anna 3.3 or 3.5... I am talking about whether their code in their tag folder for mate-tools 3.61 in their svn repository matches the downloadable jar for SRL 4.31.

**Comment by reckart** [comment]
@pedrobisp the last change to the https://code.google.com/p/mate-tools/source/browse/#svn%2Ftrunk%2Fsrl happened on 16.12.13 13:44 and the SRL 4.31 JAR is also dated Dec 16, 2013 16:47 (can be seen when downloading the tgz file). The tgz file also conveniently includes a srl-src.jar which contains the source code. So what we should do is build a new JAR from that source code, test it with DKPro Core in place of "official" SRL 4.31 jar and then deploy our new jar to Maven Central.

**Comment by reckart** [comment]
@pedrobisp we can also compare the code in the srl-src.jar to the code in the SVN to make really sure that it is correct to put in the SVN location into the scm element in the pom. Btw - since Google Code is read only now, we don't even have to worry about the authors to make a tag in SVN - not possible and not necessary ;)
