### ISSUE TITLE
Create a WhitespaceTokenizer (or maybe a generic RegexBasedTokenizer)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#552]
```
Create a WhitespaceTokenizer (or maybe a generic RegexBasedTokenizer).
```

Original issue reported on code.google.com by `richard.eckart` on 2014-12-04 11:36:31

**Comment by carschno** [comment]
I've created a simple Whitespace tokenizer. It should be possible to generalize to a regex-based tokenizer.

**Comment by carschno** [comment]
Okay, I've replaced the WhitespaceTokenizer by a RegexTokenizer which behaves as WhitespaceTokenizer by default.
