### ISSUE TITLE
Integrate Penn Discourse Treebank (PDTB) parser

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#585]
```
PDTB parser is available under GPL here:

http://wing.comp.nus.edu.sg/~linzihen/parser/index.html

It's written in Ruby, but can be run in JRuby, thus a seamless integration in DKPro
should be expected.

Integration could be done in two steps:

1.) Type system for PDTB in ASL (e.g., de.tudarmstadt.ukp.dkpro.core.api.discourse-asl)

2.) This implementation in GPL (e.g., de.tudarmstadt.ukp.dkpro.discourse.pdtbparser)
```

Original issue reported on code.google.com by `ivan.habernal` on 2015-01-28 11:09:32

**Comment by reckart** [comment]
@habernal No plans anymore to integrate it? ;) I see that there is some code [here](https://github.com/UKPLab/emnlp2015-ih-ig/tree/master/code/dependencies/de.tudarmstadt.ukp.dkpro.core.discourse.pdtbparser/src/main/java/de/tudarmstadt/ukp/dkpro/discourse/pdtbparser) which might be a suitable basis.

**Comment by habernal** [comment]
Exactly, that's about to be integrated. The downside: problems with different tokenization and normalization are not solved, but still might be found useful by some.
