### ISSUE TITLE
Integrate FlexTag

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#611]
```
Add a flexible PoS Tagger that enables easy change of models including creating/using
self-trained ones.
```

Original issue reported on code.google.com by `Tobias.Horsmann` on 2015-04-20 15:43:17

**Comment by reckart** [comment]
I feel this module should stay out of the upcoming 1.8.0 release (#702). I don't feel comfortable about the dependency on DKPro TC - and currently it is even a SNAPSHOT dependency.

**Comment by Horsmann** [comment]
Agreed. TC 0.8 should be released first bevor we use release FlexTag.

**Comment by Horsmann** [comment]
@reckart What exactly is Jenkins trying to tell me with this dependency remark in the log file?

**Comment by reckart** [comment]
```
[WARNING] Unused declared dependencies found:
[WARNING]    org.dkpro.tc:dkpro-tc-features:jar:0.8.0:compile
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.io.text-asl:jar:1.9.0-SNAPSHOT:compile
[WARNING]    org.dkpro.lab:dkpro-lab-core:jar:0.12.0:compile
[WARNING]    org.dkpro.tc:dkpro-tc-core:jar:0.8.0:compile
```

These dependencies are declared in the POM but they are not actually used in the code. To avoid extensive clean-up actions, we configured the Jenkins build to not let modules pass that declare too many or too few dependencies.

**Comment by Horsmann** [comment]
so - I add a dependency exclusion? or how do I solve this?

**Comment by zesch** [comment]
Or you remove the unused dependencies.
Tobias Horsmann <notifications@github.com> schrieb am Mi., 6. Juli 2016 um
10:25:

**Comment by Horsmann** [comment]
The dependencies are in the flextag release. I cant just remove them

**Comment by reckart** [comment]
I assume what you want to say is that the dependencies are required by your model file. As far as I know, your model is a Maven artifact itself.

How about moving the TC dependencies from the DKPro Core module into your model's POM?

DKPro Lab shouldn't actually be required. Can this be removed?

**Comment by Horsmann** [comment]
Yes, if there are models available you probably would need those dependencies. 

I think the core dependency can be removed but I still don't understand how to react on the failing Jenkins. they are not needed at the moment or the need would come with a user-defined model. But the dependencies are part of the flextag-core/feature dependency. What do I do then?

**Comment by reckart** [comment]
If the dependencies are used in the code of the DKPro Core flextag module, then the dependency checking plugin should detect that. There are only few cases where the plugin does not correctly detect that code is actually being used. One such example is if you use only constants (e.g. final static String) from a class. If you believe that the plugin is wrongly detecting a required dependency as unused, please tell us where this dependency is used. In such a case, an override for the dependency plugin can be set up.
