### ISSUE TITLE
hunpos binaries do not work for modern linux kernels (3.x)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#619]
```
The HunPosTagger does not work if it is deployed as maven shaded-jar file.
The binary loading fails. It seems that the created temporary folder with the binary
is destroyed before the file is used.

Caused by: java.io.IOException: Cannot run program "/tmp/dkpro8956676736362431887runtime/hunpos-tag":
error=2, Datei oder Verzeichnis nicht gefunden
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at de.tudarmstadt.ukp.dkpro.core.hunpos.HunPosTagger.process(HunPosTagger.java:186)
        ... 15 more
Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 16 more

I looked into the code, but the usage of the RuntimeProvider seems to be correct (e.g.
the reference should remain valid once initialized). The problem does not occur if
run from within Eclipse, but only in jar mode.

Anyone an idea what the problem could be?
```

Original issue reported on code.google.com by `Tobias.Horsmann` on 2015-05-01 17:32:10

**Comment by reckart** [comment]
@Horsmann did you ever get around to check this?

**Comment by Horsmann** [comment]
Sorry, no I did not. 
How do I see the settings of the temporary folder? I tried the "mount" command, but I does not list any temporary folders?

**Comment by reckart** [comment]
Hm, check your fstab: http://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/

I guess if your tmp folder is not mounted as a separate file system in fstab, then noexec may not be the reason for the problem. Make sure to check on the right machine: the one where you were trying to run the standalone ;)

**Comment by Horsmann** [comment]
I am on the right machine ^^

I am not the admin on this machine, but I assume /export/data is in my case the location which also contains the temporary directory (I find nothing else that sound like a temporary directory..)
It is set to "auto" which maps to "default" which should grant "exec"

Btw, I just tested the jar on OS-X and this error does not occur.

**Comment by Horsmann** [comment]
Was the previous comment helpful to you to understand the problem.

**Comment by reckart** [comment]
The temporary directory should be "/tmp" - it should not be under "/export/data". Check your environment variables to see where your temp dir resides. I still have the feeling this is a "no_exec" problem.

**Comment by Horsmann** [comment]
The temp directory has this "ls" output: The creator should be able to do everything
lrwxr-xr-x@

**Comment by Horsmann** [comment]
I use the same machine that I use also use for other binaries that are loaded with the RuntimeProvider into temp directory where they are executed (CRFSuite for instance). If this is the cause of the problem the other binaries should share the problem?

**Comment by Horsmann** [comment]
I talked to my sysadmin of the compute server, he confirmed that the temp directory is executable. I can't tell why the CRFsuite binary works, but not this one.

**Comment by reckart** [comment]
Did you try copying the raw hunpos binary to the machine and simply try to run it on the command line?
There might be some shared-library missing. E.g. on a 64bit machine, the 32bit compatibility libraries might not be present.

**Comment by Horsmann** [comment]
I just tried both neither 64bit nor 32bit binaries are runnable on my compute server. (i.e. -bash: ./hunpos-tag: Datei oder Verzeichnis nicht gefunden)
The missing shared libraries sound promising.

**Comment by reckart** [comment]
Use "ldd" to check the libraries, e.g. `ldd ./hunpos-tag`.

**Comment by Horsmann** [comment]
hm,
"Das Programm ist nicht dynamisch gelinkt"

The binaries for linux might be just broken?

**Comment by reckart** [comment]
hm, no - then it is a static library that should no depend on any shared libraries.

**Comment by Horsmann** [comment]
Is there anyone with linux as OS that has ever run HunPos - I am all Mac, you are too, right?

**Comment by reckart** [comment]
well, the unit tests on Jenkins are on Linux.

**Comment by reckart** [comment]
Did you actually "chmod +x" the executable before trying to run it?

**Comment by Horsmann** [comment]
yes. dunno why it is not working in my case? Does Jenkins maybe use a different version of the binaries?

**Comment by reckart** [comment]
It uses the binaries from zoidberg from the Maven artifact. You can try to download the binaries from the hunpos homepage just to be sure and see if they run on your server.

https://code.google.com/p/hunpos/

**Comment by Horsmann** [comment]
I tried the one from the website. They are not working either. I have no idea what the problem could be. The md5 is the same for the website-binaries and the I have installed in the maven repository.

**Comment by reckart** [comment]
What is your kernel version "uname -a"?

**Comment by Horsmann** [comment]
3.13.0-49-generic #81-Ubuntu SMP Tue Mar 24 19:29:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by reckart** [comment]
Our Jenkins is still running a 2.6 kernel and there it works - just tested on the command line.
I just tried on a machine with a 3.2 kernel and it does not work - same as your problem.

So the ancient binary is no longer compatible with recent kernels.

**Comment by reckart** [comment]
This is what "file" has to say about it:

```
hunpos-tag: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.2.0, not stripped
```

**Comment by reckart** [comment]
I guess either you have to find a server with an older kernel - or you have to recompile the linux binary... well, we should probably produce a new binary for more modern kernels anyway.

**Comment by Horsmann** [comment]
I won't get a 2-* kernel server :)
Updating the binaries is the better choice. Especially because this is a bit hard to track.

**Comment by reckart** [comment]
I guess at some point we should add OS version sensitivity to RuntimeProvider - right now it only knows about the OS and 32/64 bit ;) Are you going to try building new binaries?

**Comment by Horsmann** [comment]
I will rebuild them under kernel 3-*
Is it necessary to update the 32 bit version too? I would just add 64bit@kernel3 if no.

**Comment by Horsmann** [comment]
I added a 64-bit kernel 3 binary, but it is packed into a jar I get null pointer exceptions on the compute server. The binary is correctly installed into the maven artifact and I can execute it on the compute server by hand. Dunno why I get nullpointer exceptions now :(

**Comment by reckart** [comment]
A Java NPE or a NPE inside the hunpos binary? Do you have a stack trace?

**Comment by Horsmann** [comment]
Exception in thread "main" org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
	at hundebug.Run.main(Run.java:29)
Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.dkpro.core.hunpos.HunPosTagger.process(HunPosTagger.java:213)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	... 8 more

**Comment by reckart** [comment]
Sounds as if the hunpos-tag binary crashes. Did you try running it on the command line after re-building it? I fear that the available models may no longer be compatible with the re-built binary.

**Comment by Horsmann** [comment]
I just rechecked the new binary with "file" and 
ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=570b86ec5978086b963b6662fe1f66cfe86ef31f, not stripped

seems to be hard-wirded to kernel 2. By recompiling it on kernel 3 the binary becomes at least executable, but the processing fails shortly after initialization 

./hunpos-tag tagger-en-wsj.model < input.txt > output.txt 
model loaded
tagger compiled
Fatal error: exception Not_found

If you set the variable 
export OCAMLRUNPARAM=b
it points to an error in 
Raised at file "pervasives.ml", line 336, characters 20-31

Btw. is your Jenkins 64bit or 32bit ? I am wondering why the 32 bit binary does not execute at all on my machine.

**Comment by reckart** [comment]
Jenkins is running on a 64 bit linux, but I tend to install the 32bit compatibility packages. Since hunpos only provides 32bit binaries on their homepage, I use them for 32 as well as 64bit machines and expect that the compatibility packages are installed. See also issue #318.

**Comment by Horsmann** [comment]
Hm, I would roll-back the change then. This seems like a "won't/can't fix" to me.

**Comment by reckart** [comment]
Let's leave this issue open - we cannot fix it right now... but maybe in the future.

**Comment by reckart** [comment]
Looks like somebody unearthed Hunpos and tries to modernize it: https://github.com/mivoq/hunpos

**Comment by ljos** [comment]
See mivoq/hunpos#22, this fixes the Not_found error.

**Comment by reckart** [comment]
@ljos nice :)

**Comment by reckart** [comment]
@ljos do you know the new hunpos maintainers? Do you think you can convince them to create a release and attach pre-built binaries for Windows/OS X/Linux?

**Comment by ljos** [comment]
I don't know them, but they contacted me earlier because I had a fork of hunpos on my account asking if I would create a fork from theirs to consolidate the different forks on github.

I will see what they do with the PR first. If they accept it I will try to talk to them about adding the binaries.

I would suggest to use the C-bindings instead of using the binary directly; at least I find that a bit more clean. It also cuts down on the time it takes to run after loading the model (though loading the model is fast).

**Comment by reckart** [comment]
@ljos do you have experience of interfacing with C-bindings from Java? PRs are certainly welcome!(mind contribution guidelines) 

I think the only native tool we use through JNI is MeCabTagger and there the developers conveniently provide a JAR with a Java API. The rest we use as external processes - when possible processes we keep running in the background (e.g. TreeTaggerPosTagger).

**Comment by ljos** [comment]
No, not in Java. If I get bored or suddenly need something like that myself I could probably implement it. I have too many other things to work on before I can do that though. I just found this issue googling for other people who have had the same problem as I had with hunpos.

**Comment by reckart** [comment]
@ljos ok, no problem. let's see who gets bored first ;) maybe @Horsmann hehe

**Comment by giuliopaci** [comment]
Hi everybody! I think more or less we are all in the same situation here: we want to use hunpos and see that some work should be done in order to make it work for our use case.
My use case was just to use it from a C application, so I tried to modernize that part. I do not think it should be too difficult to create an interface for Java of that library using swig.

However I have to warn that it seems to me that there is a memory leak somewhere in hunpos (I had no chance to investigate if it is real or just a false positive from valgrind), so probably the external process solution is still the best at the moment.

Unfortunately I am also very busy with many other stuff... So I am also in the list of the people waiting to get bored. ;-)

**Comment by Horsmann** [comment]
I am also not bored sorry :)

**Comment by ecamaj** [comment]
Any news on this?

Tried to install it in Docker: 
```
uname -a
Linux 80b328f804ac 4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017 x86_64 GNU/Linux
```
Not working, saying also that it cannot find program.

**Comment by giuliopaci** [comment]
The only news are that I was able to recompile hunpos binaries for Windows, using both MinGW-w64 and VS2015, for 32bit and 64bit.

The current building system is working on Linux only. It should be easy enough to compile a Linux version, so I suggest to compile one by yourself, as I really do not have the time to deal with Linux binary releases.
Building for Windows is much more tricky, especially with VS2015, where I ended up recompiling OCaml by myself, because of missing libraries in the precompiled OCaml distribution. With MinGW-w64 it is possible to cross-compile from Linux. I will try to upload the binaries next week.

**Comment by ecamaj** [comment]
I'm using hunpos from Dkpro-core.
I'm not sure what's happening, but when I use it locally on my Mac, it works like a charm.
I tried running it on some server with CentOS7, also working.

When I try within Docker (tried Ubuntu/Alpine/CentOS7), it is not working, always the same error "No such file or directory". You know what could be the reason?

**Comment by reckart** [comment]
@ecamaj The linux version is already quite old and not compatible with recent kernel versions. That is why you cannot run it in Docker. Somebody needs to compile a version for modern kernels.

**Comment by ecamaj** [comment]
How come it works on CentOS7 on one server I have?

**Comment by reckart** [comment]
@ecamaj Maybe they have a conservative policy for their kernels.

**Comment by reckart** [comment]
@ecamaj you could try installing IA32 compatibility libraries in your Docker images. Did you try that? I didn't check, but I would not be surprised if the hunpos binary were a 32bit binary - those don't run out-of-the-box on 64bit OSes.

**Comment by giuliopaci** [comment]
I am not a dkpro user, so I do not know where this message has its root. How are you trying to use hunpos in docker? Can you check that all necessary files are where the applications expect them? Can you share the docker image and the commandline?

In the meantime I added Windows binaries for hunpos. These have been compiled on Linux and briefly tested with wine. If anybody is willing to test them, feedbacks are welcome.

**Comment by reckart** [comment]
@giuliopaci where did you add these binaries to?

**Comment by reckart** [comment]
@giuliopaci Forget it - found it: https://github.com/mivoq/hunpos/releases/tag/v0.0.20170218

**Comment by ecamaj** [comment]
@giuliopaci Using it from dkpro core (https://dkpro.github.io/dkpro-core/).
Just put it in Docker (tried ubuntu/centos7), with java8, and it said it cannot find hunpos-tag file (generated  in /tmp/ by dkpro core)

However - I just made it work by @reckart suggestion! Bravo @reckart! :)

Installed inside docker (ubuntu) 32 bit libraries by instructions from this link 
http://stackoverflow.com/questions/23182765/how-to-install-ia32-libs-in-ubuntu-14-04-lts-trusty-tahr 
```
sudo apt-get update
sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6
```
 and it is working.

Unfortunatelly now model loading by MST parser is never finishing (hangs on this line INFO: Retrieving model) and after running another request (made AnalysisEngine object static so that model does not reloads and put everything on web server so that requests could be done on it) it is failing with NullPointerException:
```
Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.dkpro.core.mstparser.MstParser.process(MstParser.java:267)
```
I would guess that it is trying to read model which never loaded on first request, but can anyone check somehow?

**Comment by reckart** [comment]
@ecamaj I have no clue about the Croatian language but combining Hunpos with the MSTParser models seem to produce odd output. We have a unit test [here](https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-mstparser-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/mstparser/MstParserTest.java#L48). The POS tagset and the tagset encoded in the MstParser model look more-or-less similar. However, the parser produces four ROOT nodes which looks rather wrong. Actually I had to disable the tests because DKPro Core today has sanity checks that make sure that a sentence cannot have more than one dependency ROOT node... If you are familiar with Croatian, maybe you see some obvious problems in the setup? Have you had any success in combining the Croatian hunpos and MstParser models outside of DKPro Core? Btw. it might be a good idea to move this discussion from here to either the mailing list or to a new issue.

**Comment by ecamaj** [comment]
Yes, that is what my company does - NLP for Croatian language. We didn't yet spend too much time into analysis of results of MSTParser tagging, but I tried now that unit test example sentence in croatian with manually downloaded model (from its original website) and manually installed MSTparser (from it's original website) and tested it, and yes, the results are the same:

```
moramo	vrlo	kompliciran	primjer	rečenicu	,	koja	sadrži	što	više	sastojaka	i	ovisnosti	što	je	više	moguće
Vmr1p	Rgp	Agpmsn	N-msn	N-msn	Z	Pi-fsn--n-a	Vmr3s	Pi3n-a--n-nn	Sg	N-mpg	Cc	Vmn	Pi3n-n--n-nn	Vcr3s	Rgc	Agpnsn
Pred	Adv	Atr	Ap	Sb	Punc	Sb	Pred	Atr	Atr	Atr	Co	Pred	Pred	Aux	Adv	Pnom
0	3	4	5	8	8	8	1	11	11	4	10	0	0	8	17	15
```

Last two lines are result from MST parser, second line is result from hunpos.
Hunpos tagging gives good results, MST parser - bad on the first glance.

Having in mind that your Croatian example is bad Croatian in the first place, the correct sentence would be something like this:

> moramo odraditi vrlo kompliciran primjer , rečenicu koja sadrži što više sastojaka i ovisnosti , što je više moguće

Running MSTParser on that corrected sentence gives even more ROOT elements.
We analysed now what might be the problem, and it seems that this "multiple-roots problem" might be linked to the fact that model has been trained on "CONLL-X"(http://anthology.aclweb.org/W/W06/W06-2920.pdf)  tagged sentences (as stated on model source site http://nlp.ffzg.hr/resources/models/dependency-parsing/). I also checked the source data that the model has been trained on, and yes, there are multiple 0 dependencies in one sentence.
CONLL-X documents says:

> 7) HEAD: Head of the current token, which is either a value of ID, or zero (’0’) if the token links to the virtual root node of the sentence. Note that depending on the original treebank annotation, there may be multiple tokens with a HEAD value of zero.

So, it seems that the you should cover this use-case in your unit tests and potentially other parts of dkpro core.

Anyway, all this is not connected to the fact that installing IA32 libraries enabled hunpos tagging, but not MSTparser which hangs on "loading model" - could you check that?

Best,
Eduard

**Comment by reckart** [comment]
@ecamaj I used Google Translate to create the test sentence ;)

Regarding MstParser - the unit tests run. However, I run them with -Xmx5g. I would guess that your experience a hang because the JVM runs out of memory. Try giving it more memory.

**Comment by reckart** [comment]
I opened a new issue for the ROOTs problem: #1033

**Comment by ecamaj** [comment]
:) Now you have someone to ask about Croatian. 

Yup, that helped! Since I'm running my little test program through mvn exec, this helped:
`export MAVEN_OPTS=-Xmx5g`

Everything works now. 

We should work together, kicking problems together without sweat. :)

**Comment by reckart** [comment]
Thanks :)

I opened a new issue for the ROOTs problem: #1033

**Comment by Horsmann** [comment]
I pulled hunpos from Git and gave it a try on our `4.4` Linux kernel. From command line training and executing the trained model seems to work. New windows binaries are provided on the website. I can locally build linux 64bit and osx. The only binary someone else would have to build is the `linux 32 bit` version. Can we update the DKPro binaries then?

**Comment by reckart** [comment]
Do you know if the new binaries can read the old models?

**Comment by Horsmann** [comment]
No, and I would have to figure out how to static link with ocalm - you know this by any chance?

**Comment by reckart** [comment]
I'm afraid I'm not really familiar with ocaml. Maybe @giuliopaci has an idea?

**Comment by reckart** [comment]
By "no" you mean *you don't know if the existing models work* or *the existing models don't work*? It would also be a good idea to test if the models work with the different binaries for the different platforms.

**Comment by Horsmann** [comment]
I don't know if they work.

**Comment by Horsmann** [comment]
The German model from the .jar does still work so I assume the others work as well.

**Comment by Horsmann** [comment]
I just noticed that the current DKPro binaries are also non-static:

`ldd` gives me this on `hunpos-tag`:
	linux-gate.so.1 =>  (0xf77e2000)
	libm.so.6 => /lib32/libm.so.6 (0xf7789000)
	libdl.so.2 => /lib32/libdl.so.2 (0xf7784000)
	libc.so.6 => /lib32/libc.so.6 (0xf75d9000)
	/lib/ld-linux.so.2 (0x56599000)

my recompiled version has almost the same dependencies:
linux-vdso.so.1 =>  (0x00007ffc0b3ee000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f937097e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f937077a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f93703b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00005581e0adf000)

Are hose dependencies ok? By what I read this is stuff that should be there anyway? If I can use non-static binaries this would be a lot easier to prepare. I am not really sure how to hack into the build-script that I want static linked files.

**Comment by reckart** [comment]
These dependencies should be ok.

**Comment by Horsmann** [comment]
@reckart I cannot reproduce the original problem anymore. I tried running HunPos from a .jar on `1.7.0` and `1.8.0` which both works. I am on a linux `4.4.0-66-generic` kernel now and do not have a 3.x kernel accessible anymore. Might it be that the problem is limited to 3.x?
I have no means to test if the new binaries do actually fix the problem... do you still have a 3.x kernel setup to test the new binaries?

**Comment by reckart** [comment]
Our Jenkins build server is a Linux 3.2.0 and there it seems to be working as well.

**Comment by reckart** [comment]
So what should we do here?

* close the issue as *not a problem*?
* close the issue as *fixed*?
* *resolve* it for 1.9.0 - if yes, what needs to be done?
* *defer* it to 1.10.0?

**Comment by Horsmann** [comment]
I would say close it for the moment as not a problem (in many situations). The problem is still there but the circumstances in which in occurs are unknown. The problem occurs seemingly sometimes for some (older?) kernel versions.

**Comment by reckart** [comment]
Ok, well, then let's close it for the time being. If somebody stumbles over this again and cannot solve it be installing the 32-bit compatibility libraries, then we can reopen it.

**Comment by reckart** [comment]
We now have a second Debian build node where the hunpos does not run :/

* Linux frankie 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
* libc6 2.24-11+deb9u3

**Comment by reckart** [comment]
We upgraded the build node to a new kernel, but hunpos still does not run:

* `Linux frankie 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux`
* `libc6 2.24-11+deb9u3`
