### ISSUE TITLE
Lbj Tagger: Loads wrong mapping file

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#625]
```
The pos tag set Lbj uses is not entirely compatible with the default pos-mapping.

Furthermore, the pos-mapping file is hard coded and the typical parameters for providing
a different does not exist.
```

Original issue reported on code.google.com by `Tobias.Horsmann` on 2015-05-08 11:14:20

**Comment by reckart** [comment]
@Horsmann, do you plan to do something about this?

**Comment by Horsmann** [comment]
The mapping is set via the default value of the parameter. I think I changed it and forgot to close the issue?!

**Comment by reckart** [comment]
Addressed by these commits
* 6d21ae39513ca6423bb7c432329983f9b97c61d4
* 30961266f71ccf3ac926dd03a6e273cd56b75194
* 811e2ddf1100578163df15c15b215978516d005d
* e52e30281800fe62797b3cb9e946dfdbff1a3b6f
