### ISSUE TITLE
Profile for flextag module

### ISSUE THREAD

**Issue by pedrobisp** [dkpro/dkpro-core#646]
Since flextag module is still unstable, maybe we could create a profile so eclipse can ignore it when we import all dkpro-core modules into workspace.

**Comment by Horsmann** [comment]
What exactly is unstable. What I could do is remove the models from the pom.xml. I think I deleted the one anyway some time before. There shouldn't be any instabilities in the actual sense its probably the model that is not found, right?

**Comment by reckart** [comment]
I was just about to create an "experimental" profile when I noticed that flextag is already in the "deps-not-on-maven-central" profile - so flextag shouldn't be there in a normal build or Eclipse import. 

Besides that, it would be a good idea to remove the reference to the model as it no longer exists.

**Comment by reckart** [comment]
@Horsmann what is the status of the flextag module in DKPro Core? I wonder if this should be included in an upcoming release? I have the feeling it is still rather experimental...

**Comment by Horsmann** [comment]
I haven't updated the DKPro version yet. I have released some time ago `0.2.0`. I will add models in the next days too.
I would want to have it in the 1.9.0 release~

**Comment by reckart** [comment]
Will leave flextag as a normal module, not in a profile.
