### ISSUE TITLE
Token Replacement

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#650]
I'd like to have a mechanism to replace certain tokens, for instance all stopwords by the string `STOP`, or  all numbers by `0`. I envision an annotator that creates annotations holding the token offsets and the replacement value. In a futher pipeline, for instance a writer, could read the replacement value and write it instead of the original value.
Such a pipeline would modify a string such as `3 cats sat on the mat` to `0 cats sat STOP STOP mat`

Building on the two use cases (stopwords and patterns), I think there should be an abstract base class `ReplacementAnnotator_ImplBase` and (to begin with) two classes `ListBasedReplacementAnnotator` and `PatternBasedReplacementAnnotator`.
These two implementations should be parameters for passing a list of tokens (in a file) or a regular expression respectively. The `textnormalizer` module seems to be the right place.

Such an implementation seems more practical than building something on the existing blocks such as `stopwordremover` and `io.transformer`.

**Comment by reckart** [comment]
I think this is something for the normalization framework (JCasTransformerChangeBased_ImplBase). Something similar is done by the DictionaryBasedTokenTransformer, right?

**Comment by reckart** [comment]
Sorry, just re-read. So what you are asking for is basically an annotator that produces SofaChangeAnnotations but not applying them? 

Couldn't add a parameter to the JCasTransformerChangeBased_ImplBase to configure whether changes are automatically applied or whether the are simply rendered into SofaChangeAnnotations without applying them?

**Comment by carschno** [comment]
Right, but that is not flexible enough to catch for instance different regular expressions.
Perhaps it could even be more general than I thought initially: the annotator could just annotate matched tokens, e.g. the annotation would contain `{ begin = 2, end = 5, name = stop }`, `{ begin = x, end = y, name = number }` etc.
Eventually, the consumer could decide how to handle these annotation. The thing I am not sure about is when I have a typical consumer that iterates over all tokens, is it efficient to query for each token whether it is covered by such a replacement annotation? E.g.:

    for (Token token : select(jcas, Token.class) {
        List<Replace> replace = selectCovered(Replace.class, token);
        if (replace.size() > 0) {
            writer.write(replace.getName())
        } else {
           writer.write(token.getCoveredText())
        }
    }

**Comment by reckart** [comment]
Why is it not ok to apply the modifications and change the base text?

**Comment by reckart** [comment]
Why is it not ok to apply the modifications and change the base text?

**Comment by carschno** [comment]
I'll need to have another look at SofaChangeAnnotation, I suppose you are right and the necessary functionality is already included there.

**Comment by carschno** [comment]
My suggestion for a `process()`method in a regex-based transformer extending `JCasTransformerChangeBased_ImplBase` is thus:

    @Override
    public void process(JCas aInput, JCas aOutput)
        throws AnalysisEngineProcessException
    {
        select(aInput, Token.class).stream()
                .filter(token -> regexPattern.matcher(token.getCoveredText()).matches())
                .forEach(token -> replace(token.getBegin(), token.getEnd(), replacement));
    }

`regexPattern` is generated from a parameter. In the `filter()` call, all tokens are identified that match the given pattern, and in the `forEach()` call, these text passages (token) are replaced by the string set in `replacement`, also defined through a parameter.
I understand that lemmatization etc. have to be (re-)applied afterwards in the pipeline if applicable.
