### ISSUE TITLE
Developer setup: settings.xml ?

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#659]
Hi,
I need to setup a new computer to work with the DKPro core snapshots. The settings.xml that was available on the old Google Code website is unfortunately no longer reachable.

I don't find this information in the new website could someone please upload me this settings.xml?

**Comment by reckart** [comment]
Ah, this was an issue ;) Too bad I forgot adding the issue number to the commit message.

Anyway: https://dkpro.github.io/dkpro-core/pages/setup-maven.html

**Comment by muchafel** [comment]
hi, the link is unfortunately broken... Is there a new source?

**Comment by reckart** [comment]
https://dkpro.github.io/dkpro-core/pages/setup-user/

**Comment by reckart** [comment]
Or rather: https://dkpro.github.io/dkpro-core/pages/setup-maven/

**Comment by muchafel** [comment]
thanks :)
