### ISSUE TITLE
ResourceCollectionReaderBase seems to behave wrong if only empty PARAM_PATTERNS is given

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#665]
If only an empty PARAM_PATTERNS is passed to a ResourceCollectionReaderBase and no PARAM_SOURCE_LOCATION, it looks like the ResourceCollectionReaderBase simply tries to read all files under the current CWD - which is not the expected behavior. Actually, in that case simply nothing should happen.

**Comment by carschno** [comment]
Shouldn't an exception be thrown? If "nothing happens", that seems potentially very confusing to the user.

**Comment by reckart** [comment]
We could log a warning, but I think an empty list of stuff to process is not really an error.

**Comment by reckart** [comment]
Throwing an exception :)
