### ISSUE TITLE
Upgrade basic dependencies

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#667]
We have some quite outdated dependencies in DKPro Core, e.g. on several Apache Commons libraries - they could be updated to more recent versons.

**Comment by reckart** [comment]
Upgraded everything that looked like it was worth upgrading. 

I didn't upgrade dependencies on Lucene. Anybody having any thoughts on this?

**Comment by Horsmann** [comment]
I had issues in the past when using the model store/load feature of DKPro TC. I usually have to explicitly add the 4.* version of lucene-core. The one that is found by default (3-something) does not work.
Unless it causes some other harm, could we upgrade lucene-core to 4.x?

**Comment by reckart** [comment]
4.what? The current version is btw 5.4.0.

**Comment by Horsmann** [comment]
TC which uses DKPro Core 1.7.0 seems to get the version 3.0.3 by default. Unless I explicitly set `4.4.0` the model-loading is not working. When 1.8.0 will use a newer version this problem is probably no longer existent.

**Comment by reckart** [comment]
Ok, but really I think this is a problem that is not caused by DKPro Core. Apparently you are using resources in TC that have been built using Lucene 4.4.0 and apparently TC doesn't have an explicitly dependency on 4.4.0. If you rely on any library, you should explicitly declare a dependency on it and on the version that you need. You should not rely on transitive dependencies. 

Consider going through the dependencies of DKPro TC using the technique described in the DKPro Core release guide to clean up dependencies: https://dkpro.github.io/dkpro-core/pages/release-guide.html (see step 6 under "Preparation").

**Comment by reckart** [comment]
Upgraded lucene to 4.4.0.

**Comment by reckart** [comment]
Sigh... as a consequence, we now have new issue: #745

So we have two modules that need older version of Lucene:
* io.fangorn requires a Lucene 2 (third-party code has the dependency)
* decompounding requires a Lucene 3 (our code has the dependency, can be upgraded, #745)
