### ISSUE TITLE
Port to Ant 1.9.4 or major 

### ISSUE THREAD

**Issue by puntogil** [dkpro/dkpro-core#671]
Hi
any plan to port dkpro-core to Ant 1.9.4 or major ?
thanks in advace
I use 1.9.4, this is the error during the build
dkpro-core-de.tudarmstadt.ukp.dkpro.core-asl-1.7.0/de.tudarmstadt.ukp.dkpro.core.api.io-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/api/io/FileSetCollectionReaderBase.java:[189,35] incompatible types: org.apache.tools.ant.types.resources.FileResourceIterator cannot be converted to java.util.Iterator<org.apache.tools.ant.types.resources.FileResource>

**Comment by reckart** [comment]
Can you provide a stack trace?

**Comment by puntogil** [comment]
no, sorry
regards

**Comment by reckart** [comment]
We are using ant 1.10.x now.
