### ISSUE TITLE
Add general purpose metadata annotation

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#672]
(We discussed this a long time ago off-line)
Add a general purpose metadata annotation with flexibly named key-value pairs (both encoded as Strings). The idea is to carry document-wide meta-information in the form of an annotation, for instance, publisher, publication date, etc.; whatever suitable for the data.

This is implemented in an annotation `MetadataStringField` annotation with two fields:
* key
* value

I suggest to add it to the module api.metadata-asl.

**Comment by reckart** [comment]
I'm thinking of adding methods to the DocumentMetaData class to manage such fields, e.g.

    String DocumentMetaData.setField(String key, String value)
    void DocumentMetaData.getField(String key, String value)
    Map<String, Object> DocumentMetaData.getFieldsAsMap()
    ...

We could also add support for multi-valued fields (Arrays) and non-String fields, i.e. primitive types (boolean, int, etc).

WDTY?

**Comment by carschno** [comment]
I was also thinking about generalizing the field types in particular for the value. However, there is no general Object CAS type, so I am not sure how to implement this other than individually for each value type (e.g. `MetaDataDoubleField` etc.).

Your suggestion seems to make this easier by implementing suitable methods such as `DocumentMetaData.setField(String key, Double value)` etc. Also, the Map implementation seems very handy.
I'll have to look into the `DocumentMetaData` implementation first though.

**Comment by carschno** [comment]
Closing the issue for now; I think additional changes could be implemented through a new issue.
