### ISSUE TITLE
Writer for one sentence per line, tokens separated by whitespace

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#673]
Many external tools that cannot easily be implemented as DKPro components (e.g. [word2vec] (https://code.google.com/p/word2vec/)) require an input format in the form of one sentence per line and tokens separated by whitespace. I propose a writer component that outputs text in such a format according to previously performed segmentation.

Additional options should be available, such as writing lemmas instead of original tokens, replacing tokens by placeholders, e.g. stopwords by `STOP`, numbers by `NUM` etc.

I think this should be located in the io.text-asl module and implement a class `TokenWriter`. `LemmaWriter` might be an additional module, or lemmas could be activated through a parameters.

- [x] Basic functionality: Iterate over sentences and tokens and write to target file, separated by newlines and whitespaces respectively.
- [x] Replace stopwords with `STOP` by passing a stopwords file through a parameter
- [x] Replace numbers (or, more generally, any regex) with `NUM` or another placeholder value
- [x] Output lemmas instead of tokens
- [x] Output any other annotation type (e.g. named entities etc.)#
- [ ] Create asciidoc

I suggest there should be an abstract class which defines the common parameters and methods, and classes that implement the token/lemma/NEs extraction.

**Comment by reckart** [comment]
Why not make the type/feature to be written a parameter entirely? E.g.

```
// Write token text
createEngineDescription(XXXWriter.class,
  XXXWriter.PARAM_FEATURE_PATH, Token.class.getName()"/text()");

// Write Lemma value
createEngineDescription(XXXWriter.class,
  XXXWriter.PARAM_FEATURE_PATH, Lemma.class.getName()"/value");
```

**Comment by carschno** [comment]
Mh because I was not aware of the possibility of append the required extension (`/text`, `/value`) to the class name. How can I then extract the token/lemma text? Let's assume a variable

`String featurePath = Lemma.class.getName()+"/value"`,

will `select(aJCas, featurePath)` work?

**Comment by reckart** [comment]
We do not have a `select(aJCas, path)` method in uimaFIT (yet) - but we have one of these in FeaturePathFactory in DKPro Core (api.featurepath).

**Comment by carschno** [comment]
Okay, looks good. I assume the default value for `PARAM_FEATURE_PATH` should thus point to `Token.class.getName()+"/value"` and allow using any other feature path instead.

**Comment by reckart** [comment]
`Token.class.getName()+"/text()"` (there is no "value" on Token).

**Comment by carschno** [comment]
This is becoming a bit involved as I want to enter a newline after each sentence, but we don't have a `selectCovered()` method in api.featurepath. My initial idea looked like this:

    BufferedWriter writer = ...
    for (Sentence sentence : select(aJCas, Sentence.class)) {
      for (Token token : selectCovered(Token.class, sentence)) {
        writer.write(token.getCoveredText() + " ");
      }
      writer.newLine();
    }
    writer.close();

However, this does not seem easily generalizable.

**Comment by reckart** [comment]
I think it should work more or less like this now (post #674):

```
        String aPath = Token.class.getName()+"/text()";
        
        JCas jcas = JCasFactory.createJCas();

        // Separate Typename and featurepath
        String[] segments = aPath.split("/", 2);
        String typeName = segments[0];

        Type t = jcas.getTypeSystem().getType(typeName);
        if (t == null) {
            throw new IllegalStateException("Type [" + typeName + "] not found in type system");
        }

        FeaturePathInfo fp = new FeaturePathInfo();
        fp.initialize(segments.length > 1 ? segments[1] : "");

        for (Sentence sentence : JCasUtil.select(jcas, Sentence.class)) {
            Iterator<String> i = new FeaturePathIterator(CasUtil.selectCovered(jcas.getCas(), t, sentence).iterator(), fp);
            while (i.hasNext()) {
                System.out.println(i.next());
            }
        }
```

**Comment by carschno** [comment]
A few new issues have come up now, sorry. `new FeaturePathIteration()` returns an iterator of type `Iterator<Entry<T, String>>` (not `Iterator<String>`) where `T` is of type  `AnnotationFS` in our case. I've used the value of each entry to get the output; in the example of `...Lemma/value`, this works fine. For `...Token/text`, it the value is `null', however, and thus throws a NullPointerException. I've tried to replace `/text` with `/text()` and other variations, but it remains null.
Is there any documentation about feature paths available anywhere?
The actual token text is retrievable via `entry.getKey().getCoveredText()`, but this does not seem to take the feature path into account for other cases. Here's the relevant code:

        String[] segments = featurePath.split("/", 2);
        String typeName = segments[0];

        Type t = aJCas.getTypeSystem().getType(typeName);
        if (t == null) {
            throw new IllegalStateException("Type [" + typeName + "] not found in type system");
        }

        FeaturePathInfo fp = new FeaturePathInfo();
        try {
            fp.initialize(segments.length > 1 ? segments[1] : "");
        }
        catch (FeaturePathException e) {
            throw new AnalysisEngineProcessException(e);
        }
        for (Sentence sentence : select(aJCas, Sentence.class)) {
            Iterator<AnnotationFS> annotationIter = selectCovered(aJCas.getCas(), t, sentence)
                    .iterator();
            FeaturePathIterator<AnnotationFS> valueIter = new FeaturePathIterator<>(annotationIter,
                    fp);

                /* write single annotations (tokens, lemmas, ...) */
                boolean isFirst = true;
                while (valueIter.hasNext()) {
                    Entry<AnnotationFS, String> anno = valueIter.next();
                    String text = anno.getValue();
                    targetWriter.write(text);
                }
        }
    }

**Comment by reckart** [comment]
The documentation is in the JavaDoc of the FeaturePath interface: http://uima.apache.org/d/uimaj-current/apidocs/index.html?org/apache/uima/cas/FeaturePath.html

It says there that `coveredText()` should be used (not `text()` as I had remembered).
