### ISSUE TITLE
Implement unit tests for TokenizedTextWriter that do not depend on other modules

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#675]
The previous unit tests for `TokenizedTextWriter` (#673) in the io.text module depend on other modules (tokit, morpha) to generate annotations (Tokens, Lemmas). However, adding the tokit dependency results in a cyclic dependency. The workaround has been to comment out all unit tests to the `TokenizedTextWriter`, hence the class currently does not have any unit tests.

**Comment by reckart** [comment]
You can use the uimaFIT TokenBuilder. Cf. AnnotationByLengthFilterTest or other tests in DKPro Core.

**Comment by carschno** [comment]
I figured I can actually use `TestRunner.runTest()` when flushing the writer at the end of the `process()` method (which is probably not a bad idea anyway). Whitespace-based tokenization can hence be done there.
The only thing still missing is a test for annotations other than tokens (such as lemmas); I suppose that is not doable, neither with `runTest()` nor with `TokenBuilder`.
