### ISSUE TITLE
PosFilter log excess

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#677]
PosFilter tends to flood the console (or whatever logging output) with warnings about missing annotations when any of the removed annotations (Stem, Lemma, POS) is not available (in `getAnnotation()`). This is not a rare case and for each token, each missing annotation emits a warning. These logs should be set to debug level.

- [x] change log level from warning to debug in `getAnnotation()`

**Comment by reckart** [comment]
+1 ;)
