### ISSUE TITLE
uima annotation viewer with dkpro-annotated xmis?

### ISSUE THREAD

**Issue by helt** [dkpro/dkpro-core#682]
Is there a way to get the uima annotation viewer to work with dkpro-annotated xmis? i.e. is there a comprehensive type system descriptor available which covers all of the typedescriptors that dkpro-core provides?
I have searched the core repo and found many typedescriptors scattered all over repo but no comprehensive “parent” descriptor which includes all the annotations in one file (as imports).

Any ideas?

**Comment by reckart** [comment]
When you use the DKPro Core XmiWriter, it should write out a type system XML file with the required types along with the XMIs. There is no comprehensive type descriptor. You could generate one by creating a Maven module that depends on all DKPro Core modules, then use the uimaFIT TypeSystemDescriptionFactory.createTypeSystem() to scan all descriptors into a large one and then write that out to a file.

**Comment by helt** [comment]
see #683
