### ISSUE TITLE
Remove examples module

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#688]
The examples in the examples modules have been copied to the new dkpro-core-examples project. Hence, the modules can be deleted.

* [x] Remove examples-asl
* [x] Remove examples-gpl

**Comment by Horsmann** [comment]
Hi,
I took a look into the `https://github.com/dkpro/dkpro-core-examples` project and checked it out. At the moment the test class ´NameAnnotationPipeline´ is unknown in the test case.

The module in DKPro Core is failing at the moment, too. 
https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Core%20(GitHub)/de.tudarmstadt.ukp.dkpro.core$de.tudarmstadt.ukp.dkpro.core.examples-asl/1286/testReport/de.tudarmstadt.ukp.dkpro.core.examples.example1/NameAnnotationPipelineTest/test/

Seems like something broke :)

**Comment by carschno** [comment]
Hm that test actually failed on my local machine as well due to some changes in the order of the output. I assume the order is arbitrary to some extent and hence the test is hardly useful as is. I suggest to remove the examples-asl module anyway and see how to deal with it in the examples project.

Regarding the issue in dkpro-core-examples, I'll look into it separately. Would you mind opening a separate issue in that project and post the details?

**Comment by Horsmann** [comment]
Is there an examples-gpl project? I see it is referenced by the -gpl pom.xml, but I don't find such a project folder in my workspace

**Comment by carschno** [comment]
There is: https://github.com/dkpro/dkpro-core/tree/bf90b7952c6efb3945a23ad21c04c57465839cb1/de.tudarmstadt.ukp.dkpro.core.examples-gpl
