### ISSUE TITLE
PTB Mapping file: "(" and ")" are other, not punctuation?

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#690]
Hi,

I just noticed in the PTB part-of-speech mapping file that open/closing round brackets are mapped to the coarse-type OTHER. I would have expected PUNC.  

First, the explicit mapping is obsolete since O is the default tag. Second, are there any reasons for treating brackets as O, or are they just wrongly assigned. Third, what about ´{}[]´ they should be imo also mapped to PUNC. Anyone an opinion on that otherwise I would add all brackets and map them to the PUNC coarse-type.

```
(=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.O
# contextual separator, right paren
)=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.O
```

**Comment by zesch** [comment]
This looks like a mistake to me. It should be PUNC.

About ´{}[]´ - are these really tags in PTB or are they also mapped to "()"?

**Comment by Horsmann** [comment]
Oh right, they are probably not in the PTB.

Then I would change the brackets to PUNC.

**Comment by Horsmann** [comment]
I updated all 3 English mappings

**Comment by reckart** [comment]
According the the universal POS tags mapping (which we should follow), all the parentheses should be mapped to PUNC. Cf. e.g. https://github.com/slavpetrov/universal-pos-tags/blob/master/en-ptb.map

**Comment by Horsmann** [comment]
@zesch @reckart Seemingly all parser-tests are failing after I added a mapping for the `#` POS-tag.

For instance the `BerkeleyParserTest`

I am not entirely sure what this tests for "unmapped tags" tries to do here, but the expected output seems to be wrong.

Before I naively set expected=actual, can someone take a look into the parser test and tell me if mapping 
`#-> PUNC` caused any harm here?

```
Unmapped tags        - Expected: "#", "$", "''", "-LRB-", "-RRB-", "``"
Unmapped tags        - Actual  : "$", "''", "-LRB-", "-RRB-", "``"
```

**Comment by reckart** [comment]
The tagset tests are pretty tight. This particular check tests which tags produced by a tool are not covered by a specific mapping file. So if you add any mapping to a mapping file, "unmapped tags" need to be updated in the tests.
