### ISSUE TITLE
Add Bintray as a repository to DKPro Core

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#694]
We have the policy of only releasing code that relies on dependencies which are on Maven Central - following a policy of Maven Central itself. Also, we have put considerable effort in the past in preparing third-party uploads to Maven Central. However, the world is turning and there is a second reliable repository service now: JCenter at Bintray hosted by JFrog, the company behind Artifactory.

Given that some dependencies may today be on Bintray JCenter but **not** on Maven Central and given that Bintray is backed by a strong commercial sponsor, I think we can assert that Bintray JCenter is a suitably reliable source.

I would propose we add Bintray JCenter as an additional repository to the DKPro Core master POM such that we can use dependencies from there. We should then observe how well this works for us and our users.

Right now, I would like to add a component for the DFKI JTok tokenizer to DKPro Core and JTok is available via Bintray.

**Comment by logological** [comment]
What happens if both repositories contain the same artifact?  Is this likely to cause any problems or do conflicts get resolved automatically?

**Comment by reckart** [comment]
Actually, JCenter mirrors Maven Central, so likely all artifacts will be duplicated there.

By convention, an artifact with a given combination of groupId, artifactIf, version, and classifier (GAVC) should be the same in all repositories. Maven repositories habitually partially mirror each other.

Anyway, this is one of the things we will have to see whether it causes problems, e.g. because somebody intentionally or accidentally uses a GAVC coordinate that they are not supposed to be using.

**Comment by zesch** [comment]
+1 for adding Bintray deploys

**Comment by reckart** [comment]
@jbaruch Since I didn't find an issue tracker for JCenter/Bintray, I'm trying to ping you this way: We've recently added Bintray as a source for artifacts in DKPro Core, but apparently there are some artifacts not properly mirrored from Maven Central:

The Stanford CoreNLP models JAR appears to be broken on JCenter:

https://bintray.com/bintray/jcenter/edu.stanford.nlp%3Astanford-corenlp/3.5.2/view#files/edu/stanford/nlp/stanford-corenlp/3.5.2

-> stanford-corenlp-3.5.2-models.jar 8 months ago 3 MB

http://search.maven.org/#artifactdetails%7Cedu.stanford.nlp%7Cstanford-corenlp%7C3.5.2%7Cjar

-> stanford-corenlp-3.5.2-models.jar 04-May-2015 321.7 M

If there is a better way to report such problems, please tell us.

**Comment by reckart** [comment]
I opened a ticked about the broken models JAR with Bintray support via the "Contact" link on Bintray.

**Comment by reckart** [comment]
Response from Bintray support:

> Thank you for bringing this to our attention.
We observed that the stanford-corenlp-3.5.2-models.jar file was indeed corrupted.
Therefore, we have removed the broken file and uploaded the complete (321.7MB) file to Bintray.
