### ISSUE TITLE
PennTreeToJCasConverter does not set the POS for Tokens

### ISSUE THREAD

**Issue by mjlaali** [dkpro/dkpro-core#697]
when calling PennTreeToJCasConverter#convertPennTree(Sentence aSentence, PennTreeNode aNode) , pos of all tokens are null

**Comment by reckart** [comment]
@mjlaali do you wish to provide an updated pull request for this issue? Please keep changes minimal.

**Comment by mjlaali** [comment]
@reckart when I start working with the de.tudarmstadt.ukp.dkpro.core.io.penntree-asl, I found out there are few more problems, namely: 
1- Some time pos tags are not set for tokens.
2- Some time the parent of tokens are not set.
3- Some time the parent of constituents are not set
4- There are two methods that need to be fixed 
         a) PennTreeToJCasConverter#convertPennTree(Sentence aSentence, PennTreeNode aNode
         b) PennTreeToJCasConverter#convertPennTree(Sentence aSentence, PennTreeNode aNode)
This is why you find some extra codes in my branch. I noticed some of these issues are still in the master branch. Do you want me to create a new issue in github for the remaining problems and submit my patch?

**Comment by reckart** [comment]
Sure, that would be great! Please make sure that the changes are minimal (no unnecessary changes in formatting, no unnecessary introductions of new methods, etc.) and clearly correlate to the description of the pull request to ensure that reviewing and merging the PR is straightforward.
