### ISSUE TITLE
Update Treetagger build.xml md5 hashes

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#701]
* [x] update hashes in build.xml file - make sure to use the correct date (`curl -I` - Last modified) and also to update the comments before each section
* [x] update managed dependencies on these models in the pom of the treetagger module
* ~~update the models overview table on google drive~~ (no longer necessary as the Google table will be replaced by the auto-generated documentation with 1.8.0)
* [x] check if the unit tests still work with the new models (e.g. by adding them manually to the build path of the project in Eclipse or by deploying them to a **private** repository and letting Maven get them from there

**Comment by reckart** [comment]
When the MD5 values are changed, the versions need to be updated, the dates of the artifacts need to be updated, the comments in front of the model sections need to be updated.

**Comment by reckart** [comment]
Unforunately, the dates are not correct. E.g. you put "20151204" for "english-par-linux-3.2-utf8.bin.gz", but the last modification date on the server is "20151119":

```
$ curl -I http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english-par-linux-3.2-utf8.bin.gz
HTTP/1.1 200 OK
Date: Fri, 04 Dec 2015 14:42:13 GMT
Server: Apache/2.4.10 (Linux/SUSE)
Last-Modified: Thu, 19 Nov 2015 10:24:39 GMT <<< THIS IS THE RELEVANT DATE
ETag: "332298-524e22aa15dd8"
Accept-Ranges: bytes
Content-Length: 3351192
Content-Type: application/x-gzip
```

**Comment by reckart** [comment]
I put in additional steps necessary to properly resolve this into the initial issue description as a checklist.

**Comment by Horsmann** [comment]
Urhg, I roll it back. Didn't know that it such an effort to update the script.

**Comment by reckart** [comment]
lol. No need to roll back :) It's good to upgrade the hashes. If you don't want to do the other necessary steps, somebody else will have to do that, but we should not close the issue before they have been completed.
