### ISSUE TITLE
Support for LAPPS LIF format

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#712]
Support for LAPPS LIF format
- [X] Sentence 
- [X] Token
- [X] Lemma
- [X] Paragraph 
- [X] NamedEntity (no mapping support yet)
- [X] POS (no mapping support yet)
- [X] Dependency (no mapping support yet)
- [X] Constituent (no mapping support yet)

See also:
- http://vocab.lappsgrid.org
- Issue #1055

**Comment by reckart** [comment]
@ksuderman First throw for LAPPS LIF support is now in the repo (reading and writing).

**Comment by reckart** [comment]
Opened issue for being unable to properly set "dependencies" feature in DependencyStructure: https://github.com/lapps/org.lappsgrid.serialization/issues/11

No merging this into 1.8.x branch because the dependencies are not on Maven Central yet: https://github.com/lapps/org.lappsgrid.serialization/issues/2

**Comment by ksuderman** [comment]
The issues above have been addressed and org.lappsgrid.serialization is now available on Maven Central.

**Comment by reckart** [comment]
@ksuderman thanks! I'm also using the vocabulary artifact for the constants which is unfortunately not yet available on Maven Central. Are you planning to publish it there as well?

```
        <dependency>
            <groupId>org.lappsgrid</groupId>
            <artifactId>vocabulary</artifactId>
            <version>2.1.1</version>
        </dependency> 
```

**Comment by ksuderman** [comment]
Yes, I should have that available later today.  I will post back when it is online.

**Comment by ksuderman** [comment]
I just pushed the 2.2.0 release of org.lappsgrid.vocabulary to Maven Central.  It should be available shortly.
