### ISSUE TITLE
Harmonize names for Morphological Analyzers

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#716]
We typically try to stick to a common naming scheme for annotators, e.g. XXXPosTagger for part-of-speech taggers.

We do not have such a scheme for morphological analyzers:
- SfstAnnotator
- MateMorphTagger
- RfTagger

The suffix "MorphologicalAnalyzer" is pretty long, right? What would be a good suffix?

**Comment by zesch** [comment]
Morphalizer? :)

Some Sfst models and the RfTagger also output POS tags, so we will name things by the "highest" level of annotation they produce?

**Comment by reckart** [comment]
> Some Sfst models and the RfTagger also output POS tags, so we will name things by the "highest" level of annotation they produce?

Kind of... we have multiple components that produce multiple outputs. So far:

* PosTagger beats Lemmatizer (e.g. TreeTaggerPosTagger)
* Parser beats PosTagger (anyway, we don't have parsers produce POS tags by default)
* "Morphalizer" beats PosTagger
* ... there might be more ...

One could argue that Lemmas depend on POSes and thus they would be "higher", but I don't feel we should rename the TreeTaggerPosTagger component ;)

**Comment by reckart** [comment]
I noticed that some POS-tagger models that we have are pretty rich and contain lots of morphological information. So actually we don't really have a clear separation between POS-taggers and morphological analyzers...

**Comment by reckart** [comment]
We have quite rich metadata on the components these days, so I think we can resort to this metadata and don't need to stick so strictly to a naming convention anymore. 

Closing this one.
