### ISSUE TITLE
Harmonize names for Named Entity Recognizers

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#717]
We typically try to stick to a common naming scheme for annotators, e.g. XXXPosTagger for part-of-speech taggers.

We do not have such a scheme for morphological analyzers:

* StanfordNamedEntityRecognizer
* LingPipeNamedEntityRecognizer
* OpenNlpNameFinder

The suffix "NamedEntityRecognizer" may be a bit longish? Should we switch to "NER"? Or at least rename the OpenNlpNameFinder to OpenNlpNamedEntityRecognizer?

**Comment by Horsmann** [comment]
I would rename the OpenNLP component. As attrictive abbreviated names are they require that you know what the abbreviation means. 
A name that gives a clear idea about what the component does is of higher worth here (imho)

**Comment by betoboullosa** [comment]
Agree with @Horsmann

**Comment by reckart** [comment]
Also rename the CogrooNameFinder...
