### ISSUE TITLE
Add missing capability annotations (1.8.0)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#724]
Add missing capability annotations. Well, there appear still to be missing several despite having addressed this issue already two times in the past. Maybe it is time to set up some sanity tests, e.g. automatically looking at the imports for UIMA types and requiring that imported types are declared either as input or output capabilities.

**Comment by carschno** [comment]
What exactly are these annotations supposed to look like? Should every component have that? Is there a documentation which defines the details? I couldn't find any; perhaps we should generally start working on a developer's guide?

**Comment by reckart** [comment]
We have a basic developers guide for quite a while, although many things are not covered in there yet:

https://dkpro.github.io/dkpro-core/documentation/ (1.8.0-SNAPSHOT section)

I have added a skeleton section on component implementation and mentioned the capabilities there.

**Comment by reckart** [comment]
@carschno I hope the documentation proves useful and grows, but I believe the main problem is forgetting to add the capabilities or not updating them when refactoring. And we still have some very old components that were never fitted with capabilities. That is why I was suggesting an automatic check - at least as a rough guideline.

**Comment by reckart** [comment]
Added various. If we find more for 1.8.0, reopen, otherwise new issue for next release.
