### ISSUE TITLE
request: clojure integration

### ISSUE THREAD

**Issue by holtzermann17** [dkpro/dkpro-core#754]
Hi, you have Groovy, and Jython... why not Zoidberg?  I mean, why not Clojure :tongue:

**Comment by reckart** [comment]
@jimpli set up a UIMA / uimaFIT / clojure tutorial some years back and we had given advice here. But in the DKPro Core team, we don't have immediate clojure expertise. If you are interested: https://github.com/jimpil/clojuima

**Comment by reckart** [comment]
If anybody feels like contributing this, please check out our contribution guidelines and get back to us. Meanwhile, as I don't see anybody working on this, closing.
