### ISSUE TITLE
Use "universal" categories for part-of-speech tags (1.9.0)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#76]
A set of universal POS tags very similar to the existing DKPro Core POS tags has been presented at LREC recently:

http://universaldependencies.org/u/pos/

It has been discussed that these will be adopted for DKPro Core. Only a few changes need to be made:

```
                    DKPro
Universal   DKPro (old) UD (new)    Change      Description
---------------------------------------------------------------------
ADJ         ADJ         ADJ         no          adjective
ADP         PP          ADP         rename      adposition
ADV         ADV         ADV         no          adverb
-           -           AUX         new         auxiliary verb
CONJ        CONJ        CONJ        no          conjunction
DET         ART         DET         rename      determiner
-           -           INTJ        new         interjection
NOUN        NN, N       NOUN        merge       noun
NUM         CARD        NUM         rename      numerals
PRT         PRT         PART        new         particle
PRON        PR          PRON        merge       pronoun
-           NP          PROPN       rename      proper noun
.           PUNC        PUNCT       rename      punctuation
-           -           SCONJ       new         subordinating conjunction
-           -           SYM         new         symbol
VERB        V           VERB        rename      verbs
X           O           X           rename      other
```

**NOTE:** The universal POS tags from the universal dependencies project (http://universaldependencies.org/u/pos/) may be more suitable today than the ones from the universal POS tags project (https://github.com/slavpetrov/universal-pos-tags).

_Original issue reported on code.google.com by `richard.eckart` on 2012-06-27 20:02:04_
- [X] Add new types
- [X] Deprecate old types
- [X] Update unit tests
- [X] Add unit test checking that mappings do not use deprecated types
- [X] Update mappings to use the new names for types we **already had** before
- (deferred) Update mappings to make use of the new type that we **did not have** before
- [x] Update documentation for types we **already had** before
- (deferred) Remove deprecated types (2.0.0)

Tasks marked as deferred have been moved to #1088.

**Comment by reckart** [comment]
I think we can migrate to these pre-2.0.0. The reason this issue is scheduled for 2.0.0 is because it includes deleting/renaming types which can cause problems loading serialized files.

However, if we just create new types that are missing, deprecate some of the old types and not use them anymore, we could still read old files - although they might not be correctly interpreted anymore. Also, we would not run into compile errors, but code that would rely on the old types would not correctly behave anymore.

What do you think about doing the switch, updating the mapping files, etc. and marking the old types as deprecated, but not deleting them (same btw. for #516 'universal constituents' #517 'universal dependencies')?

**Comment by Horsmann** [comment]
I would like to have the universal dependencies earlier. Marking as deprecated is fine with me, too.

**Comment by daxenberger** [comment]
Same here. Prefer to have them early.
