### ISSUE TITLE
Add a new reader for TüBA-D/Z chunk format

### ISSUE THREAD

**Issue by betoboullosa** [dkpro/dkpro-core#761]
The TüBA-D/Z corpus chunked version is based on Conll2000 chunk format (http://www.sfs.uni-tuebingen.de/fileadmin/user_upload/ascl/tuebadz-10.0-README.pdf), but with some differences: it has header lines for every sentence, it's tab separated instead of space-separated, and the chunk BIO tag can be compound with additional named entity

**Comment by reckart** [comment]
@betoboullosa is there anything left to do here?
