### ISSUE TITLE
Adapt Conll2002 reader to GermEval format

### ISSUE THREAD

**Issue by betoboullosa** [dkpro/dkpro-core#762]
The GermEval 2014 format for NER data is slightly different from the original Conll2002 format. Besides of using tab instead of spaces to separate columns, it has an additional fourth column used for embedded named entities.

**Comment by reckart** [comment]
What's still left to do here?

**Comment by maxxkia** [comment]
Nothing, I guess. I already used it in a pipeline and it is working properly.
@betoboullosa, I will close this.
