### ISSUE TITLE
FrequencyDistribution: loading from file does not set max-values

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#764]
`de.tudarmstadt.ukp.dkpro.core.api.frequency.util.FrequencyDistribution` offers a `load(File file)` method to load a FD from a file.
Loading from file does not set the values for the most frequent sample and its frequency.

**Comment by Horsmann** [comment]
@reckart how do I merge this change into the 1.8.0 branch?

**Comment by betoboullosa** [comment]
@Horsmann You can cherry pick onto the 1.8.0 branch the commits you made in the master branch. Use the history view in Eclipse to do that. Switch to the 1.8.0 branch, go to the history, right click the master commit and choose "cherry pick" in the context menu.

**Comment by Horsmann** [comment]
Thanks for the info.
The change didn't break anything so I am closing this one.
