### ISSUE TITLE
Create  type system for discourse processing (RST, PDTB)

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-core#774]
Parsers for RST and PDTB are gaining popularity, a type system for these two would be nice.

**Comment by habernal** [comment]
Maybe it's time to close #585 as "won't fix"?

**Comment by reckart** [comment]
I have posted a number of questions as line comments on the commit:

https://github.com/dkpro/dkpro-core/commit/7b8d75d1762058ffd8037feb128243fe72762367

**Comment by habernal** [comment]
@reckart Thanks for the comments - I fixed the easy ones in #774 and answered to the remaining ones.
