### ISSUE TITLE
GitHub webpage: broken links on components page

### ISSUE THREAD

**Issue by chmeyer** [dkpro/dkpro-core#781]
Links to segmenters on https://dkpro.github.io/dkpro-core/releases/1.7.0/components/ are broken. Same for other components. Maybe also other pages are affected.

**Comment by reckart** [comment]
Fixed.

**Comment by reckart** [comment]
Actually other pages are afffected...

**Comment by betoboullosa** [comment]
The three menu links to recipes (java, Groovy, Jython) are also broken.

**Comment by reckart** [comment]
Jep, just fixed it...
