### ISSUE TITLE
ResourceCollectionReaderBase should (optionally) log progress

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#784]
It would be useful if the ResourceCollectionReaderBase could produce a log message on calls to nextFile() as this would give a nice indication of the progress of a pipeline. E.g.:

```
Feb 19, 2016 10:47:28 AM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase nextFile(315)
INFO: Processing [13/1635]: file:/.../some/file.xml
```

**Comment by reckart** [comment]
We could possibly even pick up the ProgressMeter class from DKPro Lab and use it here. ProgressMeter also tries to give an ETA.

**Comment by reckart** [comment]
Leaving at 1.9.0 because we probably want to see if logging this at info level is a good idea.

**Comment by carschno** [comment]
When reading large collections, this really seems to be too much to be useful. We might consider to reduce the logging frequency to a (configurable/sensible default) of every nth document. The default value might depend on the total number of resources.
