### ISSUE TITLE
Unable to resolve fangorn and several other dependencies

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#785]
1. The artifact dependency fangorn in dkpro-core-io-fangorn-asl/pom.xml can not be resolved.
2. The artifact dependency edu.illinois.cs.cogcomp.lbj.pos and edu.illinois.cs.cogcomp.lbj in dkpro-core-libj-asl/pom.xml
3. other artifacts might also be affected.

- [ ] Proper repository should be added to parent pom.

**Comment by reckart** [comment]
These repositories are already added if the profile "deps-not-on-maven-central" is enabled. If this profile is not enabled, then the modules should not even be detected by Maven / Eclipse. We do not want to have a reference to the "public-ext-releases-local" outside this profile.

Please revert the change.

**Comment by maxxkia** [comment]
removed the change
