### ISSUE TITLE
TokenizedTextWriter should use PARAM_SINGULAR_TARGET

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#789]
TokenizedTextWriter always writes to one big file no matter how PARAM_SINGULAR_TARGET is set. This is because TokenizedTextWriter existed before PARAM_SINGULAR_TARGET. The component should be changed to write multiple files as usual and should rely on PARAM_SINGULAR_TARGET for writing to a single large file. PARAM_SINGULAR_TARGET is afaik handled be the superclass so that TokenizedTextWriter can remain ignorant of the actual parameter.

**Comment by carschno** [comment]
I am not exactly sure what the expected behaviour should be.

**Comment by reckart** [comment]
By default, the writer should write one file per CAS. If PARAM_SINGULAR_TARGET is set to true, then it should write only to a single file. Typically, nothing needs to be done for PARAM_SINGULAR_TARGET other than that the writer should use the getOutputStream() provided by JCasFileWriter_ImplBase. This stream can even be closed as usual. The JCasFileWriter_ImplBase takes care of managing the stream and writing to either a single file or multiple files.

**Comment by reckart** [comment]
In other words: the writer should not worry all about PARAM_SINGULAR_TARGET - it should just use getOutputStream() and that's it.
