### ISSUE TITLE
Testrunner fails for writers using `getOutputStream()`

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#791]
The method `TestRunner#runTest()` throws an IllegalArgumentException for `JCasFileWriter_ImplBase` implementations that use the `getOuputStream()` method because they do not have a `DocumentMetadata` annotation. The exception is subsequently raised in `getRelativePath()`.
For a call like this: `TestRunner.runTest(writer, "en", text);`:
(from `TokenizedTextWriterTest`, line 53, after (locally) adapting `TokenizedTextWriter` to apply `getOuputStream()` (#789))

    Caused by: java.lang.IllegalArgumentException: java.lang.Throwable: CAS does not contain any de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData
	at de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData.get(DocumentMetaData.java:389)
	at de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData.get(DocumentMetaData.java:439)
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasFileWriter_ImplBase.getRelativePath(JCasFileWriter_ImplBase.java:234)
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasFileWriter_ImplBase.getOutputStream(JCasFileWriter_ImplBase.java:149)
    ...

This happens because `TestRunner#runTest(String aDocumentId, AnalysisEngine aEngine, String aLanguage, String aDocument)` is called with `aDocumentId` set to null. This prevents  DocumentMetadata from being created (line 133 in `TestRunner.java`).

I would suggest to create an empty DocumentMetadata in those cases instead of none. This should prevent the IllegalArgumentException, but I am not sure about potentially harmful implications of an empty DocumentMetadata annotation.

**Comment by carschno** [comment]
The easiest solution seems to be to assign a fake id (e.g. `"id"`) instead of null in `TestRunner#runTest(AnalysisEngine aEngine, String aLanguage, String aDocument)` (line 100).

**Comment by carschno** [comment]
I've now added the TokenizedWriter.java version using getSourceStream() to the repository. In order to circumvent this issue, I've adapted the corresponding unit tests and manually added an documentId.

**Comment by reckart** [comment]
For readers/writers we typically use IOTestRunner, not TestRunner.

**Comment by reckart** [comment]
With regards to TestRunner, couldn't you just use the method in line 120?

**Comment by carschno** [comment]
Yes, that is how I've done it now. Will leave it like that for the time being and use IOTestRunner for future writer tests.
Closing this issue.
