### ISSUE TITLE
Remove PARAM_USE_LEMMAS and use generic feature paths instead

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#803]
When converting tokens/lemmas to Mallet data types, this should not happen statically (through PARAM_USE_LEMMAS), but instead a generic solution should allow for arbitrary annotations.

**Comment by carschno** [comment]
PARAM_USE_LEMMAS has been deprecated (not removed) for backwards compatibility.

**Comment by reckart** [comment]
For component parameters (and actually for most things except the type system and API modules), we are so far pretty generous in making modifications, changing things, and not worrying too much about backwards compatibility. I think the parameter can and should be removed.

**Comment by carschno** [comment]
TODO: remove PARAM_USE_LEMMA.
