### ISSUE TITLE
Word2Vec models should optionally be compressed for reading and writing

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#804]
The text files produces by Word2Vec (#798) should optionally be stored in ZIP/GZIP.

  * [x] `Word2VecEstimator`: Use `PARAM_COMPRESSION` (via `getOutputStream()`) to store file in a compressed format
  * [x] `Word2VecAnnotator`/`Word2VecUtils`: read compressed files

**Comment by carschno** [comment]
No matter what compression method is set, the following code produces an invalid output file:

    WordEmbeddings matrix = new WordEmbeddings(instanceList.getDataAlphabet(), dimensions,                windowSize);
    matrix.countWords(instanceList);
    matrix.train(instanceList, getNumThreads(), numNegativeSamples);
    try {
       PrintWriter printWriter = new PrintWriter(getOutputStream(parentDir.getPath(),                    getCompressionMethod().getExtension()));
       matrix.write(printWriter);
       printWriter.close();
    }
    catch (IOException e) {
        throw new AnalysisEngineProcessException(e);
    }

For instance when setting `PARAM_COMPRESSION = CompressionMethod.GZIP`:
    
    $ gzip -t dummy.vec.gz 
    gzip: dummy.vec.gz: unexpected end of file

and

    java.io.EOFException: Unexpected end of ZLIB input stream
    ...

Manual analysis shows that all the actual lines are written, but apparently the compressed output file is not finalized properly. Setting `PARAM_COMPRESSION = CompressionMethod.NONE` perfectly produces the expected results (in an uncompressed output file).
Playing around with `printWriter.flush()`, `OutputStream os = getOutputStream(...); ...; of.flush(); os.close()` in all possible variations does not make a difference.

**Comment by reckart** [comment]
I have just whipped up a simple unit test for TextWriter using GZip compression and that seems to work nicely. Commit 328e4144a9343845fdc0397ddfb0d4eecdf43936

**Comment by reckart** [comment]
Hm is this using PARAM_SINGULAR_TARGET maybe?
