### ISSUE TITLE
Add mappings to other type systems (1.9.0)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#821]
Add information how the DKPro Core types relate to other typesystems / schemata.

**Comment by reckart** [comment]
@maxxkia If you want to improve mappings to other type systems, this is relevant issue.

**Comment by maxxkia** [comment]
Ok, I will add the DKPro to Universal Dependencies mapping with this issue number.

**Comment by reckart** [comment]
Open a new issues for another version of DKPro Core.
