### ISSUE TITLE
Fix LdaTopicProportionsWriter

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#827]
The deprecated class `LdaTopicProportionsWriter` should be re-written so that it writes a per-file output format comprising topic proportions in the format
    
    <val_topic1>
    <val_topic2>
    <...>
    <val_topicn>

For instance `<docid>.<modelname>.topics`:
    
    0.4
    0.3
    0.3

Alternatively, a single file for the full collection to look like this:

    <doc_1>\t<val_topic1>\t<val_topic2>\t<...>\t<val_topicn>
    <doc_2>\t<val_topic1>\t<val_topic2>\t<...>\t<val_topicn>

**Comment by reckart** [comment]
And it remains deprecated?

**Comment by carschno** [comment]
No, it shall no longer be deprecated then.

**Comment by carschno** [comment]
The output needs to be unified to output one line per document, either in a singular target or in multiple targets:

    [<docid>\t]<topic1>\t<topic2>\t...<topicn>
