### ISSUE TITLE
Introduce isSingularTarget in JCasFileWriter_ImplBase

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#828]
The parameter `PARAM_SINGULAR_TARGET` implement in `JCasFileWriter_ImplBase` (introduced in #505) is not accessible by inheriting writers. However, some writers might need to adapt their output format according to the value (cf. #827). Hence, a simple getter method `isSingularTarget()` should make the value of `singularTarget` readable:

    public boolean isSingularTarget() {
         return singularTarget
    }

**Comment by reckart** [comment]
I think it should not be necessary to access that parameter. Why do you need it?

**Comment by carschno** [comment]
To adapt the behaviour of a writer (e.g. per-document topic proportions as in #827):
For a singular target, write

    <doc1> <topic1> ...
    <doc2> <topic1> ...

For a non-singular target:

`doc1.topics`:

    <topic1>
    <topic2>
    ...

`doc2.topics`:

    <topic1>
    <topic2>
    ...

**Comment by reckart** [comment]
I would tend towards having a separate parameter that controls whether or not to include the document ID in the output. Even when writing to multiple targets, having this ID in there can be useful.
