### ISSUE TITLE
Surefire tests for "de.tudarmstadt.ukp.dkpro.core.io.reuters-asl" failing

### ISSUE THREAD

**Issue by errantlinguist** [dkpro/dkpro-core#831]
When trying to build and install the package locally using Maven (i.e. `mvn install)`, the `test` target fails when running `de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578TxtReaderTest`:

	-------------------------------------------------------
	 T E S T S
	-------------------------------------------------------
	Running de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578TxtReaderTest
	log4j:WARN No appenders could be found for logger (org.springframework.core.io.support.PathMatchingResourcePatternResolver).
	log4j:WARN Please initialize the log4j system properly.
	log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
	Apr 28, 2016 3:19:44 PM de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578TxtReader initialize(97)
	INFO: Found 2 files.
	Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.232 sec <<< FAILURE! - in de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578TxtReaderTest
	test(de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578TxtReaderTest)  Time elapsed: 1.188 sec  <<< FAILURE!
	org.junit.ComparisonFailure: expected:<[BAHIA COCOA REVIEW]> but was:<[STANDARD OIL <SRD> TO FORM FINANCIAL UNIT]>
		at de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578TxtReaderTest.test(Reuters21578TxtReaderTest.java:58)

	Running de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578SgmlReaderTest
	Apr 28, 2016 3:19:44 PM de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578SgmlReader initialize(62)
	INFO: Extracting Reuters-21578 documents from src/test/resources/reuters-sgml
	Apr 28, 2016 3:19:45 PM de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578SgmlReader initialize(64)
	INFO: 1000 documents read.
	Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.906 sec - in de.tudarmstadt.ukp.dkpro.core.io.reuters.Reuters21578SgmlReaderTest
	Running de.tudarmstadt.ukp.dkpro.core.io.reuters.ExtractReutersTest
	Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.235 sec - in de.tudarmstadt.ukp.dkpro.core.io.reuters.ExtractReutersTest

	Results :

	Failed tests: 
	  Reuters21578TxtReaderTest.test:58 expected:<[BAHIA COCOA REVIEW]> but was:<[STANDARD OIL <SRD> TO FORM FINANCIAL UNIT]>

	Tests run: 3, Failures: 1, Errors: 0, Skipped: 0

	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 8.437s
	[INFO] Finished at: Thu Apr 28 15:19:47 CEST 2016
	[INFO] Final Memory: 24M/265M
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project de.tudarmstadt.ukp.dkpro.core.io.reuters-asl: There are test failures.
	[ERROR] 
	[ERROR] Please refer to /home/local/UKP/shore/src/UKP/dkpro/dkpro-core/dkpro-core-io-reuters-asl/target/surefire-reports for the individual test results.
	[ERROR] -> [Help 1]
	[ERROR] 
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR] 
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by carschno** [comment]
Thanks for reporting! I am currently unable to reproduce the problem. In my setup, the test passes as well as all other in the Reuters module. Our Jenkins server did not report any problems either.

Could you provide us with some more details, especially which DKPro version you are using?

**Comment by errantlinguist** [comment]
I pulled from the GitHub head: https://github.com/dkpro/dkpro-core/commit/411e1aced0706828a722e45413c97f871554d027

**Comment by carschno** [comment]
I think the test depends on a specific order in which the two input files are opened and processed. That order is in fact arbitrary, so the comparison fails when the order is different to what is expected. Apparently, we have always been lucky.
Thanks for reporting, I'm fixing it!

**Comment by reckart** [comment]
DKPro Core readers should always return the files in the same order (they are internally sorted). Cf. ResourceCollectionReaderBase line ~ 511.

**Comment by carschno** [comment]
I see. I'll fix the reader then.

**Comment by reckart** [comment]
If your reader inherits from ResourceCollectionReaderBase, it should automatically be sorted (no need for you to do anything). But it may indicate that the problem comes from elsewhere, e.g. Hashmaps having different iteration orders in Java 7 and Java 8 or such...

**Comment by carschno** [comment]
It doesn't though. It inherits from JCasCollectionReader_ImplBase which does not seem to inherit from ResourceCollectionReaderBase.

**Comment by reckart** [comment]
Can you change it to inherit from ResourceCollectionReaderBase or JCasResourceCollectionReader_ImplBase ?

**Comment by carschno** [comment]
I can, but I implemented my own method to look up the specific corpus files, so the sorting process implement in `ResourceCollectionReaderBase` won't help.
