### ISSUE TITLE
Make Reuters readers inherit from JCasResourceCollectionReaderBase

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#832]
`Reuters21578TxtReader` and `Reuters21578SgmlReader` should both inherit from `JcasResourceCollectionReaderBase` and look up files using the provided methods.
cf. #831

**Comment by carschno** [comment]
The complicated part is: how to allow for a configurable source location while pre-defining the file name pattern (which is an essential part of the corpus)?

**Comment by reckart** [comment]
The user should define the pattern - it should not be predefined. Mind that the pattern doesn't have to be a pattern - it can e.g. be a list of concrete file names.

**Comment by carschno** [comment]
Ok, this might be acceptable, but the currently fixed pattern (which then needs to be specified by the user) is: `reut2-*.txt`. I am not sure this is a proper Ant-style pattern, is it?

**Comment by reckart** [comment]
It is a proper ant-pattern, yes.
