### ISSUE TITLE
Maven test failure for artifact "dkpro-core-io-brat-asl":BratReaderWriterTest

### ISSUE THREAD

**Issue by errantlinguist** [dkpro/dkpro-core#835]
Latest commit: ee6302080b8b7fe1011fba2552dcfc5e9f5f81aa

In [Surefire test report](https://github.com/dkpro/dkpro-core/files/247102/de.tudarmstadt.ukp.dkpro.core.io.brat.BratReaderWriterTest.txt):

> Tests run: 8, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 6.103 sec <<< FAILURE! - in de.tudarmstadt.ukp.dkpro.core.io.brat.BratReaderWriterTest
> testConll2009(de.tudarmstadt.ukp.dkpro.core.io.brat.BratReaderWriterTest)  Time elapsed: 0.295 sec  <<< FAILURE!
> org.junit.ComparisonFailure: 
> expected:<...i-semantics-type-Sem[anticArgument 4 11	economy

**Comment by reckart** [comment]
@errantlinguist Yup, just looking into it. Looks like the BratReader/Writer require an extension to handle WebAnno-style slot features.

**Comment by reckart** [comment]
Should be fixed via https://github.com/dkpro/dkpro-core/commit/86383d2197c8488b07de68741b0b915088ce2e01
