### ISSUE TITLE
Maven test for "dkpro-core-clearnlp-asl" (ClearNlpParserTest) failed: "OutOfMemoryError: GC overhead limit exceeded"

### ISSUE THREAD

**Issue by errantlinguist** [dkpro/dkpro-core#836]
**Last commit:** 86383d2197c8488b07de68741b0b915088ce2e01
**Build system:** x86_64 with 2 CPU cores and 8GB RAM (see attached [lscpu.txt](https://github.com/dkpro/dkpro-core/files/248361/lscpu.txt))
**Java version:** 1.8.0_91-b14 (64-bit mixed mode)

I'm not sure if this is a problem with the project itself or if my system can't handle the test(s) which are failing: `de.tudarmstadt.ukp.dkpro.core.clearnlp.ClearNlpSegmenterTest` reports "OutOfMemoryError: GC overhead limit exceeded" (see [attached test output](https://github.com/dkpro/dkpro-core/files/248364/de.tudarmstadt.ukp.dkpro.core.clearnlp.ClearNlpParserTest.txt)). I get the error even when running `mvn install` with the environment variable `MAVEN_OPTS=-Xmx3072M`; How much memory should this test case need?

**Comment by reckart** [comment]
We run the Maven build with `-Dmaven.surefire.heap=5g` on the Jenkins. I am not sure setting MAVEN_OPTS helps here, since this is the memory for the forked unit test JVM, not for the main Maven JVM.

**Comment by errantlinguist** [comment]
I tried running with `MAVEN_OPTS="-Xmx1024M;-Dmaven.surefire.heap=5g"` but am still getting:

> ClearNlpParserTest.testEnglishMayo » OutOfMemory GC overhead limit exceeded

How exactly do you set `maven.surefire.heap`?

**Comment by reckart** [comment]
`mvn -Dmaven.surefire.heap=5g clean install`
