### ISSUE TITLE
Stanford Lemmatizer throws NPE when POS tags are missing

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#838]
If a Token does not have a POS tag, the method `Token#getPos()` returns null which provokes a NullPointerException in StanfordLemmatizer (cf. https://github.com/dkpro/dkpro-core/commit/eaabf7009f7882d087acd4b7164ed5cc37e0ff54).

I suggest to check the value of `getPos()` and to call `token.set(PartOfSpeechAnnotation.class, t.getPos().getPosValue()); only if it is not null.

**Comment by reckart** [comment]
Doing what you suggested will cause another NPE inside the CoreNLP Lemmatizer component itself.

We can check if the POS is there and if not, throw a sensible exception with a good error message
We could try checking if the POS is there and if not simply not lemmatize the given word. As long as the CoreNLP lemmatizer does not take into account context (and I think it does not) that could work as well.

**Comment by carschno** [comment]
I'll go for the sensible exception for now.
