### ISSUE TITLE
Move Mallet module to dkpro-core-gpl?

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#844]
As Mallet is licensed under the Common Public License (CPL) [1], I wonder whether the Mallet DKPro Core module should be moved from dkpro-core-asl to dkpro-core-gpl. It seems to me that CPL is located somewhere between the two. Wikipedia [2] tells me:

> CPL, like the GNU Lesser General Public License, allows non-CPL-licensed software to link to a library under CPL without requiring the linked source code to be made available to the licensee.

To my understanding, this indicates that CPL is more or less compatible with the ASL, at least as far as DKPro Core is concerned. I am not quite sure though; any more informed opinions about this?

[1] https://opensource.org/licenses/cpl1.0.php
[2] https://en.wikipedia.org/wiki/Common_Public_License

**Comment by carschno** [comment]
Since LGPL is compatible enough as well to be used in ASL modules, I suppose that the more liberal CPL is acceptable as well.

**Comment by reckart** [comment]
Weak copyleft libraries are not a problem to have in the ASL part.
