### ISSUE TITLE
macro import in build.xml points to googlecode

### ISSUE THREAD

**Issue by pkluegl** [dkpro/dkpro-core#846]
There are some url imports in build.xml files that point to the old googlecode project. These should probably be replaced by a link to the github project. 

Example:
line in dkpro-core-treetagger-asl/src/scripts/build.xml
`<url url="http://dkpro-core-asl.googlecode.com/svn/built-ant-macros/tags/0.6.0/ant-macros.xml"/>`
should read something like 
`<url url="https://raw.githubusercontent.com/dkpro/dkpro-resource-packager/master/ant-macros.xml"/>`

**Comment by reckart** [comment]
The URL should not point to the master branch but to a stable tag on github. E.g. `https://raw.githubusercontent.com/dkpro/resource-packager/0.7.0/ant-macros.xml`. I don't remember if there were any breaking changes between 0.6.0 and 0.7.0...
