### ISSUE TITLE
Update TreeTagger build.xml

### ISSUE THREAD

**Issue by betoboullosa** [dkpro/dkpro-core#849]
Update TreeTagger build.xml to create new models and binary

**Comment by betoboullosa** [comment]
Changes in 1.8.0 were made in commit 26adf1d0fe86bee2ed2516291e0dc8f8f1024aef

**Comment by betoboullosa** [comment]
@reckart should all the build.xml files both in 1.8.0 and 1.9.0 have the import url changed from googlecode to githubusercontent? Stanfordnlp module, for example, points to googlecode

**Comment by reckart** [comment]
Yes, they all need to be changed. But make sure you keep the version. Some point to a 0.6.0 version, others point to a 0.7.0 version, etc.

**Comment by betoboullosa** [comment]
Created issue #880
