### ISSUE TITLE
TreeTaggerPosTaggerTest fails with outOfMemory exception

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#850]
TreeTaggerPosTaggerTest.hugeDocumentTest fails with outOfMemory exception when trying to package the project. This even happens having allocated 10GB to maven. Maybe the test should be deactivated?

```
Tests run: 16, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 34.976 sec <<< FAILURE! - in de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosTaggerTest
hugeDocumentTest(de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosTaggerTest)  Time elapsed: 22.584 sec  <<< ERROR!
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosTaggerTest.runTest(TreeTaggerPosTaggerTest.java:974)
    at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosTaggerTest.hugeDocumentTest(TreeTaggerPosTaggerTest.java:891)
```

**Comment by reckart** [comment]
Looks like a problem with the CasValidator that runs after the test to check that the CAS content is consistent with our expectations:

```
Thread [main] (Suspended (breakpoint at line 720 in ArrayList))	
	ArrayList<E>.batchRemove(Collection<?>, boolean) line: 720	
	ArrayList<E>.removeAll(Collection<?>) line: 690	
	PosAttachedToTokenCheck(TokenAttributeAttachedToTokenCheck_ImplBase).check(JCas, List<Message>, String, Class<Annotation>) line: 52	
	PosAttachedToTokenCheck.check(JCas, List<Message>) line: 35	
	CasValidator.analyze(JCas, List<Message>) line: 80	
	CasValidator.analyze(JCas) line: 70	
	AssertAnnotations.assertValid(JCas, Class<Check>...) line: 904	
	TestRunner.runTest(String, AnalysisEngine, String, String) line: 146	
	TestRunner.runTest(AnalysisEngine, String, String) line: 100	
	TreeTaggerPosTaggerTest.runTest(String, String, String[], String, String[], String[], String[]) line: 974	
	TreeTaggerPosTaggerTest.hugeDocumentTest() line: 891	
        ...
```

The validator is not optimized for performance or large CASes - probably should not even be called here.

**Comment by maxxkia** [comment]
Ok, so this is why it takes so long to execute in eclipse. Thanks for clarification.

**Comment by reckart** [comment]
I guess we never let that test run after introducing the CasValidator...

**Comment by reckart** [comment]
@betoboullosa please `@Ignore` the hugeDocumentTest for now.

**Comment by betoboullosa** [comment]
OK. In my case, running from the command line, the test apparently hanged without any error. After almost 3 hours without an answer, I interrupted it.

**Comment by reckart** [comment]
Normally, the tests in the TreeTagger module should not even run. They should only run if the profile `se-proprietary-resources` is enabled. If this is not enabled, the tests should detect that the models are not available and skip themselves.
