### ISSUE TITLE
Update TreeTagger build.xml

### ISSUE THREAD

**Issue by betoboullosa** [dkpro/dkpro-core#851]
Update TreeTagger build.xml to create new models due to binary update

**Comment by kouylekov-usit** [comment]
Hi I am not sure if you are working on that. I have recently used the built script to get the models in the appropriate artifacts and noticed there is URL change for the MACOSX binnary from:

http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-MacOSX-3.2-intel.tar.gz
to 
http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-MacOSX-3.2.tar.gz

**Comment by reckart** [comment]
@kouylekov-usit please feel free to update the build.xml file with the new URL. When you do so, please make sure to change the version of the "bin" JAR to match the timestamp of the new file. You can get that timestamp by checking the last changed header returned by `curl -I <url>`. Also the version in the pom dependency management would need to be updated then to match the new version in the build.xml file.

**Comment by tilmanbeck** [comment]
URL-changes of the [language parameter files](http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/) 
Example:
http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/bulgarian-par-linux-3.2-utf8.bin.gz
moved to
http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/bulgarian.par.gz
