### ISSUE TITLE
CoreNlpParserTest.testExistingPos sometimes fails

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#852]
As discussed on the [mailing list](https://groups.google.com/forum/#!topic/dkpro-core-developers/5cmuCesEM9k), the CoreNlpParserTest.testExistingPos unit test seems to fail occasionally due to unpredictable results. Upstream currently seems unable to reproduce this (https://mailman.stanford.edu/pipermail/java-nlp-user/2016-May/007631.html).

However, as a temporary fix, we could disable the `-TMP` category. In the shipped binary, this option is available through the `-retainTmpSubcategories` flag. We need to see how to implement this in our DKPro Core wrapper.

**Comment by carschno** [comment]
I guess we need to create a `TreeNormalizer` like this in `CoreNlpParser.initialize()`:

    TreeNormalizer treeNormalizer = NPTmpRetainingTreeNormalizer(englishTrain.splitTMP, ...)

That normalizer should then be passed as an additional parameter to some/all of `ConvertToUima.convertPOSs()`, `ConvertToUima.convertConstituents()`, `ConvertToUima.convertPennTree()`, and `ConvertToUima.convertDependencies()` and the respective calls in `CoreNlpParser.process()` need to be adapted.

I have some doubts though about whether the TreeNormalizer can always be an `NPTmpRetainingTreeNormalizer`, independently of language and tree specificities, and how and where it should be applied to which trees.

**Comment by reckart** [comment]
How would the missing of the TreeNormalizer explain that sometimes parse X is created and other times parse Y?

**Comment by carschno** [comment]
It doesn't (as far as I can see). I was thinking of this as a workaround as we appear to be unable to isolate the actual problem.

**Comment by reckart** [comment]
I'm not sure we have actually tried to isolate the actual problem. I did some reading of code in CoreNLP yesterday night looking for obvious "static" declarations, but I didn't yet fire up a debugger and investigate that in more depth.

**Comment by carschno** [comment]
Also, I find it rather confusing that the problem never occurred in my local installation, while Jenkins fails very regularly.

**Comment by reckart** [comment]
Are you locally running tests in Eclipse or Maven?

**Comment by carschno** [comment]
Maven and IntelliJ.

**Comment by reckart** [comment]
Hm. So I suspect that this issue crops up on Jenkins because Maven Surefire runs tests differently than e.g. the JUnit Plugin in Eclipse. Basically, I expect a leak between tests that sometimes appears and sometimes not depending on the test execution order. I am not sure how IntelliJ runs tests - using Surefire directly or using it's own runner. I would kind of expect that if we run builds using Maven on the command line for a while, the problem should probably also crop up (randomly) at some point. 

The default run order in SureFire is "filesystem" (http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html)... considering to switch that to "random" for DKPro Core builds.

**Comment by carschno** [comment]
Ok, I've now been running the test a couple of times a few times through Maven and it has occurred locally as well.

**Comment by carschno** [comment]
Small update: when setting `CoreNlpParser.PARAM_NUM_THREADS` to 1, the error still occurs.

**Comment by carschno** [comment]
It might have to do with the model: when setting `CoreNlpParser.PARAM_VARIANT` to `"pcfg"`, the error does not seem to occur.
The default is `"factored"`, right?

**Comment by reckart** [comment]
Ok, that would hint at the rnn model not being deterministic for some reason. If we mention that to upstream, maybe they have an idea.

**Comment by carschno** [comment]
True. However, `testEnglishRnn()` passes reliably even for hundreds of runs. I suppose that is because the test sentence is longer/more complicated.

**Comment by carschno** [comment]
I've created a gist with plain CoreNLP API using the RNN model and our test sentence. It also fails every once in a while: https://gist.github.com/carschno/3dd307c5dba4d4f0b74c6ee4597ee9c2

**Comment by carschno** [comment]
Since the upstream issue can probably not be expected to be fixed soon, a workaround might be to update the test so that it accepts both possible outcomes.

**Comment by reckart** [comment]
Still seeing this test to fail sometimes...

**Comment by reckart** [comment]
Catching Throwable should fix that test
