### ISSUE TITLE
Integrate IXA components (1.9.0)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#857]
Integrate IXA components.

**ixa-pipe-pos** - https://github.com/ixa-ehu/ixa-pipe-pos
- [X] OpenNLP-based POS tagger - uses IXA-specific features
DictionaryAnnotator?
- [X] OpenNLP-based lemmatizer - uses IXA-specific features

Additional tasks deferred to #1139

**Comment by reckart** [comment]
Current problem: most of the components come only as fat jars.

See also: https://groups.google.com/d/msg/ixa-pipes-users/V02tGh4qYBg/SXdb37XOAgAJ

**Comment by kouylekov-usit** [comment]
Hi,

I have tried to build opennlp pos models.

The file http://ixa2.si.ehu.es/ixa-pipes/models/pos-resources.tgz does not contain
en-pos-perceptron-c0-b3-dev.bin

A similar model file is released http://ixa2.si.ehu.es/ixa-pipes/models/morph-models-1.5.0.tar.gz. Are the ixa models supported? 

Milen

**Comment by reckart** [comment]
I am not sure what your question is. We currently have components wrapping the IXA POS tagger and Lemmatizer and there is also a build.xml for the respective models: https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-ixa-asl/src/scripts/build.xml

The Maven JARs for the respective models created by this build script should be available here: https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local/de/tudarmstadt/ukp/dkpro/core/

**Comment by kouylekov-usit** [comment]
Sorry will be more verbose.
I have tried to crate an opnnlp module for LAP and could not fetch de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-pt-cogroo:jar from the repository.

[ERROR] Failed to execute goal on project dkpro-lap-tool: Could not resolve dependencies for project org.dkpro.core:dkpro-lap-tool:jar:0.0.1-SNAPSHOT: Could not find artifact de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-pt-cogroo:jar:20130527.1 in ukp-oss-releases (http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-releases/) -> [Help 1]

So I tried to use the build script.

ant local-maven

en-tagger-perceptron-ixa:
     [mkdir] Created dir: /home/milen/git/dkpro-core/dkpro-core-opennlp-asl/target/model-staging/de/tudarmstadt/ukp/dkpro/core/opennlp/lib

BUILD FAILED
/home/milen/git/dkpro-core/dkpro-core-opennlp-asl/src/scripts/build.xml:30: The following error occurred while executing this line:
/home/milen/git/dkpro-core/dkpro-core-opennlp-asl/src/scripts/build.xml:315: The following error occurred while executing this line:
/home/milen/git/dkpro-core/dkpro-core-opennlp-asl/src/scripts/build.xml:671: The following error occurred while executing this line:
https://raw.githubusercontent.com/dkpro/resource-packager/0.6.0/ant-macros.xml:445: The following error occurred while executing this line:
https://raw.githubusercontent.com/dkpro/resource-packager/0.6.0/ant-macros.xml:164: Warning: Could not find file /home/milen/git/dkpro-core/dkpro-core-opennlp-asl/target/download/ixa-pos-resources/en-pos-perceptron-c0-b3-dev.bin to copy.

Cheers Milen

**Comment by reckart** [comment]
Ah, I see. So the cogroo models are currently in the build.xml file of the OpenNLP module - but they are not really supported in OpenNLP. They should be moved over to the (experimental) cogroo module. The cogroo models are also *not* available on zoidberg.

If the packaging of the IXA models that are in the OpenNLP build.xml does not work anymore, then probably IXA has changed something - however, these models *are* packaged and available via zoidberg. But instead of using these, you'd probably rather want to use the IxaPosTagger with the respective models nowadays.

**Comment by kouylekov-usit** [comment]
Thanks.

Cheers Milen

**Comment by reckart** [comment]
@kouylekov-usit https://groups.google.com/forum/#!topic/ixa-pipes-users/JSTZ_WM_3ZM
