### ISSUE TITLE
Optionally replace stopwords instead of removing

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#861]
In Word2Vec (and possibly other applications), stopwords are sometimes not removed, but replaced by a generic token such as `STOP` in order to retain original word distances and syntactical structures.

I see three possible ways to implement this:

1. A non-mandatory `PARAM_STOPWORD_REPLACEMENT` parameter in `StopwordRemover.java`. If it is not specified (i.e. `null`), the remover should work as it does now (removing stopwords). If it is specified, stopwords should be replaced by its value (e.g. `STOP`). Annotations (e.g. lemmas) may be retained.
1. Use the `DictionaryBasedTokenTransformer`; a simple workaround could be to construct a dumb mapping dictionary where each stopword is mapped to the same output (`STOP`). A slightly more elegant way would be to add a transformer that reads a (stop)word list instead of a dictionary and has a parameter defining the output (`STOP`) for all words.
1. If the use case seems too specific for a general solution, it might be implemented in the specific class, i.e. in `MalletUtils#extractAnnotationValues`. However, this is how this feature is already implemented in `TokenizedTextWriter`, indicating at least two potential modules that might make use of it.

I think that implementing a new transformer as described in option 2 seems most elegant.

**Comment by carschno** [comment]
One more issue: how to handle annotations? A use case would be to also replace lemmas that have a value contained in the stopword list. Otherwise, all possible inflections of a stopword have to be listed in the lexicon.

**Comment by zesch** [comment]
We could use a feature path in order to specify which annotation/feature the stop word list is compared to.
1) sounds like a easy solution that doesn't break existing stuff
2) I don't know about that specific class - so I cannot comment on that

**Comment by reckart** [comment]
StopWordRemover.PARAM_PATHS - does that not work for you?

**Comment by reckart** [comment]
How about having such a replacement function in the mallet component instead of separately?

**Comment by carschno** [comment]
That is what I meant in option 3 and it seems least involved to implement. The idea to make this a general feature was that it is already implemented in `TokenizedTextWriter.java`.

**Comment by reckart** [comment]
Maybe extract the code into a utility class and place that in one of the API modules?

**Comment by carschno** [comment]
Due to time constraints, I've now implemented a less generic solution in the Mallet module. This should be extracted to a utility class (in the text-io module?).

**Comment by reckart** [comment]
I was thinking about `api-io`?

**Comment by carschno** [comment]
No more errors reported by asciidoctor in https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Core%20(GitHub)/1610/de.tudarmstadt.ukp.dkpro.core$de.tudarmstadt.ukp.dkpro.core.doc-asl/console.

**Comment by carschno** [comment]
This should be done now within the `*StringSequenceGenerator` classes in `de.tudarmstadt.ukp.dkpro.core.api.io.sequencegenerator`.
