### ISSUE TITLE
Add HDFS to FileWriter

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#869]
Although this might at least partially already exist in dkpro-bigdata, it might come handy to be able to write directly to a Hadoop filesystem (HDFS) from any writer in dkpro-core. For that specific task, dkpro-bigdata seems a bit of an overkill.

The most obvious location for implementation is the `JCasFileWriter_ImplBase#getOutputStream()` method. It might additionally check for a `hdfs:` prefix (similar to the Jar prefix) and then pass a [FSDataOutputStream](https://hadoop.apache.org/docs/r2.6.1/api/org/apache/hadoop/fs/FSDataOutputStream.html) to a new NamedOutputStream.

Hadoop settings could be configured through a couple of additional parameters, although they are probably read from the local Hadoop configuration in many cases.

Goal of this issue is to enable just any dkpro-core pipeline to write its output to HDFS, for instance when creating (very large) word embeddings from a corpus which are going to be processed further on a Hadoop (or Spark) cluster.

**Comment by reckart** [comment]
If we add this directly to the JCasFileWriter_ImplBase, we have a hard dependency on Hadoop in DKPro Core. The preferred way of supporting alternate file systems would be a mechanism as it was used in the readers, using a pluggable file system abstraction. Maybe Apache Commons VFS or something like that.

**Comment by carschno** [comment]
According to https://commons.apache.org/proper/commons-vfs/filesystems.html, Apache Commons VFS cannot write to HDFS.

Another idea might be to implement an abstract class JCasHdfsWriter_ImplBase that inherits from JCasFileWriter_ImplBase and overrides getOutputStream(). That class could reside in a dedicated module that depends on Hadoop. Downside would be though that every reader explicitly has to implement that class in order to be able to write to HDFS, instead of transparently allowing the user to pass a `hdfs:` target location to any writer.

**Comment by reckart** [comment]
* https://issues.apache.org/jira/browse/HDFS-1213
* https://commons.apache.org/proper/commons-vfs/apidocs/org/apache/commons/vfs2/provider/hdfs/package-summary.html

**Comment by reckart** [comment]
Having a separate JCasHdfsWriter_ImplBase would mean that only classes deriving from that could write to HDFS. That we couldn't just add that back to all the writers we already have.

**Comment by reckart** [comment]
* https://github.com/terrancesnyder/apache-vfs-hdfs

**Comment by carschno** [comment]
Reading has been implemented by @reckart, see #888.

**Comment by reckart** [comment]
If we switch to VFS at some point, using that for reading would also be good.

**Comment by reckart** [comment]
Looks like somebody implemented a Spring ResourceResolver on top of VFS, so that should also be easily pluggable into our readers:

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22javaetmoi-spring4-vfs2-support%22
