### ISSUE TITLE
JWEB1T: irritating package name

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#872]
After adding the phrase annotator (#871) to the package `de.tudarmstadt.ukp.dkpro.core.frequency`, I realised that the module name (as specified in the module pom.xml) is `JWEB1T`. This seems a bit confusing, so I see two solutions:

1. change the module name in pom.xml to `Frequency`
2. change the package name to `de.tudarmstadt.ukp.dkpro.core.jweb1t` and remove the new phrase annotator classes to a different package.

**Comment by zesch** [comment]
+1 for (1).

The old name is just a leftover from the evolution of this module.

**Comment by reckart** [comment]
IMHO the module name in the POM is wrong and should be `DKPro Core ASL - Frequency (ASL)`

**Comment by reckart** [comment]
@betoboullosa I would suggest to cherry-pick this renaming also over to the 1.8.0 branch.

**Comment by betoboullosa** [comment]
Cherry-picked!
