### ISSUE TITLE
Rename Phrase type and move to api-segmentation

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#873]
The Phrase type generated in #871 should be moved to the module api-segmentation-asl. However, the name "phrase", although used by Mikolov et al. [1], is not really linguistically grounded and should hence be changed. In a linguistic sense, a phrase typically corresponds to a constituent such as noun phrase.

Here, a phrase represents a span that covers one or multiple tokens. It might hence be called multi-word expression, n-gram, surface form, etc. 

All of these terms have their pro and contra arguments. My priorities would be to make the usage intuitively clear, make the name generic enough to be used by similar annotators, and re-use existing types and classes if applicable. 

After having given it some thought, I have a tendency towards NGram because it already exists and seems intuitive enough. On the other hand, users might expect NGrams to be of stable lengths (i.e. unigrams, bigrams, etc.) rather than flexibly assigned to one or multiple tokens. Also, the NGram feature `text` seems unnecessary and hence potentially confusing here (`Annotation#getCoveredText()` should suffice).

Are there any other opinions?

[1] Mikolov, Tomas, Ilya Sutskever, Kai Chen, Greg S Corrado, and Jeff Dean. “Distributed Representations of Words and Phrases and Their Compositionality.” In Advances in Neural Information Processing Systems 26, edited by C. J. C. Burges, L. Bottou, M. Welling, Z. Ghahramani, and K. Q. Weinberger, 3111–3119. Curran Associates, Inc., 2013. http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf.

**Comment by judithek** [comment]
Your phrase type annotation (as you describe it) is highly useful also in other contexts (e.g. the SemanticFieldAnnotator could easily be extended to use it).

Regarding the naming issue:
- ngram might be a bit misleading, because "phrase leaning" according to the Mikolov paper you cite aims to learn something like idiomatic n-grams / lexicalized n-grams rather than other very frequent n-grams like "this is".

- I do not fully share your comment about a phrase corresponding to a constituent in a linguistic sense. Phrase in a linguistic sene is mainly characterized by the property of having a head so the POS of the head extends to the phrase.

I am still thinking of alternatives, these are just first thoughts. 

Judith

**Comment by carschno** [comment]
Regarding surface form, this is the relevant issue: #874.
However, the notion of a surface form does not seem to match very well to this "phrase" scenario.

**Comment by carschno** [comment]
@judithek Regarding the phrase definition, I guess this sort of phrase (idiomatic/lexicalized n-gram), could be interpreted as a phrase where the head is not known/(or not explicitly annotated). Would you agree or is this a misuse (or too broad definition) of the definition for "phrase"?
In other words: can we stick with the term phrase without making linguists angry?

**Comment by reckart** [comment]
My unqualified suggestion for a type name would have been "MultiTokenUnit". That said, I feel the name would be too general to be really useful... E.g. a NamedEntity is usually also a MultiTokenUnit. SemanticToken maybe?

**Comment by carschno** [comment]
@reckart I would argue against `SemanticToken` because it imposes a semantic motivation. However, it may be useful to annotate syntactically motivated phrases (TODO: find use case).

I think MultiTokenUnit is accurate, but in order to use established terminology, I would prefer MultiWordExpression to make the naming more intuitive; even though it may include tokens that aren't words.

**Comment by judithek** [comment]
@carschno recent work on supersense tagging of MWEs uses your suggested MultiWordExpression in a similar way as Mikolov in his paper:
"... the semantically holistic nature of multiword expressions (MWEs) including idioms, light verb constructions, verb-particle constructions, and many compounds ..."
see Schneider & Smith: http://repository.cmu.edu/cgi/viewcontent.cgi?article=1156&context=lti

So there are many use cases apart from named entities. Another not mentioned are multiword discourse markers.
-> this is an argument pro MultiWordExpression

@carschno @reckart SemanticToken has the advantage that it is not familiar, people do not associate possibly misleading properties with it. Why would it be a problem to impose a semantic motivation? I can not think of any purely syntactically motivated phrases ... the point is the non-compositional behaviour regarding the semantics

**Comment by judithek** [comment]
argument con MultiwordExpression: 
multiword expressions can be discontinuous, e.g. those involving verbs; some examples have been posted here: https://github.com/stanfordnlp/CoreNLP/issues/202

**Comment by judithek** [comment]
@carschno regarding phrase:
I fully agree with your interpretation - this sort of phrase (idiomatic/lexicalized n-gram), could be interpreted as a phrase where the head is not known/(or not explicitly annotated).
In fact, multiword expressions are a special kind of phrase: see also: http://www.aclweb.org/aclwiki/index.php?title=Multiword_Expressions

So why not keeping Phrase? or maybe LexicalPhrase?

**Comment by carschno** [comment]
My conclusion is that we can in fact stick with the name "Phrase". Unless there still are objections, I'll move this type to the segmentation module in the next days, ok?

**Comment by reckart** [comment]
I would still tend rather towards SemanticToken ;) As @judithek also said, I believe it is less likely to cause confusion for people mistaking Phrase for something different then you imagine.

**Comment by zesch** [comment]
It was under the impression that no consensus had been reached so far.

If we want something generic, the options seem to be something along the lines of Ngram/MultiToken.
All other proposal impose some kind of semantic interpretation that is valid in one context, but not in another.

In the example provided by @carschno in #874 one could re-use already existing Ngram annotations, but as the order is mixed, it is not optimal.
However, introducing another annotation is also not.

Thus, how about re-using Ngram?

**Comment by reckart** [comment]
N-gram gives the impression that all n-grams should have the same size. Also, it is not really a n-gram thing, is it? N-gram boundaries are not semantically motivated but are rather a fixed window size.

**Comment by zesch** [comment]
I agree, but what is the semantics in that special case? It seems a bit vaguely defined to me.

**Comment by betoboullosa** [comment]
I don't like using phrase, because it has different meanings and scopes depending on the context, the theory used and the level of analysis. I'd prefer MultiWordExpression, although it could imply more than one word, as @carschno said. What about SingleMultiWordExpression? Or MultiSingleWordExpression?

**Comment by reckart** [comment]
SingleMultiWordExpression sounds really confusing ;)

**Comment by maxxkia** [comment]
Just a quick thought ...

How about WordSequence?

**Comment by betoboullosa** [comment]
Sounds good.

**Comment by carschno** [comment]
I had not expected this to be so tricky... :) I'm trying to sum up the arguments so far here; feel free to directly edit this comment.

- Phrase
	- Pro
	  - Could be seen as linguistic phrase where the head is unknown
	  - Generalization of MultiWordExpressions
	- Con
  	  - In linguicistcs, typically corresponds to a syntactic constituent/something having a head
  	  - Different meanings and scopes depending on context, theory, and level of analysis
	
- NGram
	- Pro
	  - already exists, can be re-used
	- Con:
	  - users might expect constant n
	  - users expect non-semantic motivation
	  - misleading for idiomatic/lexicalized n-grams
	
- MultiTokenUnit
	- Pro
	  - describes well what it is
	- Con
	  - too general
	  - introducing new terminology

- SemanticToken
	- Pro
	  - not familiar, no misleading associations
	  - semantic motivation is usually/always given
	- Con
	  - imposes semantic motivation (vaguely defined/context-dependent)
	
- MultiWordExpression
	- Pro
	  - used in a similar way as Mikolov et al. use "phrase"
	- Con
	  - MWEs can be discontinuous
	  - Should always comprise multiple tokens

- SingleMultiWordExpression, MultiSingleWordExpressions
	- Con
	  - confusing

- WordSequence

**Comment by zesch** [comment]
WordSequence has no pro/con so far :)
Con: Word is not well defined anyway.
-> TokenSequence

That is pretty close to MultiTokenUnit.
If I had to choose between the two, I would prefer TokenSequence, as it stresses the sequential nature, as we do not allow discontinuous units (right?), which would be possible for MultiTokenUnit.

**Comment by reckart** [comment]
I would like to see pervasive support for discontinuity in DKPro Core at some point using a global approach, e.g. a feature by a specific name to associate additional spans. So I would opt to keep the question of discontinuity out of the present discussion. IMHO it is orthogonal.

**Comment by maxxkia** [comment]
For me TokenSequence doesn't necessarily convey continuity, rather it pictures a collection of tokens having a specific order (as opposed to e.g. a TokenSet).

So, one could also have ContiguousTokenSequence or NonContiguousTokenSequence.

**Comment by betoboullosa** [comment]
Yes, you can have non contiguous sequences. For example: "Non-Contiguous Word Sequences for Information Retrieval"  http://www.aclweb.org/anthology/W04-0412

**Comment by reckart** [comment]
I am not sure if I said it here already, but I would prefer to avoid a completely generic name. This is an annotation for a quite specific purpose. The "Phrase" suggested by @carschno captures this reasonably, I only see some conflict with concepts established in the users head (e.g. noun phrase, verb phrase, prepositional phrase, etc.). But I would certainly prefer Phrase over N-Gram or TokenSequence or SingleMultiTokenUnit etc.

The point of this discussion is trying to choose a name which we don't have to change again very soon and one which the users can reasonably understand. 

I think we should go wrapping it up now. @carschno suggested the introduction of the type. We discussed it. I think we have had quite a bit of input. Personally, I'd now just ask @carschno to make an informed decision and just live with that ( at least until DKPro Core 2.0 ;) )

**Comment by carschno** [comment]
That seems a lot of responsibility. ;)
In the list above, I forgot to add @judithek's suggestion `LexicalPhrase` which seems a good compromise to me.

Another new suggestion (sorry!) that has just occurred to me is `Chunk`. I thought this was even better suited, but ad-hoc, I haven't been able to find a linguistic definition. It seems to be in use mostly in the field of language learning/acquisition.

**Comment by reckart** [comment]
We already have a type called Chunk ;) We use it for Chunking!

**Comment by judithek** [comment]
@carschno chunk is also used in parsing (I believe the term was coined in this context, by Steven Abney);
chunking in this sense is partial / shallow parsing; chunks are non-recursive (in contrast to constituents), there are noun chunks, verb chunks etc.

I updated the pro/con list

**Comment by carschno** [comment]
Ok, so I'm falling back to `LexicalPhrase` as my personal favourite, unless there are strong objections remaining against it.

**Comment by reckart** [comment]
@carschno just do it ;)
