### ISSUE TITLE
Extend POS mapping of British National Corpus

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#876]
The BNC part of speech mapping does not contain many of the dual pos-tags (see below list of missing values)

These tags can be mapped to the first mentioned POS' coarse word class (see discussion: https://groups.google.com/forum/#!topic/dkpro-core-developers/BTfVn_mKQUw)

```
AJ0-AV0
VVN-AJ0
AJ0-VVG
CJS-AVQ
DT0-CJT
AV0-AJ0
AJ0-VVN
CJT-DT0
VVZ-NN2
PRP-AVP
CJS-PRP
NN1-VVG
NN2-VVZ
VVD-VVN
AJ0-VVD
NN1-VVB
NP0-NN1
VVD-AJ0
VVN-VVD
VVG-NN1
AJ0-NN1
NN1-AJ0
AVP-PRP
PRP-CJS
PNI-CRD
NN1-NP0
CRD-PNI
VVB-NN1
VVG-AJ0
AVQ-CJS
```

**Comment by Horsmann** [comment]
I just saw that `NP0` is still mapped to 'N' instead of 'NP' if fix this too.

**Comment by Horsmann** [comment]
@betoboullosa Is it already too late add changes to `1.8.x` ^^?

**Comment by betoboullosa** [comment]
No, I can still cherry pick them if needed.

**Comment by Horsmann** [comment]
Then please `cherry-pick` this one please :)

**Comment by betoboullosa** [comment]
Done!

**Comment by carschno** [comment]
I guess these changes are the cause for the BncReaderTest failing, aren't they?

**Comment by Horsmann** [comment]
oops, thanks. I will cherry-pick it to 1.8.0 once it is fixed

**Comment by betoboullosa** [comment]
@Horsmann I'm receiving an error during BncReaderTest (I've already applied your changes):

> Failed tests: 
>   BncReaderTest.test:33 expected:<...alue: "CJC"
> [phone]
> [NN
>    sofa: _InitialView
>    begin: 466
>    end: 471
>    PosValue: "NN1-VVB"
> [phone]
> Lemma
>    sofa: _InitialView
>    begin: 466
>    end: 471
>    value: "phone"
> [phone]
> Token
>    sofa: _InitialView
>    begin: 466
>    end: 471
>    lemma: Lemma
>       sofa: _InitialView
>       begin: 466
>       end: 471
>       value: "phone"
>    pos: NN]
>       sofa: _Initia...> but was:<...alue: "CJC"
> [phone]
> [O
>    sofa: _InitialView
>    begin: 466
>    end: 471
>    PosValue: "NN1-VVB"
> [phone]
> Lemma
>    sofa: _InitialView
>    begin: 466
>    end: 471
>    value: "phone"
> [phone]
> Token
>    sofa: _InitialView
>    begin: 466
>    end: 471
>    lemma: Lemma
>       sofa: _InitialView
>       begin: 466
>       end: 471
>       value: "phone"
>    pos: O]
>       sofa: _Initia...>
> 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
>

**Comment by Horsmann** [comment]
The error on 1.8.x is from build 94 (yesterday) the update from today is still in the wait-queue. My Jenkins builds the master branch again. If you wait a bit longer it should be ok.

**Comment by betoboullosa** [comment]
I'm trying to build locally.

**Comment by Horsmann** [comment]
hm, it works locally on `1.8.x` for me and on `master`.
Are you sure you picked the change locally? 

This part in the error message you posted suggest you did not 
```
[O
sofa: _InitialView
begin: 466
end: 471
PosValue: "NN1-VVB"
[phone]
```
That is a mapping I added in commit 7376ee60723532

**Comment by Horsmann** [comment]
UKP Jenkins finished building - BNC module seems fine now but the Stanford module failed.

**Comment by betoboullosa** [comment]
As I said, I had already applied your changes, and even so I was receiving the error. But after I made a clean it passed ok.

**Comment by carschno** [comment]
@Horsmann If it's Stanford CoreNLP that fails, it may be unrelated (cf. #852).

**Comment by Horsmann** [comment]
Ok - I don't really see why the BNC mapping file should have an effect on Stanford. So I close this again and hope things fix themselves.
