### ISSUE TITLE
Introducing new "coarseValue" feature on POS type

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#886]
I am consider to introduce a new "coarseValue" feature on POS type. This would be for two cases:

* to retain coarse-grained tag information read from source files that support such information, e.g. BNC ("pos" column) or CoNLL formats ("cpos" column)
* to allow editing such a feature in WebAnno (the DKPro Core elevated types are not convenient for that and presently not supported in WebAnno at all)
* for cases where users may wish to assign their coarse-grained categories without defining their own UIMA types and writing their own mapping files

Looking for feedback. Any objections?

**Comment by Horsmann** [comment]
I like the idea of having an own field for setting a coarse POS.
Would the current "coarse" mapping information be removed then `getClass().getSimpleName()`? Or would we introduce yet another mapping that maps the coarse value of the `corpus` to the `dkpro coarse type`?

**Comment by zesch** [comment]
We should ensure that all relevant DKPro components write the elevated type AND the coarse POS attribute.
Then one could use the attribute value instead of the class name.

**Comment by reckart** [comment]
I would want to have the "coarsePosValue" *not* be managed by DKPro Core (as the elevated types are) but rather use this as a vehicle to pass through information verbatim from source files or from specific components that support coarse-grained tags.

**Comment by reckart** [comment]
That means if the coarsePosValue would not be available from an input file and if no component in a pipeline actually fills it, then it would simply remain empty until the end. 

We could consider creating a specific component which maps fine-grained tags to coarse-grained tags, but it would be up to the user to add that to a pipeline. I wouldn't wish that to happen automatically behind the curtains.

**Comment by zesch** [comment]
I am worried then about users being confused why the taggers in Core do not set this field.
They are using the mapping anyway and write the elevated types. So I would expect them to write the attribute too.

**Comment by reckart** [comment]
The elevated type may not be the same as the coarse-grained tag. It should be compatible. We would use BNC "pos" tags for the coarse grained tags or CoNLL-U universal POS tags or Petrov's universal POS tags. Our own "elevated" types are yet another tagset. We plan to align it with the CoNLL-U universal POS tags. But we would still need the freely settable "coarsePosValue" in order to pass e.g. BNC "pos" or Petrov's POS verbatim through a pipeline.

E.g. I am implementing support for CoNLL-U elseissue and currently am unable to recover the cpos column from the original input file because our elevated types are more coarse-grained than the CoNLL-U set. Same problem for other CoNLL formats.

**Comment by reckart** [comment]
I would also make it a new option PARAM_WRITE_CPOS to enable coarse POS writing and have it off by default even for components that support it (except readers).

**Comment by reckart** [comment]
Ok, maybe components that support it explicitly in their models should write them. But I am not really convinced about introducing yet another mapping mechanism for those that don't. @zesch or do you suggest to simply set the elevated type name as the coarse-grained name in such a case?

**Comment by zesch** [comment]
Yes, that would be my suggestion. Everything else would be highly confusing.
Of course, users are free to overwrite it with their own mapping if needed.

2016-06-18 11:44 GMT+02:00 Richard Eckart de Castilho <
notifications@github.com>:

**Comment by judithek** [comment]
I agree with @zesch

**Comment by judithek** [comment]
Although it might be some work until all the taggers are adapted

**Comment by judithek** [comment]
Alternatively the feature name could be changed so that the 2 specific use cases are somehow expressed

**Comment by reckart** [comment]
Renaming "coarsePosValue" to "coarseValue".

With two values, the interesting question is: which value should be used for mapping? I'm currently opting for being conservative and continue to use the fine-grained value for tag-to-UIMA-type mapping.

**Comment by reckart** [comment]
@zesch So if we do not have a fine-to-coarse mapping or if the mapping falls back to the generic "POS" annotation type, what should we then write into the *coarseValue* feature? Should it then be null or `POS` (i.e. annotation.getClass().getSimpleName()).

**Comment by zesch** [comment]
I see pros/cons for both. Writing POS would probably make the code less cluttered.

Regarding the other question, I think that the fine-grained values should be used for mapping.

**Comment by reckart** [comment]
Hm, I think I would prefer setting "null" instead of "POS". POS could in theory be an actual coarse-grained tag and then we would have no way to discern between unset and POS. Also, filling in POS tags in a user interface would be more tedious if users need to explicitly set the coarse tag always to "POS" instead of simply leaving it unset.

**Comment by zesch** [comment]
I guess that would also be ok.
