### ISSUE TITLE
Links on main documentation page broken

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-core#889]
It seems that all links on https://dkpro.github.io/dkpro-core/ are currently broken.

**Comment by reckart** [comment]
Which ones? I clicked a few and they all worked for me.

**Comment by logological** [comment]
These don't work for me; there may be others:

https://dkpro.github.io/dkpro-core/releases/1.8.0/components/
https://dkpro.github.io/dkpro-core/releases/1.8.0/models/
https://dkpro.github.io/dkpro-core/releases/1.8.0/formats/
https://dkpro.github.io/dkpro-core/releases/1.8.0/typesystem/

**Comment by zesch** [comment]
ok, it only seem to be the ones pointed out by @logological 
I must admit I only clicked at those and then decided that everything must be broken.

**Comment by reckart** [comment]
Ok, should be fixed now.
