### ISSUE TITLE
Langdetect: string unescaping might cause Exception

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#900]
The language detect tool performs a string unescaping operation 
`StringEscapeUtils.unescapeJava(documentText);`
If it the input string is somewhat malformed garbage input might be attempted to be parsed to a number resulting into an exception.

A try-catch should be added that silently catches and ignores those cases making no language prediction in those cases.

**Comment by reckart** [comment]
Uh... why should it perform that operation at all? Input text is input text... why does it require unescaping?

**Comment by Horsmann** [comment]
If the input text is not unescaped the language detection doesn't really work at all. In case its normal ASCII text nothing happens. The tool is made for social media in particular and the raw data you get are usually escaped like Twitter. I think it makes sense to do this to ensure that the data is in a form that allows proper language identification.

**Comment by Horsmann** [comment]
Well, we could introduce a parameter enabling the escaping (default turned off)?

**Comment by reckart** [comment]
Well, I think the respective reader for that specific Twitter format should handle the unescaping such that the text in the CAS is already clean. Another option would be to implement a "normalizer" for this. We have a "text normalization" framework in DKPro Core.

**Comment by Horsmann** [comment]
i think that would be too much decoupling. You don't know that a normalization might be necessary unless it is actually part of the wrapper. 
If you separate this you would furthermore introduce some complexity to know which information shall be language identified. If the reader reads unescaped  text you want to use the document text if there is a normalization module you probably would have to read it from an alternative location or annotation?
As this tool is for social media I don't think it hurts if this tool provides a convenient switch for that. Especially because the results you got if you work on escaped text are trash.

**Comment by reckart** [comment]
The [documentation](https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/component-reference.html#engine-LangDetectLanguageIdentifier) for the component says nothing about social media:

```
Langdetect language identifier based on character n-grams.
```

Also from the name it sounds like a generic component for all kinds of texts.

If I use the component with normal text, e.g. from a news paper, will it work without unescaping?

It sounds to me that the problem of escaped data is not in the component, but rather in the document data. Thus IMHO the document should be unescaped.

**Comment by Horsmann** [comment]
The models that exist are for web and Twitter I think I.e. It only supports social media. 
If you remove it from the module you probably will not know that unescaping is necessary- ideally the reader should provide correctly processed text but realistically the user might not know that.
In terms of helping the user to correctly use this tool I think it should at least offer to do the unescaping.
So, it is more a usability thing.

**Comment by reckart** [comment]
I assume that all other DKPro Core components will also be unable to work with escaped data, so shouldn't the such twitter data be unescaped early and permanently in the pipeline (i.e. in a reader or normalizer)? If no component can process escaped data, why limit the unescaping only to this component?

@zesch any opinion?

**Comment by zesch** [comment]
I don't understand why this kind of unescaping should be necessary at all.
@Horsmann Can you provide an example?

**Comment by Horsmann** [comment]
A twitter sample as you get it from the 1% stream looks for instance like this if it is written with non-ascii characters 
`\u3069\u3046\u3057\u305f\u306e\u3001\u9ed2\u304d\u6226\u4eba\uff1f`
Running langid on this one will give you pretty random results which is why I introduced this unescaping.

**Comment by zesch** [comment]
On input like that, _any_ further processing with our tools will fail.
So it would be better to use a normalization component to change this kind of input before processing, instead of changing _all_ our components to treat this kind of input.

This view agrees with @reckart I guess, but the discussion is a bit long, so I am not fully sure.
