### ISSUE TITLE
Recognizing multiple named entity types on a noun phrase using NLP

### ISSUE THREAD

**Issue by whatsthebeef** [dkpro/dkpro-core#901]
I'm currently using OpenNLP with UIMA to label words in a sentence. It's important that a single word can be labelled more than once. For example David Cronenberg should be labelled as director and person.

I know the training process is implemented correctly because I have a custom model file and when all sentences with one of the labels is removed from the model file the other label is detected.

I would preferably be able to continue to use OpenNLP to double label words. Is there a way to do this? If not is this possible with another library such as Stanford CoreNLP.

The code that gets the labels is below:

    List<NamedEntity> entities = JCasUtil.selectCovered( NamedEntity.class, aConstituent );
        if ( !entities.isEmpty() ) {
            // is never more than 1
        }

And some sample training data is below (there are hundreds of lines similar to this.)

    <START:person> David Cronenberg <END> directed <START:film> Crash <END> .
    <START:director> David Cronenberg <END> directed <START:film> Scanners <END> .

**Comment by reckart** [comment]
I don't think that the OpenNLP named entity recognizer itself is able to generate more than one label. A solution for you would be to train separate classifiers, one for "person" and one for "director" and add two OpenNlpNamedEntityRecognizer components to the pipeline, each using of of your trained models.

**Comment by whatsthebeef** [comment]
I don't think this solution suites my requirements because the classifiers are quite dynamic and there are quite a lot of them (100+). I'm not sure what performance issues having so many AnalysisEngines has on performance.

**Comment by zesch** [comment]
As long as the underlying tool supports the functionality you are looking for, the DKPro/UIMA side supports having multiple NE types at the same position/chunk.

**Comment by whatsthebeef** [comment]
@zesch So you think openNLP is the limitation here? Any suggestions for what might work?

**Comment by reckart** [comment]
@whatsthebeef get a faster machine and use 100+ classifiers ;)

**Comment by reckart** [comment]
@whatsthebeef *If* OpenNLP supports getting multiple annotations instead of just "the best", we could also support that in DKPro Core. But I do not think it does. Supporting n-best for a sequence classification task that uses multi-token features also doesn't seem completely trivial to me.

**Comment by zesch** [comment]
@reckart At some point, we were thinking about a general feature "confidence". Using this + multiple annotations over the same span would support n-best without a major overhead.

**Comment by reckart** [comment]
@zesch Sure, but that is not what I meant.

What I mean is if you get output like this from a sequence classifier

```
John    B-PERSON,0.9    I-PERSON,0.8    O,0.5
Miller   B-PERSON,0.8    O,0.6
```

... what would it mean? You could not assume that the first column is one annotation and the second is another. Maybe "John" is the person, maybe "John Miller", maybe nothing. And this becomes worse if there there is not only a single label (person) but multiple labels.

**Comment by whatsthebeef** [comment]
Just adding all annotation over a certain score would work for me. The score could be configurable or the library could just return all annotations and allow the app to filter. What sized modification would be necessary to implement something like this?

**Comment by reckart** [comment]
@whatsthebeef it would require that OpenNLP offers an API where you can actually request the n-best. I am not aware of such an API. That would be a question for the OpenNLP mailing list. There is an API by which we can get the probabilities/confidence of the last-returned spans, but I see nothing where you would request like the n-best overlapping spans.

**Comment by whatsthebeef** [comment]
@reckart What's the API to get the probabilities?

**Comment by reckart** [comment]
E.g. opennlp.tools.namefind.NameFinderME.probs()

**Comment by whatsthebeef** [comment]
Yeah, I already checked that one and the alternative models aren't there so there must be a deeper problem.

**Comment by reckart** [comment]
I wouldn't call a function that is simply not implemented a "problem". It would be a problem if such a function was there but it would actually not be work. As I said: I would suggest to inquire on the OpenNLP list to ask the OpenNLP developers if they believe what you require is supported - or if it is not supported, possibly whether there is a conceptual/technical reason that it is not supported or just simply a lack of time or that so far nobody came up with the requirement (or both).

**Comment by whatsthebeef** [comment]
I meant a problem in my approach rather than the library.

I've posted to the OpenNLP mailing list and I am going to try implement my own NameFinderME type class that handles multiple sequences. If it works or I get a useful response from the mailing list I will post back so we can tie up this issue.

**Comment by zesch** [comment]
Answering the question by @reckart from 2 hours ago:
I agree, this would be a problem. The proposed solution was meant more for situations where a tool returns multiple solutions for a given span.

And also answering the question by @whatsthebeef from even longer ago :)
I am not aware of any tools that offer the kind of functionality you are looking for. Running single classifiers as @reckart suggested seems to be a workaround.
I think your approach is valid. There are some papers about it, e.g. 
http://talukdar.net/papers/mld09_multi_label.pdf
However tool support for this kind of task seems to be rather thin.

**Comment by whatsthebeef** [comment]
Because of certain design choices I have already made the problem @reckart identified isn't so important to me right now and as I mentioned, the dynamic nature of the labels in my design means separate classifiers will add a lot of extra complexity. I've therefore implemented a bit of a hacky solution that appears to work quite well for now by overriding `TokenNameFinder` in openNLP and casting the value from `modelProvider.getResources` to allow me to fetch a 3d Span array of all possibilities above a certain score.

**Comment by reckart** [comment]
@whatsthebeef maybe you could consider contributing a patch for such a functionality to OpenNLP.

**Comment by reckart** [comment]
I think this can be closed now.
