### ISSUE TITLE
Naming convention for components that generate models

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#913]
We now have kind of two naming conventions for NLP components that train models to be used by a respective companion component, e.g.:

* `LdaTopicModelEstimator`<-> `LdaTopicModelInferencer`
* `OpenNlpPosTaggerTrainer` <-> `OpenNlpPosTagger`

Can we agree on a single scheme?

**Comment by reckart** [comment]
I think "Trainer" is probably more intuitive than "Estimator". I also thought about "ModelWriter" and "ModelGenerator" but that seemed to long to me.

**Comment by carschno** [comment]
The estimator/inferencer is derived from the Mallet terminology ([estimate() method](http://mallet.cs.umass.edu/api/cc/mallet/topics/ParallelTopicModel.html#estimate())) and [Inferencer](http://mallet.cs.umass.edu/api/cc/mallet/topics/TopicInferencer.html). For the latter, I would prefer to stick with `Inferencer` -- there is no clear analogy to something like `Tagger` anyway.

For the `Estimator`, I agree. -> `LdaTopicModelTrainer` then?

**Comment by reckart** [comment]
Sounds good to me 👍
