### ISSUE TITLE
Use default PARAM_FILENAME_EXTENSION where applicable

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#937]
Use the ComponentParameters.PARAM_FILENAME_EXTENSION where applicable. We still have many components that use a locally defined PARAM_FILENAME_SUFFIX.

**Comment by pkluegl** [comment]
6

Am 07.08.2016 18:52 schrieb "Richard Eckart de Castilho" <
notifications@github.com>:

**Comment by reckart** [comment]
@pkluegl ?
