### ISSUE TITLE
Add missing capability annotations (1.9.0)

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#938]
Add missing capability annotations. Well, there appear still to be missing several despite having addressed this issue already two times in the past. Maybe it is time to set up some sanity tests, e.g. automatically looking at the imports for UIMA types and requiring that imported types are declared either as input or output capabilities.

**Comment by carschno** [comment]
One issue I tend to have regularly is that the input type of some components are configurable through e.g. a `PARAM_FEATURE_PATH` parameter. In those cases, would you recommend to specify the default (e.g. Token) or to omit explicit capability declarations?

**Comment by reckart** [comment]
I see three cases:

* types hardcoded - capability must be present
* types configurable but have a default - tend towards not adding them as capabilities
* types configurable with no default - no capability

**Comment by reckart** [comment]
I am not particularly settled on the configurable types with defaults. Thinking about end users (who tend not to configure such things in many cases), adding the capabilities may be useful. Thinking about automatic validation, adding them would be harmful.

**Comment by carschno** [comment]
I would recommend to add each concerned module's label to this issue whenever stumbling across a missing annotation, so module maintainers can easily become aware of their responsibility.

**Comment by reckart** [comment]
When I stumble over missing capabilities, I add them. I suggest everybody does that - instead of pushing the task to somebody else.

**Comment by carschno** [comment]
That's clearly the better approach. I was thinking of situations in which I wasn't able to fix it myself.

**Comment by reckart** [comment]
Then I would suggest to edit the initial comment here (can you do that?) and add a checklist there for components that need updating. In that way we can also see which of these subtasks have been completed.

In which cases can you not fix it?

**Comment by carschno** [comment]
In fact, I had nothing specific in mind. I was just looking at this issue and wondered whether any module I wrote was still affected. I tend to remove the whole discussion because my initial comment does no longer make sense.

**Comment by reckart** [comment]
Unless there is a security-relevant or abusive content, I'd tend not to remove posts.
