### ISSUE TITLE
Enable sort option by default for CasDumpWriter

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#940]
It would be good if value for `PARAM_SORT` is set to `true` by default in [CasDumpWriter](https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-testing-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/testing/dumper/CasDumpWriter.java).

Since `PARAM_SORT` is set to `true` (by default) in `testOneWay` and set to `false` in CasDumpWriter this might cause inconsistent results.

**Comment by reckart** [comment]
Changed default to true. Let's see if any tests fail now ;)Changed default to true. Let's see if any tests fail now ;)
