### ISSUE TITLE
Add support for the LXF format

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#954]
Add support for the LXF format as being under development in LAP project.
- [x] avoid using linkage information on edges
- [x] replace broken test data with dependencies with proper test data containing only a single set of morphology nodes
- [x] fix exporting dependencies in delta mode
- [x] when exporting dependencies, decide how to handle the ROOT node (DKPro Core does self-looping, LXF not?)

**Comment by reckart** [comment]
@kouylekov-usit do you know if the items so far not marked as completed in the initial issue description have been resolved?

**Comment by kouylekov-usit** [comment]
@reckart Yes they are all fixed. Is there a standard way for notification in the git commit messages ?

**Comment by reckart** [comment]
Commit mails go to a mailing list: https://groups.google.com/forum/#!forum/dkpro-core-source

I follow that list too. Since you fixed the "sub-issues", the question is if you have sufficient permissions check-off the items in the initial message here in the tracker. Can you check them off?

**Comment by kouylekov-usit** [comment]
@reckart No I can not

**Comment by reckart** [comment]
@kouylekov-usit I added you to the dev team - can you tick off the boxes now?

Adding you to the dev team also gives you write permissions to the repo. But we can (maybe should) continue for another while with pull requests and explicit reviews of them - ok?

**Comment by kouylekov-usit** [comment]
@reckart Yes I have checked them off. 

I agree it is wiser for review from you on updates. Anyway I do not expect them to be often.

**Comment by reckart** [comment]
Closing this. If there are further changes to be made to the LXF support, please open new issues.
