### ISSUE TITLE
Support for “Cut” operation in ApplyChangesAnnotator

### ISSUE THREAD

**Issue by mjunsilo** [dkpro/dkpro-core#973]
I originally implemented this as a preprocessor AE for the ApplyChangesAnnotator, which was an artificial way to introduce a new “cut” operation without modifying the original ApplyChangesAnnotator. It works similar to the Ruta Cutter AE with ApplyChangesAnnotator instead and this allows us to specify what not to delete as opposed to specifying all deletes. This simplified and optimised our workflow when we marked up SofaChangeAnnotation with Ruta because we had to specify more complex rule set before this. Previously our rule set produced a lot of small deletes that gave a large performance penalty in the backmapper as I recall, although that was also because of other things we needed to optimise further upstream. Paradoxically the preprocessor just converts the cuts into equivalent deletes but optimises a bit by removing or merging eventual redundant operations.

I don't think its a good idea to keep it as a separate preprocessor so I fully integrated it into ApplyChangesAnnotator by simply copying the code into a local preprocessing class. I am not sure whether there is much gained in rewriting the code to handle cuts differently instead of just transforming them to deletes but this would require a larger rewrite.

The component also lacks unit tests right now but we have used it for a while without discovering any new errors. That said, it would definitely benefit from unit tests since the implementation is a bit tricky and I would need to add this before doing any rewriting. However, I am not sure whether this is the smartest implementation so any suggestions are welcome.

Please review the current implementation in this forked branch:
https://github.com/mjunsilo/dkpro-core/blob/mjuric/cut-sofa-change/dkpro-core-castransformation-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/castransformation/ApplyChangesAnnotator.java

Note that the implementation currently depends on Java 8 streams and Guava 19.0, so if any of this is a "no go" then a rewrite is required.

**Comment by reckart** [comment]
DKPro Core is already based on Java 8.

Guava is not great, but also not a blocker. Guava is known to break its API between versions which makes it a bit inconvenient to use in a large project such as WebAnno where multiple components easily refer to different versions of the same library. Apache Commons projects have a more stable API and are generally preferred. This can be refactored later.

**Comment by mjunsilo** [comment]
Let me know if you know of an alternative to Guava TreeMultimap in Apache Commons since this could simplify the migration.

**Comment by reckart** [comment]
Looks like one can be constructed by subclassing [AbstractSetValuedMap](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/multimap/AbstractSetValuedMap.html) filling the constructor argument with a TreeMap and overriding createCollection to return a TreeSet... didn't try it though.

**Comment by reckart** [comment]
I'd prefer if `cut` would be handled at the same place as the other operations instead of transforming cut-operations into other operations at the level of SofaChangeAnnotations:

* I think it comes a surprise to the user if ApplyChanges modifies the original view which includes the SofaChangeAnnotations
* the original cut operations cannot be recovered after the action
* extra memory is used in the CAS heap

So I gather that `cut` is an optimized delete. Would it be sensible to optimize all delete operations or do you think it is good to keep `cut` and `delete` separately?

**Comment by mjunsilo** [comment]
I think all your points are valid, although I am not sure how big the extra memory requirements are since we don't ourselves observe any practical issues with this. Other AEs are far bigger memory consumers in our case.

The `cut` operation is for us most importantly an alternate way to specify deletes. It reduces complexity in capturing deletes if the stuff you want to keep is more well defined than what needs to be removed. It is a matter of convenience, and having this alternate approach to delete is also more intuitive in our case.

The optimisations are probably more secondary for us now, but it was a different matter when we did the first implementation 16 month ago. We had little control of the amount of fine grained delete and other operations being produced, which slowed down back mapping to a degree where it rivalled the POS tagger in computational complexity or even worse. This changed when we did a lot of optimisations further upstream, so we don't really produce many SofaChangeAnnotations anymore. However, if you have less control of fine grained deletes being produced then the optimisation may have an impact, but it modifies the original view as you already pointed out. It could be optional with a warning about its modifying behaviour.

Having this functionality via a pre-processor makes the choice at least more explicit but I think its an obscure AE, that won't really make that much sense to others, since it is a workaround.  It then makes a lot more sense to treat `cut` as an operation on its own, which is handled in the same place as the others. It's semantically different enough from delete, even though it can be defined in terms of them, but I would have to think about an alternative implementation, so that the original annotations are not just transformed. This is also why I am testing the idea before I spend too much time on this. We can live with our internal pre-processor just fine, but if others might have a benefit of this alternate delete operation, then I'll be happy to have a stab at it when I find some extra time.

BTW We can also name the operation differently if its functionality becomes more clear this way. The name was just inspired by the Ruta Cutter AE.

**Comment by mjunsilo** [comment]
I refreshed my memory by going back in our Git history in order to dig up more background on this feature. It turns out that we used Ruta for creating SofaChangeAnnotation using rules like:

ANY {-OR(PARTOF(BodyAnnotation),PARTOF(DescriptionAnnotation),...) -> CREATE(SofaChangeAnnotation, "operation" = "delete")};

This creates a lot of small deletes because the action is fired whenever an annotation occurs that isn't within the specified parts. This created performance issues in the backmapper together with other delete operation inside the remaining parts, which back then triggered the idea of introducing the `cut` operation. The optimisations where added later and they will have the same effect with `delete` by merging all overlapping deletes except that `cut` prevents unnecessary deletes to be created in the first place, and the rules also became easier to read.

**Comment by pkluegl** [comment]
Just a short comment on the the Ruta rule: a quantfier like ANY+ would probably do already some merging for you. 

btw PARTOF takes now a type list expression and interprets it as an `or`, e.g., `PARTOF({BodyAnnotation,DescriptionAnnotation})`

**Comment by mjunsilo** [comment]
Thanks, I wasn't aware of that ANY+ does some merging already. I'll try to play with this together with the new type list expressions to see how the rules work with it.

**Comment by reckart** [comment]
Is this still something to track or has the need for this feature meanwhile been resolved?

**Comment by mjunsilo** [comment]
I decided to postpone this work after looking closer at the implementation requirements to do it properly. I still think it would be nice to have, but I don't think it is worth the additional effort since we have internally already a working alternative that we can live with. The code for transforming cut annotations into deletes is available in the GitHub fork and can be put into separate AE in case someone wants to do something similar. I would therefore suggest we close this issue.

**Comment by reckart** [comment]
Ok, then let's close it.
