### ISSUE TITLE
Update to UIMA 2.10.0

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#977]
Update to UIMA 2.10.0.

**Comment by carschno** [comment]
In a project using DKPro Core, I now get the following error message when running `mvn compile` (project name anonymized):

> [ERROR] Failed to execute goal on project XXX: Could not resolve dependencies for project XXX:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.parameter-asl:jar:1.9.0-SNAPSHOT -> org.apache.uima:uimaj-core:jar:2.9.1: Failed to read artifact descriptor for org.apache.uima:uimaj-core:jar:2.9.1: Could not transfer artifact org.apache.uima:uimaj-core:pom:2.9.1 from/to ukp-central (https://scruffy.ukp.informatik.tu-darmstadt.de/artifactory/ukp-internal-grid): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

I am not sure how/if this is related, but it seems to be.
BTW, I have imported the most recent SSL certificate for scruffy.
