### ISSUE TITLE
Set isLastSegment on document metadata annotation in ResourceCollectionReader

### ISSUE THREAD

**Issue by Erfans** [dkpro/dkpro-core#994]
IsLastSegment does not set on DocumentMetadataAnnotation in ResourceCollectionReaderBase. 
It could be set when initialing resources (inner class `Resource`) and retrieve it later in initCas or by checking remained resources when `getNext` is called.

**Comment by reckart** [comment]
isLastSegment is a flag that would be used by a CAS multiplier to indicate whether a CAS that was split into multiple segments is the last of the split ones. This is not related to whether there are more resources available to a reader.
